const EVENT_EN_V5_03=Object.freeze({
"Дайте мне десять минут и человека, который умеет писать мелко":"Give me ten minutes and someone who can write small",
"Оба приказа выпущены одной канцелярией. Второй — через час после первого":"Both orders came from the same office. The second was issued an hour after the first",
"Пока взрослые спорят, кому она принадлежит, она поедет с нами. До города хватит времени разобраться":"While the adults argue over who she belongs to, she rides with us. We will have enough time to sort it out before the city",
"Если земля отвечает на договор, значит, одной подписи владельца здесь недостаточно":"If the land answers the contract, then the owner's signature alone is not enough here",
"Он не смерти боится. Он боится, что его забудут не там":"He is not afraid of death. He is afraid of being forgotten in the wrong place",
"Стена настоящая. Просто она стоит там, где раньше не стояла":"The wall is real. It simply stands where it did not stand before",
"Кажется, испытание уже идёт. Они просто об этом не знают":"It seems the trial is already underway. They simply do not know it yet",
"Оно не знает, кто мы. Оно ищет, чем нас можно заставить открыть его":"It does not know who we are. It is searching for what can make us open it",
"Письмо, которое читает адресата, всё равно остаётся текстом. Значит, у него есть грамматика — и ошибка, на которой его можно поймать":"A letter that reads its recipient is still a text. That means it has grammar—and a mistake we can catch it on",
"Судья имеет право молчать. Стороны — нет. Пусть сначала договорятся, что именно они считают правдой":"The judge has the right to remain silent. The parties do not. Let them first agree on what exactly they consider true",
"Когда символ власти отказывается решать, это хороший повод вернуть решение тем, кто умеет отвечать за последствия":"When a symbol of authority refuses to decide, that is a good reason to return the decision to those who can answer for the consequences",
"Дерево помнит ритм. Слова можно восстановить по паузам":"The tree remembers the rhythm. The words can be restored from the pauses",
"Если она хочет соревнования, можно дать ей соревнование":"If she wants a contest, we can give her one",
"Путь, который ревнует к другим дорогам, всё ещё путь. Иногда ему достаточно напомнить, что его выбрали":"A road jealous of other roads is still a road. Sometimes it only needs reminding that it was chosen",
"Они не исчезли. Их унесли":"They did not disappear. They were carried away",
"Их спор не о земле. Каждый хочет услышать, что мать любила именно его больше остальных":"Their argument is not about the land. Each wants to hear that their mother loved them more than the others",
"Разделить землю проще, чем право считать себя единственным наследником. Начнём хотя бы с первого":"Dividing the land is easier than dividing the right to call oneself the sole heir. Let us at least begin with the first",
"Если человек сам бросил оружие, не надо первым делом объяснять ему, кому он теперь принадлежит":"If someone laid down their weapon willingly, the first thing we should not do is explain who they belong to now",
"Это не заклинание дождя. Это заклинание призыва. А вот кого именно — написано очень неразборчиво":"This is not a rain spell. It is a summoning spell. What exactly it summons is written very poorly",
"Они не спорят о зубе. Они спорят о том, кто имеет право быть великодушным":"They are not arguing about the tooth. They are arguing about who has the right to be generous",
"Он не предсказывает судьбу. Он помнит кровь":"It does not predict fate. It remembers blood",
"Если это командир, с ним надо говорить как с командиром":"If this is a commander, then we speak to him as a commander",
"Пусть скажет сам. Я достаточно прожила среди людей, которые решали за связанных":"Let him say it himself. I have lived long enough among people who made decisions for those in chains",
"Он не опоздал. Просто дорога закончилась раньше его службы. Давайте дадим ей новый конец":"He is not late. The road simply ended before his service did. Let us give it a new ending",
"Они пришли не за ним. Они ждут того, кто должен был прийти вместе с ними":"They did not come for him. They are waiting for whoever was supposed to arrive with them",
"Он не проклят. Он просто не умеет оставить работу незаконченной":"He is not cursed. He simply does not know how to leave a job unfinished",
"Клятва связывает её. Его держит только чувство вины":"The oath binds her. Only guilt is holding him",
"Мёртвые редко просят продолжения. Если просят — стоит хотя бы дослушать":"The dead rarely ask for a continuation. If they do, we should at least hear them out",
"Он держал переход дольше, чем существовал его приказ. Теперь смена действительно прибыла":"He held the crossing longer than his order existed. Now his relief has truly arrived",
"Паутина закрывает дорогу. Но сама дорога всё ещё наша":"The web blocks the road. The road itself is still ours",
"Он не случайная жертва. Вопрос только в том, какую роль он играет в собственной казни":"He is not a random victim. The only question is what role he plays in his own execution",
"Она не повторяет его. Она учится быть им":"She is not copying him. She is learning to become him",
"Не уверен, что паук здесь самый нечестный игрок":"I am not sure the spider is the least honest player here",
"Тот, кто больше всех торопится увидеть правду, может бояться, что её увидят без него":"The one most eager to see the truth may be afraid it will be seen without him",
"Она уже знает, где проходит каждая артерия. Вопрос только в том, что она хочет делать с этим знанием":"She already knows where every artery runs. The question is what she intends to do with that knowledge",
"Нам не нужен лифт. Нам нужна одна шестерня и способ заставить её подняться":"We do not need the lift. We need one gear and a way to make it rise",
"Он не написал “лучший кузнец”. Он написал “лучше меня”. Возможно, речь вообще не о кузне":"He did not write “the best smith.” He wrote “better than me.” Perhaps this is not about a smith at all",
"Угол тут ни при чём. Они забыли вес мокрого снега":"The angle has nothing to do with it. They forgot the weight of wet snow",
"Это не замок. Это условие. И кто-то из предков был очень драматичным человеком":"This is not a lock. It is a condition. And one of the ancestors was a very dramatic person",
"Её нельзя догнать. Но можно заставить дорогу догнать её":"We cannot catch her. But we can make the road catch her",
"Тебе не нужно любить высоту. Тебе нужно доверять крыльям":"You do not need to love heights. You need to trust your wings",
"Он не прячет ловушку. Он рассчитывает, что никто не дочитает до неё":"He is not hiding the trap. He is counting on nobody reading far enough to reach it",
"Кажется, у нас есть дипломатический инструмент":"It seems we have a diplomatic instrument",
"Вина здесь не магия. Магия только не даёт человеку забыть, за что ему стыдно":"The guilt here is not magic. The magic only prevents the person from forgetting what they are ashamed of",
"Если ведомство не способно отличить заявителя от покойника, проблема не в заявителе":"If the office cannot tell an applicant from a dead person, the problem is not the applicant",
"Если это вход, у него должен быть хозяин. Если хозяина нет — его закрывают":"If this is an entrance, it should have an owner. If there is no owner, it gets closed"
});export{EVENT_EN_V5_03};