const EVENT_EN_V5_05=Object.freeze({
"Имя, которое тебе дадут четверо взрослых и один цветок, всё равно носить придётся тебе":"Whatever name four adults and one flower give you, you are still the one who has to carry it",
"Можно построить новый мост поверх старого и оставить ей нижний ярус. Фактически — крепость с крышей":"We can build the new bridge over the old one and leave her the lower level. Effectively—a fortress with a roof",
"Сначала освободим проход. Потом построим укрытие, которое не держит на себе половину дороги":"First we clear the passage. Then we build a shelter that is not carrying half the road on its back",
"Она ведёт не через лес. Она срезает расстояние":"She is not leading through the forest. She is cutting across distance",
"Короткая дорога редко любит тех, кто всё время проверяет, короткая ли она":"A short road rarely likes travelers who keep checking whether it is truly short",
"Удивительно. Это плохая ложка, но вполне приличная дубина":"Remarkable. It is a terrible spoon, but a perfectly respectable club",
"Это не кредит. Это ловушка, которая умеет считать":"This is not a loan. It is a trap that knows arithmetic",
"Он жульничает. Но хуже всего то, что он жульничает грамотно":"He is cheating. Worse, he is cheating competently",
"Пещеру можно проверить. Но пластину я бы из рук не выпускал":"We can inspect the cave. But I would not let go of the plate",
"Голос идёт не изнутри. Заклинание сидит в древесине":"The voice is not coming from inside. The spell is embedded in the wood",
"В споре между мошенником и страховой компанией я впервые хочу увидеть точную процедуру проверки пульса":"For the first time in a dispute between a swindler and an insurance company, I want to see the exact pulse-check procedure",
"Они оба правы, но говорят о разных рисках. Сначала кровь, потом операция":"They are both right, but they are talking about different risks. Blood first, operation second",
"Если бы она хотела его съесть, мы бы нашли совсем другую сцену":"If she wanted to eat him, we would have found a very different scene",
"Пока они спорят о том, кто имеет право его спасать, единственный хозяин тела остаётся без права голоса":"While they argue over who has the right to save him, the only owner of the body gets no say at all",
"Они уже сделали половину работы друг за друга. Осталось заставить камень и дерево учитывать рост":"They have already done half the work for each other. Now we only need to make stone and wood account for height",
"Они оба уже построили половину моста. Осталось убедить половины, что у них один берег":"They have each already built half a bridge. Now we only need to convince the halves they share the same bank",
"Текст изменился. Это не всегда означает, что он испорчен":"The text changed. That does not always mean it was corrupted",
"Проблема не в том, имеет ли он право. Проблема в том, что закон написан для мира, где люди умирают только один раз":"The problem is not whether he has the right. The problem is that the law was written for a world where people die only once",
"Они похожи только снаружи. Один использует давление, другой — очень плохое решение":"They only look alike from the outside. One uses pressure; the other uses a very bad idea",
"Он не охраняет лестницу. Он каждый раз закрывает путь тому, кто первым пытается уйти":"He is not guarding the stairs. He blocks whoever tries to leave first each time",
"Механически он работает лучше, чем раньше. Проблема у мастера не техническая":"Mechanically, he works better than before. The master's problem is not technical",
"Я думал, что потерял её. Похоже, в какой-то момент я просто перестал искать":"I thought I had lost it. It seems at some point I simply stopped looking",
"Возможно, это вообще не пароль. Возможно, он ждёт обращения":"Perhaps this is not a password at all. Perhaps it is waiting to be addressed",
"Если ты действительно знаешь мой следующий путь, назови то, чего я ещё не успел решить":"If you truly know my next path, name something I have not yet decided",
"Если здесь уже смогли усадить вместе орка, ангела и тёмную эльфийку, хозяин знает о дорогах больше большинства послов":"If someone here managed to seat an orc, an angel, and a dark elf together, the proprietor knows more about roads than most ambassadors",
"Она не оставляет следов. Значит, двигается не по земле. Можно закрыть ей обзор на цель, а не держать взгляд вечно":"She leaves no tracks. That means she is not moving over the ground. We can block her view of the target instead of watching forever",
"Прежде чем отвечать на вопрос о нашей цели, я бы выяснила, кто решил, что имеет право его задавать":"Before answering a question about our destination, I would find out who decided they had the right to ask it",
"Если дороги нет, это ещё не значит, что нет пути":"No road does not mean no path",
"Если путь обещает привести туда, куда мы действительно идём, я хочу проверить, понимает ли он разницу между целью и названием города":"If the path promises to take us where we are actually going, I want to see whether it understands the difference between a destination and a city's name",
"Если это налог, у него должна быть правовая основа. Если услуга — право отказаться":"If this is a tax, it needs a legal basis. If it is a service, there must be a right to refuse",
"Это не мельница создаёт ветер. Она стоит прямо над тем, откуда он выходит":"The mill is not creating the wind. It stands directly above where the wind is coming from",
"Картина — приманка. Интереснее человек, который заранее знал, кого ею ловить":"The painting is bait. The more interesting person is whoever knew in advance whom it would catch",
"Пехота различает людей не по лицам. По привычкам":"Infantry tell people apart not by faces, but by habits",
"В строю их различают не по лицам. Дайте команду, которую каждый привык выполнять по-своему":"In formation they are distinguished not by faces. Give an order each is used to carrying out differently",
"Он отвечает на вопросы, которых ему никто не задавал":"He is answering questions nobody asked him",
"Если он решит бежать за нами в одном таком, преимущество всё равно будет у нас":"If he decides to chase us wearing one of those, the advantage will still be ours",
"Это не память. Что-то действительно пришло по его следу":"This is not a memory. Something really followed his trail here",
"Сад не просит тишины. Он проверяет, умеем ли мы услышать то, что произойдёт после неё":"The garden is not asking for silence. It is testing whether we can hear what happens after it",
"Я польщена. Но у меня уже есть работа":"I am flattered. But I already have a job",
"Опор нет. Но нагрузка распределяется так, будто сооружение всё ещё здесь":"There are no supports. Yet the load is distributed as though the structure were still here",
"Лодка — не поражение перед мостом. Это просто мост, который умеет двигаться":"A boat is not a bridge admitting defeat. It is simply a bridge that can move",
"Быстрое. Тяжёлое. И оно старается обходить нас с ветра":"Fast. Heavy. And it is trying to circle us from downwind",
"Зал ждёт не красивой ноты. Он ждёт правильного прощания":"The hall is not waiting for a beautiful note. It is waiting for the proper farewell",
"Они репетировали. И очень хотят, чтобы всё прошло по плану":"They rehearsed. And they very much want everything to go according to plan",
"Это уже не кулинария. Это инженерная задача":"This is no longer cooking. It is an engineering problem",
"Если уничтожить символ, спор не исчезнет. Но хотя бы перестанет притворяться спором о мебели":"Destroying the symbol will not end the dispute. But at least it will stop pretending to be an argument about furniture",
"Хороший разведчик должен замечать кровь раньше, чем она появится":"A good scout should notice blood before it appears",
"Это не бог. Но у него достаточно памяти, чтобы держать обиду":"It is not a god. But it has enough memory to hold a grudge",
"Когда оно заговорит моим голосом, пусть хотя бы скажет что-нибудь умное":"When it speaks in my voice, let it at least say something intelligent",
"Юридически он покупатель. Биологически — отдельный вопрос":"Legally, he is a customer. Biologically, that is a separate question",
"Он купил место для себя. Не право оставить соседнюю землю пустой навечно":"He bought a place for himself, not the right to keep the neighboring land empty forever"
});export{EVENT_EN_V5_05};