const EVENT_EN_V5_11=Object.freeze({
"Традиция должна переносить народ через время. Не удерживать его под падающей горой":"Tradition should carry a people through time, not hold them beneath a falling mountain",
"Холод идёт снизу. Нагревать поверхность можно до следующей зимы":"The cold is coming from below. We could heat the surface until next winter",
"Третий либо победил, либо сейчас узнает цену художественной смелости":"The third contestant either won or is about to learn the price of artistic courage",
"Там ещё не горит. Но кто-то только что побежал именно туда":"It is not burning there yet. But someone just ran in exactly that direction",
"Если приговор будет суровым, хотелось бы услышать план его исполнения":"If the sentence is severe, I would like to hear the plan for enforcing it",
"Десяти минут у нас нет. Зато есть очень мотивированный таран":"We do not have ten minutes. We do have a very motivated battering ram",
"Память не исчезла. В ней словно вырвали одну страницу — и только одну":"The memory is not gone. It is as though one page—and only one—was torn out",
"По крайней мере, у неё честнее вывеска, чем у половины трактиров":"At least her sign is more honest than half the taverns",
"Победить претендентов и захотеть править — два разных испытания. Я бы не путал их":"Defeating the contenders and wanting to rule are two different trials. I would not confuse them",
"Если вор добровольно возвращает золото, я бы сначала выяснил, почему оно стало хуже тюрьмы":"If a thief voluntarily returns gold, I would first find out why it became worse than prison",
"Войны начинались из-за меньшего количества знаков препинания":"Wars have started over fewer punctuation marks",
"Самое тревожное не то, что он двадцать лет делает ненужную деталь. А то, что кто-то когда-то посчитал её нужной":"The most troubling part is not that he has spent twenty years making a useless part. It is that someone once thought it was necessary",
"Стены исчезли. Зато привычка объезжать ворота пережила их прекрасно":"The walls are gone. The habit of going around the gate survived them perfectly",
"Здесь осталась должность без ворот и приказ без города. Такие вещи опаснее разобрать, чем камень":"A post without a gate and an order without a city remain here. Such things are harder to dismantle than stone",
"Если ни один не хочет смерти другого, возможно, вопрос об оригинале важнее нам, чем им":"If neither wants the other dead, perhaps the question of which one is original matters more to us than to them",
"Если я её не вижу, это считается половиной путешественника?":"If I cannot see it, does that count as half a traveler?",
"Если они научились бояться, приказ включиться уже не ремонт. Сначала придётся разговаривать":"If they learned fear, ordering them to switch on is no longer a repair. First we will have to talk",
"Он явно понимает систему. Вопрос только в том, насколько твёрдо установлены тарифы":"He clearly understands the system. The only question is how firmly the rates are fixed",
"Судя по запасам, это не святотатство. Это профессия":"Judging by the collection, this is not sacrilege. It is a profession",
"Она не убежала от него. Она вернулась за помощью":"She did not run away from him. She came back for help",
"Признаю: работа хорошая. Это не делает её менее неудобной для владельца мельницы":"I admit it: the workmanship is good. That does not make it any less inconvenient for the mill owner",
"Меня больше интересует не отправитель, а курьер. Сова наверняка знает обратный путь":"I am more interested in the courier than the sender. The owl surely knows the way back",
"Маршрут, которого боится неизвестный отправитель, заслуживает хотя бы того, чтобы пройти его с открытыми глазами":"A route an unknown sender fears deserves at least to be walked with our eyes open",
"Я бы начал переговоры с признания его вклада в раскопки":"I would begin negotiations by acknowledging his contribution to the excavation",
"Если это считается небольшим опозданием, я начинаю понимать, почему с феями нельзя договариваться о часе встречи":"If this counts as a minor delay, I am beginning to understand why you should never arrange a meeting time with fairies",
"Даже если признать сон гостиницей, это худший договор заселения, который я видела":"Even if we accept the dream as an inn, this is the worst lodging agreement I have ever seen",
"Мост через реку я строил. Туннель под рекой тоже. Но обычно сначала река выбирает землю":"I have built a bridge over a river. A tunnel under one too. Usually the river chooses the ground first",
"Она не выглядит чужой. Но, возможно, вернулась не из того времени, из которого ушла":"She does not look like someone else. But perhaps she returned from a different time than the one she left",
"Похоже, впервые долг нельзя уменьшить хорошими переговорами. Только плохим пением":"It seems this is the first debt that cannot be reduced by good negotiation. Only by bad singing",
"Если маленькие фигуры играют без нас, самое невежливое — вмешаться до того, как поймём правила":"If the little pieces are playing without us, the rudest thing would be to interfere before we understand the rules",
"Внутри кто-то ест бутерброд. Очень грозно":"Someone inside is eating a sandwich. Terrifying",
"Это либо самое плохо организованное ограбление, либо самый честный банковский отчёт":"This is either the worst organized robbery or the most honest bank report",
"Если верить этим цифрам, половина второго этажа должна платить за осадные работы":"If these figures are accurate, half the second floor should be paying for siege operations",
"Первое, что я бы посчитал, — сколько осталось зарядов до международного инцидента":"The first thing I would count is how many charges remain before an international incident",
"Он уже подписывает бумаги осмысленнее некоторых чиновников, которых я встречала":"He already signs documents more sensibly than some officials I have met",
"Прук нашёл рынок даже для собственной смерти. Я бы только проверил, что семья получит деньги раньше организатора":"Pruk found a market even for his own death. I would only make sure the family receives the money before the organizer",
"Если они не могут решить, кто спасает его первым, давайте сделаем так, чтобы никто не отпускал последним":"If they cannot decide who saves him first, let us make sure nobody is the last to let go",
"Можете назвать это неисправностью. Но неисправность явно знает мелодию":"You can call it a malfunction. But the malfunction clearly knows the melody",
"Двадцать лет они делили поле. Может, сегодня хватит разделить тряпку":"They divided a battlefield for twenty years. Perhaps today dividing a piece of cloth will be enough",
"Они не боятся нежити. Они будто не хотят, чтобы именно эти мёртвые куда-то ушли":"They are not afraid of the undead. It is as though they do not want these particular dead to leave",
"Механизм исправен. Его представление о том, что является товаром, — нет":"The mechanism works. Its idea of what counts as merchandise does not",
"Он не забыл хозяйку. Только слово, которым она к нему обращалась. С животными бывает и хуже":"He did not forget his owner. Only the word she used for him. Worse things happen with animals",
"Спор легко решить: сначала посчитать, сколько каждый зарабатывает, когда второго рядом нет":"The dispute is easy to solve: first calculate how much each earns when the other is absent",
"Публика пришла. Артисты здесь. Похоже, отсутствует только человек, который считал себя самым нужным":"The audience came. The performers are here. It seems the only missing person is the one who thought himself indispensable",
"Иногда уважение к врагу появляется слишком поздно. Но это всё ещё уважение":"Sometimes respect for an enemy arrives too late. It is still respect",
"Иногда цивилизация держится не на законах, а на наличии мелочи":"Sometimes civilization depends not on laws, but on having exact change",
"Обряд прост, пока цена символическая. Сегодня она вполне настоящая":"The ritual is simple while the price is symbolic. Today the price is quite real",
"Я не уверен, что осадная машина — правильный инструмент для садоводства. Но признаю решимость":"I am not sure a siege engine is the right tool for gardening. I respect the determination",
"Если исполнитель и цель вместе ищут заказчика, работа уже пошла не по плану":"If the assassin and the target are searching for the client together, the job has already gone off plan",
"Вот редкий случай, когда четырнадцать народов уже согласились в главном: торговаться лучше, чем воевать":"Here is a rare case where fourteen peoples already agree on the main point: bargaining is better than fighting",
"Юридически это кошмар. Политически — впервые избиратели могут сравнить одного кандидата с самим собой":"Legally, this is a nightmare. Politically, voters can compare a candidate with himself for the first time",
"Если оба помнят одну присягу, начните с совместной ответственности. Легитимность проверим тем, кто выдержит её дольше":"If both remember the same oath, begin with shared responsibility. Legitimacy can be tested by whoever carries it longer",
"Я знаю каждого, кого вижу. Проблема в том, что счёт всё равно говорит, будто здесь есть ещё кто-то":"I know everyone I can see. The problem is that the count still says someone else is here"
});export{EVENT_EN_V5_11};