const EVENT_EN_V5_01=Object.freeze({
"Здесь можно заставить местность драться за нас":"We can make the terrain fight for us here",
"Лучший путь — тот, который враг заметит слишком поздно":"The best path is the one the enemy notices too late",
"Обряд ещё идёт. Просто его некому закончить":"The rite is still going. There is simply no one left to finish it",
"Говорят все. Решение уже принял один":"Everyone is talking. One person has already made the decision",
"Лев на гербе лишний, воск свежий, а подпись поставлена рукой человека, который никогда не видел баронскую канцелярию":"The lion on the crest is wrong, the wax is fresh, and the signature was written by someone who has never seen the baron's chancery",
"Ворота без гарнизона — просто проход. Пошлина без приказа — просто грабёж с печатью":"Gates without a garrison are just an opening. A toll without an order is just robbery with a seal",
"Я схожу вперёд. Если вернусь быстро — всё плохо. Если медленно — ещё хуже":"I'll scout ahead. If I return quickly, things are bad. If I take my time, they're worse",
"Формула приветствия изменилась всего на одно слово. Похоже, именно его от нас и ждут":"The greeting formula changed by only one word. It seems that is exactly the word they expect from us",
"Раненый зверь не бежит от погони. Он выбирает место для последнего прыжка":"A wounded beast is not fleeing the hunt. It is choosing the place for its final leap",
"Вот здесь вы и попытались нас обмануть":"This is where you tried to deceive us",
"Если это вопрос чести, не будем заставлять их ждать ответа":"If this is a matter of honor, let us not keep them waiting for an answer",
"Не всякая помощь требует красивого приказа":"Not every act of help needs an elegant order",
"Озеро не предсказывает. Оно предлагает. Это разные вещи":"The lake does not predict. It offers. Those are different things",
"Если это должно ударить кого-то первым, пусть ударит меня":"If this has to hit someone first, let it hit me",
"Если цена написана мелко, значит, именно её и нужно читать вслух":"If the price is written in small print, that is exactly what should be read aloud",
"Не трогайте ничего. Особенно то, что выглядит безопасным":"Do not touch anything. Especially anything that looks safe",
"Я дам ему причину смотреть туда ещё внимательнее. Цепи снимайте, когда они отвернутся":"I'll give him a reason to watch that way even more closely. Remove the chains when they turn away",
"Он читает знаки правильно. Только вывод каждый раз выбирает тот, за который ему выгоднее заплатить":"He reads the signs correctly. He simply chooses whichever conclusion earns him the best payment",
"Они хотят идти по нашему следу. Хорошо. Оставим им след, который приведёт совсем не туда":"They want to follow our trail. Good. We'll leave them one that leads somewhere else entirely",
"Под полотном что-то держится за незавершённый обряд. Я могу оборвать эту связь без лишнего шума":"Something beneath the cloth is clinging to an unfinished rite. I can sever that bond without unnecessary noise",
"Если уж мёртвые требуют королевский документ, пусть хотя бы форма будет безупречной":"If the dead insist on a royal document, the form should at least be flawless",
"Здесь просили не силы. Здесь просили свидетеля":"They did not ask for strength here. They asked for a witness",
"Такие вещи опасны не потому, что мёртвые сильны. А потому, что живые забыли правильные слова":"Things like this are dangerous not because the dead are strong, but because the living forgot the proper words",
"Проклятие держится не на костях, а на том, кому позволили назвать их короной. Разорвём именно это":"The curse is bound not to the bones, but to whoever was allowed to call them a crown. That is what we will break",
"Успею перехватить их до поворота. После поворота будет уже бой":"I can intercept them before the bend. After the bend, it becomes a battle",
"Есть путь быстрее. Хорошим он от этого не становится":"There is a faster path. That does not make it a good one",
"Опаснее не то, что блестит. Опаснее то, на чём оно держится":"The dangerous part is not what shines. It is what the shining thing stands on",
"Я знаю, чего они хотят. Осталось решить, сколько они готовы за это отдать":"I know what they want. Now we only need to decide how much they are willing to give for it",
"Они торгуются не за вещь. Они торгуются за право показать, что могут заплатить больше. Это легко испортить":"They are not bidding for the item. They are bidding for the right to prove they can pay more. That is easy to disrupt",
"Шёлк выдержит вес, если не заставлять его держать ещё и страх. Я проверю переправу первым":"The silk will hold the weight if we do not make it carry our fear too. I will test the crossing first",
"Им нужен не победитель. Им нужен кто-то, кого можно будет обвинить после":"They do not need a winner. They need someone to blame afterward",
"Сначала удержим гору. Потом будем спасать людей":"First we keep the mountain standing. Then we save the people",
"Наконец-то условие, в котором никто не прячет мелкий шрифт":"Finally, a contest where nobody hides the fine print",
"Они соревнуются в силе. Значит, никто не будет ждать хитрости":"They are competing in strength. That means nobody will expect cunning",
"Обоз слишком громкий, чтобы замечать засаду вовремя. Я пройду дорогу раньше него и вернусь с ответом":"The caravan is too loud to notice an ambush in time. I'll ride the road ahead of it and return with an answer",
"Это не пароль. Это порядок действий. Ошибёшься в одном знаке — сейф решит, что его уже вскрывают":"This is not a password. It is a sequence of actions. Get one symbol wrong and the vault will decide it is already being broken into",
"Если не торопить железо, оно обычно само рассказывает, что с ним не так":"If you do not rush metal, it usually tells you what is wrong with it",
"Силовой узел не сломан — его заставили работать против самого себя. Сначала снимем нагрузку, потом полезем внутрь":"The power assembly is not broken—it was forced to work against itself. First we remove the load, then we go inside",
"Банда ещё на марше. Если перехватить её до теснины, это будет разговор. После теснины — уже бой":"The gang is still on the move. Catch them before the narrows and it will be a conversation. After the narrows, it becomes a battle",
"Символ построен на трёх именах. Разрушить нужно среднее — остальные тогда рассыплются сами":"The symbol is built on three names. Break the middle one and the others will collapse on their own",
"Желание уже записано против нас. Я перепишу условия так, чтобы продавцу впервые пришлось читать собственный договор":"The wish has already been written against us. I'll rewrite the terms so the seller has to read his own contract for once",
"Она держит не тело. Она держит обещание. Если переписать того, кому оно дано, круг перестанет понимать, кого удерживать":"It does not hold the body. It holds a promise. Change who the promise belongs to, and the circle will no longer know whom to restrain",
"Угли опасны, пока каждый идёт сам по себе. Под щитами мы превратим переход в одну короткую линию":"The embers are dangerous while everyone crosses alone. Under shields, we turn the crossing into one short line",
"Ритм повторяется. Значит, перед нами не чудо — перед нами правило":"The rhythm repeats. That means this is not a miracle—it is a rule",
"Он забрал право толковать условия себе. Значит, мы начнём с того, что заберём это право обратно":"He gave himself the right to interpret the terms. So we begin by taking that right back",
"Печать света не погасла — её разомкнули. Если вернуть последний знак на место, крыло снова будет защищено":"The seal of light did not go out—it was broken open. Restore the final symbol and the wing will be protected again",
"Весы здесь давно наклонены. Я могу заставить суд хотя бы услышать то, что он уже решил не замечать":"The scales here have been tilted for a long time. I can at least make the court hear what it has already decided to ignore",
"Колокол ждёт не силы, а правильной последовательности. Один неверный жест — и он услышит совсем другую молитву":"The bell is waiting not for strength, but for the correct sequence. One wrong gesture and it will hear a very different prayer",
"Если страж хочет поединка за звезду, я приму его правила. Но место и дистанцию выберу сам":"If the guardian wants a duel for the star, I will accept his rules. But I will choose the ground and distance",
"Один голос в хоре повторяет ноты слишком правильно. Найдём его — и поймём, что здесь подменили":"One voice in the choir repeats the notes too perfectly. Find it, and we will understand what was replaced here",
"Хорошая сделка. Особенно для того, кто её придумал":"A good deal. Especially for whoever came up with it",
"Дым закрывает перевал, но не следы под ногами. Я узнаю, кто прошёл здесь до пожара":"The smoke hides the pass, but not the tracks underfoot. I will find out who came through before the fire",
"Выдержим. Вопрос только — сколько раз":"We can take it. The only question is how many times"
});export{EVENT_EN_V5_01};