const EVENT_EN_V4_05 = Object.freeze({
  "Семь минут бессмертия": "Seven Minutes of Immortality",
  "Царр продаёт стеклянные ампулы с надписью «БЕССМЕРТИЕ — 7 МИНУТ». Он честно предупреждает: эффект заканчивается внезапно, продлить нельзя, а использованные семь минут организм «запоминает очень плохо».": "Tsarr sells glass ampoules labeled ‘IMMORTALITY — 7 MINUTES.’ He warns honestly that the effect ends suddenly, cannot be extended, and the body ‘remembers those seven minutes very poorly.’",
  "На столе лежит журнал покупателей. Один прыгнул со скалы и успел пожалеть. Другой съел яд, чтобы доказать спор. Третий просто проспал все семь минут и требует возврата денег.": "A customer ledger lies on the table. One buyer jumped from a cliff and had time to regret it. Another swallowed poison to prove a point. A third simply slept through all seven minutes and is demanding a refund.",
  "Царр предлагает одну ампулу Королю бесплатно — «в рекламных целях».": "Tsarr offers the King one ampoule free of charge—‘for promotional purposes.’",
  "Взять бесплатную ампулу": "Take the free ampoule",
  "Купить ещё две": "Buy two more",
  "Поручить Слону определить настоящую цену эффекта": "Ask the Bishop to determine the true price of the effect",
  "{bishopName} держит ампулу на свету. «Это не бессмертие. Это отсрочка последствий».": "{bishopName} holds the ampoule up to the light. ‘This is not immortality. It is a delay of consequences.’",
  "Испытать ампулу немедленно": "Test the ampoule immediately",
  "Разбить товар как опасную алхимию": "Destroy the merchandise as dangerous alchemy",

  "Демон, который хочет уволиться": "The Demon Who Wants to Quit",
  "Гриск сидит на камне и заполняет заявление об увольнении из легиона Бездны. В графе «причина» он написал: «токсичная рабочая среда». Ниже: «буквально».": "Grisk sits on a stone filling out a resignation form from the Legion of the Abyss. Under ‘reason’ he has written: ‘toxic work environment.’ Beneath that: ‘literally.’",
  "Проблема в том, что демонам нельзя уволиться без подписи внешнего свидетеля, «не находящегося под властью непосредственного руководителя». Гриск просит Короля расписаться.": "The problem is that demons cannot resign without the signature of an outside witness ‘not subject to the authority of the immediate supervisor.’ Grisk asks the King to sign.",
  "Из маленького зеркала на поясе доносится голос начальницы: «НЕ СМЕЙ».": "The supervisor's voice comes from a small mirror on his belt: ‘DON'T YOU DARE.’",
  "Король берёт перо. «Это, пожалуй, первый мятеж, который начинается с формы в трёх экземплярах».": "The King takes the quill. ‘This may be the first mutiny to begin with a form in triplicate.’",
  "Подписать заявление Гриска": "Sign Grisk's resignation",
  "Потребовать плату за королевское свидетельство": "Demand payment for a royal witness",
  "Предложить Гриску просто не возвращаться на работу": "Suggest that Grisk simply not return to work",
  "Отказать и вернуть зеркало начальнице": "Refuse and return the mirror to his supervisor",
  "Разбить зеркало и посмотреть, считается ли это расторжением связи": "Break the mirror and see whether that counts as severing the connection",

  "Ангел с грязными крыльями": "The Angel with Dirty Wings",
  "Ангел Эйрен помогает разбирать пепелище после пожара. Белые крылья покрыты сажей, доспехи сложены в стороне. Жители работают рядом и стараются не смотреть на него.": "The angel Eiren helps clear the ruins after a fire. His white wings are covered in soot and his armor lies to one side. The villagers work nearby and try not to look at him.",
  "Огонь начался во время его боя с демоном. Эйрен победил, но половина деревни сгорела. Небесный приказ велит ему немедленно продолжать преследование остатка вражеского отряда. Он не уходит.": "The fire began during his battle with a demon. Eiren won, but half the village burned. A heavenly order commands him to resume pursuit of the remaining enemy force immediately. He refuses to leave.",
  "«Если приказ требует оставить этих людей в золе, — говорит он, — пусть тот, кто его написал, придёт и повторит мне это здесь».": "‘If the order requires me to leave these people in the ashes,’ he says, ‘let whoever wrote it come here and repeat it to me.’",
  "Король смотрит на обугленные балки. «Победа не всегда выглядит как место, где хочется поднять знамя».": "The King looks at the charred beams. ‘Victory does not always look like a place where you want to raise a banner.’",
  "Помочь восстановлению деревни": "Help rebuild the village",
  "Убедить ангела выполнить приказ, а восстановление оставить людям": "Convince the angel to obey the order and leave the rebuilding to the villagers",
  "Отправить часть отряда по следу демонов вместо Эйрена": "Send part of the roster after the demons in Eiren's place",
  "Предложить Эйрену временно присоединиться к Королю": "Invite Eiren to serve with the King temporarily",

  "Нимб напрокат": "Halo for Hire",
  "Торговец Пел предлагает «подлинные небесные нимбы» по цене хорошего коня. На прилавке лежат двенадцать сияющих колец. Молодой ангел Саэль стоит рядом и требует прекратить торговлю.": "Merchant Pel offers ‘genuine heavenly halos’ for the price of a good horse. Twelve glowing rings lie on his counter. A young angel named Sael stands nearby demanding that the trade stop.",
  "Пел настаивает, что нимбы не украдены. Он их арендует. Саэль утверждает, что нимб вообще не вещь и не может быть предметом аренды.": "Pel insists the halos were not stolen. He rents them. Sael argues that a halo is not an object at all and therefore cannot be rented.",
  "Чтобы доказать обратное, Пел надевает один на голову. Нимб тут же поднимается на метр и тащит торговца за собой.": "To prove otherwise, Pel puts one on his head. The halo immediately rises a meter into the air and drags the merchant with it.",
  "Помочь Саэлю конфисковать нимбы": "Help Sael confiscate the halos",
  "Купить один нимб до конфискации": "Buy one halo before the confiscation",
  "Поручить Ладье заземлить сияющие кольца и безопасно снять их с прилавка": "Ask the Rook to ground the glowing rings and remove them safely from the counter",
  "{rookName} ловит Пела за сапог. «Спор о собственности можно продолжить после того, как собственность перестанет его уносить».": "{rookName} catches Pel by the boot. ‘The ownership dispute can continue after the property stops carrying him away.’",
  "Поддержать Пела: если ангелы сдают нимбы добровольно, это их дело": "Support Pel: if angels rent out their halos willingly, that is their business",
  "Уйти, пока торговца не унесло окончательно": "Leave before the merchant is carried away for good",

  "Колокол, который звонит только лжецам": "The Bell That Rings Only for Liars",
  "В небесной часовне висит маленький серебряный колокол. По легенде, он звонит, когда рядом произносят ложь. Сегодня утром он звонил без остановки.": "A small silver bell hangs in a heavenly chapel. Legend says it rings whenever a lie is spoken nearby. This morning it rang without stopping.",
  "В часовне всего трое паломников и хранительница Офира. Каждый утверждает, что говорит правду. Колокол молчит, пока они повторяют свои показания Королю. Но стоит Королю спросить, кто первым вошёл в часовню, — колокол начинает бешено звенеть, хотя никто ещё не ответил.": "Only three pilgrims and the keeper Ophira are in the chapel. Each claims to be telling the truth. The bell remains silent while they repeat their statements to the King. But the moment the King asks who entered the chapel first, the bell begins ringing furiously even though no one has answered yet.",
  "Офира бледнеет. «Он реагирует не на слова».": "Ophira turns pale. ‘It is not reacting to words.’",
  "Допросить паломников по очереди": "Question the pilgrims one at a time",
  "Заставить всех написать ответы, не произнося их": "Have everyone write their answers without speaking them",
  "Поручить Слону проверить сам ритуал колокола": "Ask the Bishop to examine the bell's ritual itself",
  "{bishopName} смотрит вверх. «Он звонит на намерение солгать. Кто-то уже решил, что скажет».": "{bishopName} looks up. ‘It rings at the intention to lie. Someone has already decided what they will say.’",
  "Снять колокол и забрать как артефакт": "Take down the bell and keep it as an artifact",

  "Крыло в залоге": "A Wing in Pawn",
  "У дорожного ломбарда сидит ангел Нира с одним крылом. Второе находится внутри за железной решёткой.": "The angel Nira sits outside a roadside pawnshop with one wing. The other is inside behind an iron grille.",
  "Она заложила перья, чтобы купить лекарства для отряда паломников. Ростовщик Вельт принял «крыло целиком как неделимый предмет обеспечения». По договору срок истёк вчера.": "She pawned feathers to buy medicine for a group of pilgrims. Moneylender Velt accepted ‘the entire wing as an indivisible item of collateral.’ According to the contract, the term expired yesterday.",
  "Нира может летать и с одним крылом — недолго и очень плохо. Вельт уже нашёл покупателя на второе.": "Nira can fly with one wing—briefly, and very badly. Velt has already found a buyer for the other.",
  "Выкупить крыло": "Redeem the wing",
  "Запугать Вельта королевским расследованием": "Intimidate Velt with a royal investigation",
  "Поручить Ферзю доказать недействительность договора": "Ask the Queen to prove the contract invalid",
  "{queenName} читает договор. «Он законен только потому, что никто не предполагал, что кто-то попробует такое написать».": "{queenName} reads the contract. ‘It is legal only because nobody imagined someone would try to write such a thing.’",
  "Предложить Нире службу в обмен на выплату долга": "Offer Nira service in exchange for paying her debt",
  "Не вмешиваться в законную сделку": "Do not interfere in a lawful transaction",

  "Паломник, который идёт назад": "The Pilgrim Who Walks Backward",
  "Амарон идёт по дороге спиной вперёд. Он делает это уже сорок дней, судя по истёртым задникам сапог. В руках у него посох с колокольчиком, который предупреждает о камнях.": "Amaron walks along the road backward. Judging by the worn backs of his boots, he has been doing it for forty days. He carries a staff with a little bell that warns him about stones.",
  "На вопрос Короля ангел отвечает: «Я слишком долго шёл только к цели и перестал видеть, откуда пришёл. Теперь исправляю».": "When the King asks why, the angel answers: ‘For too long I walked only toward the destination and stopped seeing where I had come from. Now I am correcting that.’",
  "Он предлагает отряду пройти вместе с ним хотя бы одну милю, не поворачиваясь лицом к дороге.": "He invites the roster to walk at least one mile with him without turning to face the road.",
  "Король оглядывается на пройденный путь. «Не самый удобный способ вспомнить прошлое. Но, возможно, именно поэтому он работает».": "The King looks back at the road already traveled. ‘Not the most convenient way to remember the past. But perhaps that is precisely why it works.’",
  "Пройти милю вместе с Амароном": "Walk a mile with Amaron",
  "Попросить у него благословение вместо прогулки": "Ask him for a blessing instead of the walk",
  "Предложить проводить его безопасно обычным способом": "Offer to escort him safely in the usual way",
  "Попытаться убедить Амарона, что урок уже усвоен": "Try to convince Amaron that the lesson has already been learned",
  "Продолжить свой маршрут": "Continue on your own route",

  "Суд над чудом": "The Trial of a Miracle",
  "Ангельский суд рассматривает необычное дело. Бен, приговорённый к смерти за убийство, был смертельно ранен при побеге. Ангел-лекарь спас его, не зная личности пациента. Теперь семья погибшего требует исполнить старый приговор. Сам лекарь умер месяц назад.": "An angelic court is hearing an unusual case. Ben, sentenced to death for murder, was mortally wounded while escaping. An angel healer saved him without knowing the patient's identity. Now the victim's family demands that the old sentence be carried out. The healer himself died a month ago.",
  "Судья Сариэль спрашивает Короля как светского правителя: считается ли чудесно спасённая жизнь «новой жизнью» или продолжением прежней ответственности?": "Judge Sariel asks the King as a secular ruler whether a life saved by miracle counts as a ‘new life’ or as a continuation of the old responsibility.",
  "Бен молчит. Он не просит помилования.": "Ben remains silent. He does not ask for mercy.",
  "Подтвердить старый приговор": "Uphold the old sentence",
  "Помиловать Бена при условии службы пострадавшей семье": "Pardon Ben on condition that he serve the victim's family",
  "Поручить Ферзю предложить решение, разделяющее наказание и месть": "Ask the Queen to propose a solution that separates punishment from vengeance",
  "{queenName} говорит тихо: «Если закон зависит от того, насколько хорош был лекарь, это уже не закон».": "{queenName} says quietly, ‘If the law depends on how good the healer was, it is no longer law.’",
  "Предложить Бену службу в опасном походе Короля": "Offer Ben service in the King's dangerous campaign",
  "Отказаться выносить решение чужого суда": "Refuse to rule for another court",

  "Дракон, которому холодно": "The Dragon Who Is Cold",
  "У дороги горит костёр размером с дом. Вокруг него сидит молодой драконорождённый Роар, завернувшийся в три шерстяных плаща. Он стучит зубами.": "A bonfire the size of a house burns beside the road. A young dragonkin named Roar sits beside it wrapped in three woolen cloaks, his teeth chattering.",
  "Мать Хесса в отчаянии. Для её рода холод — позорная редкость. Роар случайно съел голубой кристалл из ледяной пещеры, решив, что это «очень твёрдый сахар».": "His mother Hessa is desperate. In her bloodline, feeling cold is a shameful rarity. Roar accidentally ate a blue crystal from an ice cave because he thought it was ‘very hard sugar.’",
  "Каждый его выдох покрывает траву инеем. Костёр от этого становится только больше: дварфские угли шипят, но не гаснут.": "Every breath he exhales coats the grass in frost. The fire only grows larger: dwarven coals hiss but refuse to go out.",
  "Отдать Роару тёплые припасы и дождаться улучшения": "Give Roar warm provisions and wait for him to recover",
  "Попытаться прогреть его магическим огнём": "Try to warm him with magical fire",
  "Поручить Слону нейтрализовать кристалл через противоположную руну": "Ask the Bishop to neutralize the crystal with an opposing rune",
  "{bishopName} просит Роара выдохнуть на серебряную монету. «Кристалл не охлаждает тело. Он меняет само пламя внутри».": "{bishopName} asks Roar to breathe onto a silver coin. ‘The crystal is not cooling his body. It is changing the flame inside him.’",
  "Предложить Роару остаться таким и заработать на охлаждении погребов": "Suggest that Roar stay this way and earn money cooling cellars",

  "Вес драконьего слова": "The Weight of a Dragon's Word",
  "Посол Кассар обещал купцу Двену защитить караван «до последнего камня на дороге». На третьей миле дорогу смыло рекой. Двен считает, что договор закончился: камней больше нет. Кассар считает, что теперь обязан сопровождать караван вечно, потому что условие прекращения физически уничтожено.": "Ambassador Kassar promised merchant Dven to protect his caravan ‘until the last stone on the road.’ Three miles later, the road was washed away by a river. Dven believes the agreement is over because there are no stones left. Kassar believes he is now obliged to escort the caravan forever because the termination condition has been physically destroyed.",
  "Оба устали от спора, но драконорождённый не может просто отказаться от произнесённого слова. Для его рода такая клятва оставляет видимый знак на чешуе.": "Both are tired of the argument, but the dragonkin cannot simply abandon a spoken promise. In his bloodline, such an oath leaves a visible mark on the scales.",
  "На груди Кассара уже появился тёмный рубец.": "A dark scar has already appeared on Kassar's chest.",
  "Приказать Двену формально освободить Кассара от обязательства": "Order Dven to formally release Kassar from the obligation",
  "Найти камень со старой дороги и объявить его “последним”": "Find a stone from the old road and declare it the ‘last’ one",
  "Поручить Ферзю составить новую формулу, которая юридически и ритуально завершит старую": "Ask the Queen to draft a new formula that ends the old oath both legally and ritually",
  "{queenName} изучает место старой дороги. «Фраза была метафорой. Проблема в том, что клятва услышала её буквально».": "{queenName} studies the site of the old road. ‘The phrase was a metaphor. The problem is that the oath heard it literally.’",
  "Потребовать, чтобы Кассар исполнил слово буквально до конца жизни": "Demand that Kassar fulfill his word literally for the rest of his life"
});

export { EVENT_EN_V4_05 };
