const EVENT_EN_V5_06=Object.freeze({
"Пароль, возможно, проще. Но замок тоже вполне убеждаем":"The password may be simpler. But the lock looks quite persuadable too",
"Они не поют. Они заставляют память петь за них":"They are not singing. They are making memory sing for them",
"В строю держался бы лучше половины живых":"He would hold formation better than half the living",
"В комнате кто-то есть. Вопрос только — с какой стороны":"Someone is in the room. The only question is which side",
"Редкий случай, когда клевета сделана из лучших побуждений":"A rare case where slander was made with the best intentions",
"Он не капризничает. Ремень натирает панцирь":"He is not being difficult. The strap is chafing his shell",
"Контракт требует результата, но нигде не сказано, что заказчик должен пережить разъяснение условий":"The contract requires a result, but nowhere does it say the client must survive the explanation of the terms",
"Восьмой угол появляется, когда кто-то решает, что уже понял комнату":"The eighth corner appears when someone decides they have already understood the room",
"Я знаю историю, в которой камень победил короля. Правда, камень потом пожалел":"I know a story where a stone defeated a king. Admittedly, the stone regretted it afterward",
"Пауки здесь ведут себя честнее переговорщиков":"The spiders here are behaving more honestly than the negotiators",
"Если это поможет: первым по торту прошёл вообще третий человек":"If it helps, the first person to walk across the cake was actually a third party",
"Продолжайте рассуждать — и скоро ответ будет: столько, сколько вся гора":"Keep reasoning like this and soon the answer will be: as many as the whole mountain",
"Кольца тяжёлые. Вор унёс бороду, но оставил следы масла от украшений":"The rings are heavy. The thief took the beard, but left oil traces from the ornaments",
"Её толкнули руками. Достаточно недавно, чтобы металл ещё дрожал":"She was pushed by hand. Recently enough that the metal is still vibrating",
"После обвала живые кричат не всегда. Иногда главное — заметить, где камень лежит слишком ровно":"After a collapse, the living do not always shout. Sometimes the important thing is noticing where the stone lies too neatly",
"С пивом всё в порядке. Возможно, дело не в том, кто должен выпить, а кто должен налить":"There is nothing wrong with the beer. Perhaps the issue is not who should drink, but who should pour",
"Ствол стоит правильно. Камора — нет. Кто-то собрал пушку зеркально":"The barrel is mounted correctly. The chamber is not. Someone assembled the cannon as a mirror image",
"Если никто не доверяет правилам фонда, проблема уже не в деньгах":"If nobody trusts the fund's rules, the problem is no longer the money",
"Продавец, который заранее перечислил последствия, заслуживает хотя бы одного покупателя, умеющего читать условия":"A seller who listed the consequences in advance deserves at least one buyer capable of reading the terms",
"Если открыть дверь, они сначала съедят ужин. Потом дверь":"If we open the door, they will eat dinner first. Then the door",
"Красный цвет настоящий. Конец света — пока нет":"The red color is real. The end of the world is not—yet",
"Без договора у него есть только очень уверенный тон":"Without a contract, all he has is a very confident tone",
"Если это не сработает, хотя бы согреется кузнец":"If this does not work, at least the smith will get warm",
"Портал держится на самой раме. Если снять петли, возможно, ад останется без входа":"The portal is anchored to the frame itself. Remove the hinges and perhaps hell will be left without an entrance",
"Хорошие ворота отличаются от плохих не тем, куда ведут. А тем, умеют ли закрываться вовремя":"Good gates differ from bad ones not by where they lead, but by whether they know how to close in time",
"Помощь не становится хуже оттого, что оказалась не первой":"Help does not become worse because it was not the first help offered",
"Если они умеют считать каждое перо, удивительно, что война вообще помещается в расписание":"If they can count every feather, it is remarkable that war fits into the schedule at all",
"Облако не знает ваших границ. Возможно, на этот раз границам придётся пережить это унижение":"The cloud does not know your borders. Perhaps this time the borders will have to survive the humiliation",
"Пожалуй, это самый убедительный аргумент против неподвижных карт, который я сегодня видел":"That may be the strongest argument against static maps I have seen all day",
"Он не уснул. Он слушает то, что поднимается снизу":"He did not fall asleep. He is listening to whatever is rising from below",
"Дварф ругается, но работа хорошая. Очень хорошая":"The dwarf is cursing, but the workmanship is good. Very good",
"Свет слишком яркий именно там, где должен давать тень":"The light is brightest exactly where it should be casting a shadow",
"А ты кому хочешь отдать награду?» «Мне":"And who do you want to give the reward to?” “Me",
"Человек, который пишет себе “не ходи туда”, обычно уже знает почему":"A person who writes “do not go there” to themselves usually already knows why",
"Это имя. Но не отца":"It is a name. But not the father's",
"Сколько тебе платят?":"How much are they paying you?",
"Иногда традиции полезно защищать от погоды":"Sometimes tradition needs protection from the weather",
"Сражаться в этом нельзя. Но пройти сто шагов — можно, если правильно распределить вес":"You cannot fight in this. But you can walk a hundred paces if the weight is distributed properly",
"Это не источник. Что-то живое двигается под водой":"This is not a spring. Something alive is moving under the water",
"Слово “естественной” здесь есть. Это делает ножницы особенно неуместными":"The word “natural” is right there. That makes the scissors especially inappropriate",
"С пехотой проще. Пехота хотя бы понимает приказ “не жуй это”":"Infantry are easier. Infantry at least understand the order “do not chew that”",
"Если пост перенести вместе со знаком, формально он его не покинет":"If we move the post together with its marker, technically he will never leave it",
"Не спрашивайте, как его зовут. Иногда имя — это приглашение":"Do not ask its name. Sometimes a name is an invitation",
"Никогда ещё беспристрастность не требовала такого самоконтроля":"Impartiality has never required this much self-control",
"Первый голос — память. Второй — нет":"The first voice is memory. The second is not"
});export{EVENT_EN_V5_06};