const EVENT_EN_V4C_04 = Object.freeze({
'Фея поселилась в дварфском автомате':'A Fae Moved into a Dwarven Automaton',
'Автоматон Б-12 говорит голосом феи и отказывается идти на стройку. Механик Орд уверен, что это поломка. Фея Мим высовывается из вентиляционной решётки и заявляет, что это «совместное владение телом».':'Automaton B-12 speaks in a fae voice and refuses to report to the construction site. Mechanic Ord is certain it is a malfunction. Mim the fae pokes her head out through a ventilation grille and declares this is “joint ownership of the body.”',
'Она поселилась внутри во время дождя. За неделю научилась управлять пальцами, потом ногами, а вчера — бухгалтерским модулем. Б-12 при этом не возражает. Его обычный голос время от времени добавляет: «МНЕ НРАВИТСЯ МУЗЫКА».':'She moved inside during a rainstorm. In a week she learned to control the fingers, then the legs, and yesterday the accounting module. B-12 does not object. Its normal voice occasionally adds: “I LIKE MUSIC.”',
'Орд хватается за голову: «Он был идеальной машиной!»':'Ord clutches his head. “It was a perfect machine!”',
'Выселить Мим из автомата':'Evict Mim from the automaton',
'Признать соглашение Мим и Б-12':'Recognize the agreement between Mim and B-12',
'Поручить Ладье установить отдельный модуль управления, чтобы оба могли делить тело безопасно':'Ask the Rook to install a separate control module so both can safely share the body',
'{rookName} слушает двигатель. «Механически он работает лучше, чем раньше. Проблема у мастера не техническая».':'{rookName} listens to the engine. “Mechanically, it works better than before. The master’s problem is not technical.”',
'Купить модернизированного Б-12':'Buy the upgraded B-12',

'Рынок потерянных вещей':'The Market of Lost Things',
'На ночном рынке не продают обычные товары. Здесь лежат вещи, которые люди потеряли и давно перестали искать: детская перчатка, половина медальона, письмо без адресата, тупой нож, деревянная фигурка коня.':'The night market sells no ordinary goods. Its stalls hold things people lost and stopped searching for long ago: a child’s glove, half a medallion, an undelivered letter, a blunt knife, a wooden horse figurine.',
'Торговцы утверждают, что платят не за предмет, а за право окончательно отказаться от поисков. Если хозяин всё ещё надеется найти вещь, она не появляется на прилавке.':'The merchants claim they pay not for the object, but for the right to give up the search forever. If the owner still hopes to find something, it never appears on a stall.',
'На одном столе Король замечает предмет, который узнаёт один из героев отряда.':'On one table, the King notices an object recognized by one of the roster’s heroes.',
'Выкупить знакомый предмет для героя':'Buy back the familiar object for the hero',
'Продать рынку собственную ненужную реликвию':'Sell the market one of your unwanted relics',
'Поручить Пешке расспросить торговцев, откуда именно пришла вещь':'Ask the Pawn to question the merchants about where the object came from',
'{pawnName} долго смотрит на знакомую вещь. «Я думал, что потерял её. Похоже, в какой-то момент я просто перестал искать».':'{pawnName} stares at the familiar object for a long time. “I thought I had lost it. It seems that at some point I simply stopped looking.”',
'Искать дорогие вещи без эмоциональной ценности':'Look for valuable objects with no emotional value',
'Уйти, ничего не покупая':'Leave without buying anything',

'Мост просит назвать пароль':'The Bridge Asks for a Password',
'Каменный мост не пускает никого. При приближении он гулко спрашивает: «Пароль?»':'The stone bridge allows no one across. Whenever someone approaches, it booms: “Password?”',
'Никто не знает пароль. Караван стоит здесь второй день. Уже пробовали имена строителей, названия королей, молитвы, ругательства и слово «пароль». Мост на всё отвечает: «Неверно».':'Nobody knows the password. A caravan has been waiting for two days. They have tried the builders’ names, names of kings, prayers, curses, and the word “password.” The bridge answers every attempt with: “Incorrect.”',
'На нижней стороне арки вырезана почти стёртая надпись. Видно только: `...скажи как другу...`':'A nearly erased inscription is carved beneath the arch. Only one fragment remains legible: `...speak as to a friend...`',
'Сказать мосту “пожалуйста”':'Say “please” to the bridge',
'Попытаться перебрать старые имена и даты':'Try old names and dates',
'Поручить Слону восстановить полную надпись':'Ask the Bishop to reconstruct the full inscription',
'{bishopName} читает остатки надписи. «Возможно, это вообще не пароль. Возможно, он ждёт обращения».':'{bishopName} reads the remaining inscription. “Perhaps it is not a password at all. Perhaps it is waiting to be addressed.”',
'Переправиться вброд':'Ford the river',
'Разрушить часть моста':'Destroy part of the bridge',

'Король из будущего':'The King from the Future',
'У костра сидит старик в изношенной короне. Лицо незнакомое. Манеры — нет. Он знает личные привычки Короля, имена героев отряда и детали событий, которых посторонний знать не может.':'An old man in a worn crown sits by the fire. His face is unfamiliar. His mannerisms are not. He knows the King’s personal habits, the names of the roster’s heroes, and details no outsider could know.',
'Старик утверждает, что он — Король через тридцать лет, вернувшийся на одну ночь. Он не просит золота и не предупреждает о великой катастрофе. Только говорит: «Завтра на развилке не бери левую дорогу».':'The old man claims he is the King thirty years from now, returned for a single night. He asks for no gold and warns of no great catastrophe. He only says: “Tomorrow at the fork, do not take the left road.”',
'На вопрос почему отвечает: «Если скажу — ты всё равно выберешь левую, чтобы доказать, что свободен».':'Asked why, he replies: “If I tell you, you will choose left anyway just to prove you are free.”',
'Король долго смотрит на старика. «Если ты действительно я, то должен понимать, насколько это раздражающий способ давать совет».':'The King stares at the old man for a long time. “If you really are me, then you should understand how irritating a way this is to give advice.”',
'Поверить и запомнить предупреждение':'Believe him and remember the warning',
'Потребовать доказательство, известное только Королю':'Demand proof known only to the King',
'Попытаться задержать старика до утра':'Try to detain the old man until morning',
'Спросить о будущем одного из героев, а не Короля':'Ask about the future of one of the heroes rather than the King',
'Не верить ни слову':'Believe none of it',

'Трактир на один вечер':'The Tavern for One Evening',
'На пустой дороге вечером появляется трактир, которого не было на карте. Внутри тепло. За одним столом мирно играют в карты орк и ангел, у окна спит тёмная эльфийка, гоблин режет хлеб ровными ломтями и никого не обманывает.':'At dusk, a tavern that appears on no map stands beside the empty road. Inside it is warm. An orc and an angel peacefully play cards at one table, a dark elf sleeps by the window, and a goblin slices bread evenly without cheating anyone.',
'Трактирщица говорит только одно правило: «До рассвета здесь никто никому не враг».':'The innkeeper gives only one rule: “Until dawn, nobody here is anybody’s enemy.”',
'Оружие само остаётся у входа. Даже если попытаться взять меч, рукоять кажется слишком тяжёлой. Утром трактир исчезнет.':'Weapons remain at the entrance of their own accord. Even if someone tries to take a sword, its hilt becomes too heavy to lift. In the morning, the tavern will vanish.',
'Король оглядывает зал. «Жаль, что миру иногда нужна магия, чтобы люди просто поужинали за одним столом».':'The King looks around the room. “A pity the world sometimes needs magic just to let people share a dinner table.”',
'Остаться на ночь':'Stay the night',
'Сыграть с гостями в карты':'Play cards with the guests',
'Расспросить гостей о дорогах и опасностях':'Ask the guests about roads and dangers',
'Попытаться нарушить правило и вынести оружие внутрь':'Try to break the rule and carry a weapon inside',
'Не входить':'Do not enter',

'Статуя меняет позу, когда никто не смотрит':'The Statue Moves When Nobody Is Looking',
'Археолог Вена просит отряд посмотреть на статую. Буквально. Она стоит у раскопа уже двое суток, потому что каждый раз, когда все отворачиваются, каменная фигура становится ближе к лагерю.':'Archaeologist Vena asks the roster to watch a statue. Literally. She has stood beside the dig for two days because every time everyone looks away, the stone figure moves closer to camp.',
'Пока хотя бы один человек смотрит на неё, статуя неподвижна. Моргать можно. Вена проверила.':'As long as at least one person watches it, the statue remains still. Blinking is safe. Vena tested it.',
'Сейчас до палатки с припасами осталось двенадцать шагов. Вена хочет узнать, что произойдёт, если позволить статуе дойти до цели. Остальные археологи категорически не хотят быть частью исследования.':'It is now twelve paces from the supply tent. Vena wants to know what will happen if the statue is allowed to reach its destination. The other archaeologists emphatically do not want to participate in the experiment.',
'Держать постоянное наблюдение до рассвета':'Maintain constant watch until dawn',
'Позволить статуе дойти до палатки':'Let the statue reach the tent',
'Поручить Ладье построить вокруг неё непрозрачный каменный короб':'Ask the Rook to build an opaque stone box around it',
'{rookName} смотрит на землю вокруг статуи. «Она не оставляет следов. Значит, двигается не по земле. Можно закрыть ей обзор на цель, а не держать взгляд вечно».':'{rookName} studies the ground around the statue. “It leaves no tracks. So it is not moving across the ground. We can block its view of the target instead of watching forever.”',
'Разбить статую':'Smash the statue',
'Покинуть раскоп':'Leave the excavation',

'Последний свободный стул':'The Last Empty Chair',
'В заброшенном зале за длинным столом сидят двенадцать незнакомцев. Перед каждым тарелка, бокал и карточка с именем. Тринадцатый стул пуст. На его карточке написано имя Короля.':'Twelve strangers sit at a long table in an abandoned hall. Before each is a plate, a glass, and a name card. The thirteenth chair is empty. Its card bears the King’s name.',
'Никто из сидящих не знает, как оказался здесь. Дверь за ними исчезла. На стене надпись: «Ужин закончится, когда каждый скажет, зачем пришёл».':'None of them knows how they arrived. The door behind them has vanished. An inscription on the wall reads: “Dinner ends when everyone says why they came.”',
'Один гоблин говорит, что шёл грабить дом. Ангел — что искал пропавшего ребёнка. Нежить — что просто заблудилась. Когда очередь доходит до пустого стула, все смотрят на Короля.':'One goblin says he was going to rob a house. An angel says she was searching for a missing child. An undead traveler says he simply got lost. When the turn reaches the empty chair, everyone looks at the King.',
'Король остаётся стоять. «Самое неприятное в магических испытаниях — их уверенность, что вопрос задан правильно».':'The King remains standing. “The most unpleasant thing about magical trials is their certainty that the question was asked correctly.”',
'Сесть и честно назвать цель путешествия':'Sit down and honestly state the purpose of the journey',
'Солгать о цели':'Lie about the purpose',
'Попросить каждого уточнить, что именно он считает “зачем пришёл”':'Ask everyone to clarify what exactly they mean by “why they came”',
'Отказаться садиться и искать выход силой':'Refuse to sit and force a way out',
'Попросить одного из героев занять стул вместо Короля':'Ask one of the heroes to take the chair instead of the King',

'Дорога закончилась':'The Road Ends',
'К вечеру тракт действительно заканчивается. Не обрывается у пропасти и не уходит в лес — просто прекращается ровной линией. Дальше лежит нетронутая трава, будто по ней никогда никто не ходил.':'By evening, the road truly ends. It does not break off at a cliff or disappear into a forest — it simply stops in a perfectly straight line. Untouched grass lies beyond it, as though nobody has ever walked there.',
'На последнем дорожном камне сидит старик с молотком. Он представляется мастером дорог и говорит, что следующий участок ещё не построен.':'An old man with a hammer sits on the final roadstone. He introduces himself as a roadmaster and says the next section has not been built yet.',
'«Но на карте он есть», — замечает кто-то из отряда.':'“But it is on the map,” someone in the roster points out.',
'Старик пожимает плечами. «Карты всегда спешат».':'The old man shrugs. “Maps are always in a hurry.”',
'Рядом лежат четыре каменные плиты. На каждой вырезано направление: к городу, к лесу, к перевалу и «туда, куда вы на самом деле собирались».':'Four stone slabs lie nearby. Each bears a direction: toward the city, toward the forest, toward the pass, and “where you were actually going.”',
'Король смотрит на траву за последним камнем. «Хорошо. Значит, хотя бы один раз дорога не делает вид, что знает за нас, куда идти».':'The King looks at the grass beyond the final stone. “Good. At least once, the road is not pretending to know where we should go.”',
'Заплатить мастеру и выбрать плиту “к городу”':'Pay the roadmaster and choose the “to the city” slab',
'Выбрать плиту “туда, куда вы на самом деле собирались”':'Choose the slab marked “where you were actually going”',
'Поручить Коню проложить путь без помощи мастера':'Ask the Knight to find a route without the roadmaster’s help',
'{knightName} уже осматривает почву впереди. «Если дороги нет, это ещё не значит, что нет пути».':'{knightName} is already studying the ground ahead. “No road does not mean no way.”',
'Спросить старика, кто построил дорогу позади вас':'Ask the old man who built the road behind you',
'Свернуть с тракта прямо в траву':'Leave the road and head straight into the grass',

'Налог на тень':'The Shadow Tax',
'На въезде в город стоит новая будка с вывеской «Сбор за использование городской тени». Сборщик Лотт невозмутимо объясняет: стены отбрасывают тень на дорогу, путники ею пользуются, следовательно, услуга оказана.':'A new booth at the city entrance bears a sign: “Fee for Use of Municipal Shade.” Collector Lott calmly explains that the walls cast shade on the road, travellers use it, and therefore a service has been rendered.',
'За ним писарь Вена устало ставит печати. Очередь спорит уже несколько часов. Один возчик принципиально держит телегу на солнце и почти падает от жары, лишь бы «не дать казне ни медяка».':'Behind him, clerk Vena wearily stamps papers. The queue has been arguing for hours. One driver stubbornly keeps his wagon in the sun and is nearly collapsing from the heat just to “deny the treasury a single copper.”',
'Когда подходит Король, Лотт листает тарифы и заметно бледнеет: для монарха отдельной строки нет.':'When the King approaches, Lott flips through the tariff book and visibly pales: there is no separate entry for a monarch.',
'Заплатить сбор и не задерживаться':'Pay the fee and move on',
'Потребовать вернуть деньги всей очереди':'Demand that everyone in the queue be refunded',
'Поручить Ферзю разобрать постановление по пунктам':'Ask the Queen to examine the ordinance clause by clause',
'{queenName} забирает книгу тарифов. «Если это налог, у него должна быть правовая основа. Если услуга — право отказаться».':'{queenName} takes the tariff book. “If this is a tax, it requires legal authority. If it is a service, people have the right to refuse it.”',
'Проехать по солнечной стороне дороги':'Travel along the sunny side of the road',

'Мельник, который украл ветер':'The Miller Who Stole the Wind',
'В долине не шевелится ни один лист. Зато единственная мельница крутится так быстро, что жернова гудят. Трое фермеров обвиняют мельника Хаса в том, что он «запер весь ветер в колесе» и теперь продаёт помол втридорога.':'Not a single leaf moves in the valley, yet the only mill turns so fast its stones hum. Three farmers accuse the miller Has of having “locked all the wind in his wheel” and charging triple for milling.',
'Хас смеётся до тех пор, пока мальчик не запускает воздушного змея. Тот падает камнем — но, оказавшись рядом с мельницей, внезапно взмывает вертикально вверх.':'Has laughs until a boy launches a kite. It drops like a stone — then, beside the mill, suddenly shoots straight upward.',
'Внутри башни слышен гул, похожий на далёкое дыхание.':'Inside the tower is a hum like distant breathing.',
'Заставить Хаса открыть мельницу для всех':'Force Has to open the mill to everyone',
'Купить муку по его цене':'Buy flour at his price',
'Поручить Ладье проверить механизм и основание башни':'Ask the Rook to inspect the mechanism and the tower foundation',
'{rookName} смотрит на фундамент. «Это не мельница создаёт ветер. Она стоит прямо над тем, откуда он выходит».':'{rookName} studies the foundation. “The mill is not creating the wind. It stands directly above where the wind emerges.”',
'Не трогать странную мельницу':'Leave the strange mill alone',

'Человек с чужим портретом':'The Man with Someone Else’s Portrait',
'Художник Рен выбегает на дорогу с незаконченным портретом. На холсте изображён Король — в тех же доспехах, с той же царапиной на ножнах. Рен клянётся, что никогда его не видел.':'Painter Ren runs into the road carrying an unfinished portrait. The canvas shows the King — in the same armor, with the same scratch on the scabbard. Ren swears he has never seen him.',
'Заказчик пришёл ночью, заплатил заранее и велел написать «человека, который завтра проедет мимо». Сам заказчик сидит теперь в углу трактира, накрыв лицо капюшоном.':'The client came at night, paid in advance, and ordered a portrait of “the man who will pass tomorrow.” The client now sits in the corner of the tavern with his face hidden beneath a hood.',
'Когда Король входит внутрь, незнакомец поднимается. Под капюшоном нет лица — только гладкая кожа.':'When the King enters, the stranger rises. Beneath the hood there is no face, only smooth skin.',
'Король долго смотрит сначала на портрет, потом на незнакомца. «Полагаю, сходство будем обсуждать после того, как выясним, кто из нас здесь заказ».':'The King looks first at the portrait, then at the stranger. “I suppose we can discuss the resemblance after we establish which of us is the commission.”',
'Схватить безликого незнакомца':'Seize the faceless stranger',
'Сжечь портрет':'Burn the portrait',
'Заплатить Рену и забрать картину':'Pay Ren and take the painting',
'Уехать немедленно':'Leave immediately',

'Семь одинаковых сержантов':'Seven Identical Sergeants',
'На заставе службу несут семь братьев Брант. Все одинакового роста, с одинаковыми усами и одинаковым шрамом на подбородке. Капитан Села признаётся, что уже месяц не понимает, кто из них кто.':'Seven Brant brothers serve at the checkpoint. All are the same height, wear the same moustache, and have the same scar on the chin. Captain Sela admits she has not known which is which for a month.',
'Проблема стала серьёзной сегодня утром: один из братьев получил приказ охранять мост, другой — сопровождать казну, третий — арестован за драку. Теперь все семеро утверждают, что именно они охраняли мост.':'The problem became serious this morning: one brother was ordered to guard the bridge, another to escort the treasury, and a third was arrested for fighting. Now all seven insist they were the one guarding the bridge.',
'«Я пробовала номера, — шепчет Села. — Они поменялись мундирами».':'“I tried numbers,” Sela whispers. “They swapped uniforms.”',
'Провести перекличку под присягой':'Hold a roll call under oath',
'Заплатить за задержку и ехать дальше':'Pay for the delay and continue',
'Поручить Пешке определить братьев по строевым привычкам':'Ask the Pawn to identify the brothers by their drill habits',
'{pawnName} усмехается. «Пехота различает людей не по лицам. По привычкам».':'{pawnName} grins. “Infantry do not distinguish people by faces. They do it by habits.”',
'Предложить одному из братьев службу в отряде':'Offer one brother a place in the roster',

'Долгий обед мэра':'The Mayor’s Long Lunch',
'Городские ворота закрыты, потому что мэр Ковен «на обеде». Обед начался три дня назад. Секретарь Лида каждые несколько часов выносит новое распоряжение: не тревожить мэра до десерта.':'The city gates are closed because Mayor Coven is “at lunch.” Lunch began three days ago. Every few hours, secretary Lida issues another order not to disturb the mayor before dessert.',
'Через окно ратуши видно накрытый стол и самого Ковена, который неподвижно сидит с ложкой в руке. Еда перед ним давно сгнила. Но когда кто-то пытается войти, он совершенно живым голосом кричит: «Я ещё не закончил!»':'Through the town hall window you can see a laid table and Coven himself sitting motionless with a spoon in hand. The food before him has long since rotted. Yet whenever anyone tries to enter, he shouts in a perfectly living voice: “I HAVE NOT FINISHED!”',
'Горожане спорят, проклят мэр или просто наконец нашёл идеальную должность.':'The townsfolk argue over whether the mayor is cursed or has simply found the perfect public office.',
'Выломать дверь и прекратить обед':'Break down the door and end the lunch',
'Подкупить стражу, чтобы открыла ворота':'Bribe the guards to open the gates',
'Поручить Слону проверить, кто говорит из ратуши':'Ask the Bishop to determine who is speaking from the town hall',
'{bishopName} прислушивается к голосу из ратуши. «Он отвечает на вопросы, которых ему никто не задавал».':'{bishopName} listens to the voice from the town hall. “It is answering questions nobody asked.”',
'Обойти город':'Go around the city',

'Башмачник для великанов':'The Shoemaker for Giants',
'У дороги стоит сапог размером с лодку. Башмачник Пирс бегает вокруг него с молотком и ругается на швы. За холмом терпеливо ждёт владелец — великан, который заплатил половину заказа, а вторую обещал после примерки.':'A boot the size of a boat stands by the road. Shoemaker Piers runs around it with a hammer, cursing the seams. Its owner waits patiently beyond the hill — a giant who paid half in advance and promised the rest after fitting.',
'Пирс боится идти один: прошлый сапог оказался тесен, и великан выразил недовольство так громко, что с крыши слетела черепица. Дочь Ани уверяет, что клиент вовсе не злой, просто «у него голос большой».':'Piers is afraid to go alone: the last boot was too tight, and the giant expressed his displeasure so loudly that roof tiles came loose. Piers’s daughter Ani insists the client is not angry, he simply “has a big voice.”',
'Из-за холма доносится осторожное: «ГОТОВО?»':'A cautious call comes from beyond the hill: “READY?”',
'Сопроводить Пирса на примерку':'Escort Piers to the fitting',
'Купить часть дорожных припасов у мастерской':'Buy some travel supplies from the workshop',
'Поручить Коню отвлечь великана разговором во время примерки':'Ask the Knight to distract the giant with conversation during the fitting',
'{knightName} оглядывает гигантский сапог. «Если он решит бежать за нами в одном таком, преимущество всё равно будет у нас».':'{knightName} looks over the enormous boot. “If he decides to chase us wearing one of these, we still have the advantage.”',
'Не вмешиваться в ремесленные отношения':'Stay out of the craft dispute'
});
export { EVENT_EN_V4C_04 };
