const EVENT_EN_V4_01 = Object.freeze({
  "Коза Его Величества": "His Majesty's Goat",
  "В деревне Белые Камни Короля встречают колокольным звоном и спором, который слышно ещё с моста. На площади стоит белая коза в красной попоне. К её рогам привязан свиток с королевской печатью.": "In the village of White Stones, the King is greeted by ringing bells and an argument loud enough to hear from the bridge. A white goat in a red caparison stands in the square. A scroll bearing the royal seal is tied to her horns.",
  "Староста Мейр объясняет неприятность: прежний сборщик налогов, уходя в запой, оформил Маргариту как «живой символ коронной власти». Теперь каждый раз, когда коза съедает чужую капусту, хозяева требуют компенсацию из казны. За последнюю неделю она успела разорить три огорода и один цветник.": "Elder Meir explains the problem: before disappearing into a drinking binge, the former tax collector registered Margarita as a ‘living symbol of Crown authority.’ Now every time the goat eats someone else's cabbages, the owners demand compensation from the treasury. In the past week she has ruined three vegetable gardens and one flower bed.",
  "«Мы бы просто сняли попону, — говорит староста, — но в бумагах сказано, что оскорбление Маргариты приравнивается к оскорблению трона».": "‘We would simply take off the caparison,’ says the elder, ‘but the papers say that insulting Margarita is equivalent to insulting the throne.’",
  "Король перечитывает документ дважды. «Я впервые узнаю о назначении собственного представителя постфактум».": "The King reads the document twice. ‘This is the first time I have learned about the appointment of my own representative after the fact.’",
  "Выкупить Маргариту у деревни и увезти с собой": "Buy Margarita from the village and take her with you",
  "Заплатить пострадавшим из королевского кошеля": "Pay the victims from the royal purse",
  "Поручить Ферзю отменить указ юридически, не отменяя достоинства козы": "Ask the Queen to revoke the decree legally without revoking the goat's dignity",
  "{queenName} аккуратно забирает свиток. «Дайте мне десять минут и человека, который умеет писать мелко».": "{queenName} carefully takes the scroll. ‘Give me ten minutes and someone who can write very small.’",
  "Объявить, что отныне Маргарита отвечает за собственные долги": "Declare that Margarita is responsible for her own debts from now on",
  "Не вмешиваться": "Do not interfere",

  "Последний пассажир": "The Last Passenger",
  "У сломанной кареты сидит девочка лет десяти и держит на коленях деревянную коробку. Кучер Йорен говорит, что вёз её к родственникам, но ни имени, ни адреса назвать не может. Через несколько минут с востока появляются двое приставов и требуют передать ребёнка им.": "A girl of about ten sits beside a broken carriage with a wooden box on her lap. Coachman Yoren says he was taking her to relatives, but he cannot name either the relatives or their address. A few minutes later two officers arrive from the east and demand that the child be handed over to them.",
  "Оба предъявляют бумаги. Обе бумаги настоящие. Только приказы противоречат друг другу: один предписывает доставить девочку в столицу как свидетеля, второй — вернуть семье под охраной.": "Both present papers. Both sets of papers are genuine. The orders simply contradict each other: one requires the girl to be taken to the capital as a witness, the other orders her returned to her family under guard.",
  "Сама девочка молчит до тех пор, пока Король не спрашивает, что в коробке. «То, из-за чего они оба врут», — отвечает она.": "The girl herself remains silent until the King asks what is in the box. ‘The reason they are both lying,’ she replies.",
  "Передать девочку первому приставу": "Hand the girl over to the first officer",
  "Передать её второму приставу": "Hand her over to the second officer",
  "Поручить Слону восстановить цепочку приказов и выяснить, кто подменил распоряжение": "Ask the Bishop to reconstruct the chain of orders and find out who changed the instruction",
  "{bishopName} изучает даты и подписи. «Оба приказа выпущены одной канцелярией. Второй — через час после первого».": "{bishopName} studies the dates and signatures. ‘Both orders were issued by the same office. The second came one hour after the first.’",
  "Взять девочку под защиту до ближайшего города": "Take the girl under your protection until the next town",
  "Открыть коробку без её разрешения": "Open the box without her permission",

  "Поле, которое не хочет быть проданным": "The Field That Refuses to Be Sold",
  "Землемер Гастон просит королевского суда по вопросу, который формулирует предельно серьёзно: «поле саботирует сделку». Каждый раз, когда он ставит новые межевые столбы, ночью они оказываются на старых местах. Свидетелей нет, следов тоже.": "Surveyor Gaston requests a royal ruling on a matter he states with complete seriousness: ‘the field is sabotaging the sale.’ Every time he places new boundary posts, they are back in their old positions by morning. There are no witnesses and no tracks.",
  "Пока Гастон показывает карту, один из камней у дороги кашляет. Затем глухо произносит: «Рудек пахал меня сорок лет. Я остаюсь у Рудека».": "While Gaston shows the map, one of the roadside stones coughs. Then it says in a dull voice, ‘Rudek ploughed me for forty years. I am staying with Rudek.’",
  "Фермер Рудек снимает шапку. «Я думал, дед перед смертью просто очень странно благословил землю».": "Farmer Rudek removes his cap. ‘I thought Grandfather simply blessed the land in a very strange way before he died.’",
  "Король смотрит на карту, потом на камень. «Мне редко приходится выслушивать обе стороны земельного спора настолько буквально».": "The King looks at the map, then at the stone. ‘I rarely get to hear both sides of a land dispute quite this literally.’",
  "Признать волю старого духа и оставить поле Рудеку": "Recognize the old spirit's will and leave the field to Rudek",
  "Подтвердить законную продажу": "Uphold the lawful sale",
  "Предложить духу новую границу и отдельный участок": "Offer the spirit a new boundary and a separate plot",
  "Приказать выкопать говорящий камень и увезти его как свидетеля": "Order the talking stone dug up and taken away as a witness",
  "Уехать, пока юриспруденция окончательно не вышла из-под контроля": "Leave before jurisprudence gets completely out of hand",

  "Похороните меня завтра": "Bury Me Tomorrow",
  "У придорожной часовни старый наёмник Освальд копает могилу. Для себя. Он не ранен и не выглядит больным. Рядом сидит племянник Тимо, который отказывается помогать.": "Beside a roadside chapel, an old mercenary named Oswald is digging a grave. For himself. He is not wounded and does not look ill. His nephew Timo sits nearby and refuses to help.",
  "Освальд объясняет: двадцать лет назад он поклялся умершему товарищу, что будет похоронен рядом. Завтра отряд бывших сослуживцев уйдёт из этих мест навсегда, и старик решил «не создавать людям неудобств потом».": "Oswald explains that twenty years ago he swore to a dead comrade that he would be buried beside him. Tomorrow a group of former brothers-in-arms will leave these lands forever, so the old man has decided ‘not to inconvenience people later.’",
  "«Я не собираюсь умирать сегодня, — раздражённо добавляет он. — Я просто хочу подготовиться как следует».": "‘I am not planning to die today,’ he adds irritably. ‘I simply want to prepare properly.’",
  "Помочь закончить могилу и разделить ужин": "Help finish the grave and share supper",
  "Предложить Освальду присоединиться к походу вместо ожидания смерти": "Invite Oswald to join the campaign instead of waiting for death",
  "Поручить Пешке поговорить с Тимо без свидетелей": "Ask the Pawn to speak with Timo in private",
  "{pawnName} долго смотрит на аккуратно сложенную землю. «Он не смерти боится. Он боится, что его забудут не там».": "{pawnName} looks at the neatly piled earth for a long time. ‘He is not afraid of death. He is afraid of being forgotten in the wrong place.’",
  "Заплатить священнику за место в настоящем кладбище": "Pay a priest for a place in a proper cemetery",
  "Не вмешиваться в чужую клятву": "Do not interfere with another man's oath",

  "Корчма без дверей": "The Inn Without Doors",
  "Корчма стоит прямо у дороги. Окна светятся, внутри слышны разговоры, пахнет жареным луком. Проблема только одна: у здания нет двери.": "The inn stands right beside the road. Its windows glow, voices can be heard inside, and the air smells of fried onions. There is only one problem: the building has no door.",
  "Трактирщик Гельм машет отряду из окна и кричит, что дверь была ещё утром. Постояльцы уверяют, что никто её не закладывал. На внешней стене нет ни шва, ни следа ремонта. Когда Ладья обходит дом, изнутри кто-то стучит по стене три раза — но все люди внутри стоят на виду.": "Innkeeper Helm waves to the roster through a window and shouts that the door was there this morning. The guests insist nobody bricked it up. The outer wall has neither seam nor sign of repair. When the Rook walks around the building, someone knocks three times from inside the wall—yet every person inside is standing in plain view.",
  "«Если найдёте вход, ужин за мой счёт!» — обещает Гельм. Из стены ему отвечают четвёртым стуком.": "‘If you find the entrance, supper is on me!’ Helm promises. A fourth knock answers him from inside the wall.",
  "Разобрать часть стены вручную": "Take down part of the wall by hand",
  "Искать магическую причину исчезновения двери": "Search for a magical cause of the missing door",
  "Поручить Ладье найти несущую точку и открыть безопасный проход": "Ask the Rook to find a load-bearing point and open a safe passage",
  "{rookName} прикладывает ладонь к кладке. «Стена настоящая. Просто она стоит там, где раньше не стояла».": "{rookName} places a palm against the masonry. ‘The wall is real. It is simply standing where it did not stand before.’",
  "Предложить постояльцам вылезти через окна и оставить дом существу": "Suggest that the guests climb out through the windows and leave the house to the creature",
  "Провести ночь снаружи и посмотреть, появится ли дверь утром": "Spend the night outside and see whether the door returns by morning",

  "Двадцать семь женихов": "Twenty-Seven Suitors",
  "Баронесса Лисса перекрыла дорогу не по военной причине. Она проводит отбор жениха, и двадцать семь претендентов заняли мост, луг и обе придорожные канавы. Секретарь Эд умоляет Короля помочь: состязание длится четвёртый день, а баронесса всё ещё не увидела человека, «способного принять самостоятельное решение».": "Baroness Lissa has blocked the road for reasons that have nothing to do with war. She is selecting a husband, and twenty-seven candidates have occupied the bridge, the meadow, and both roadside ditches. Secretary Ed begs the King to help: the contest has entered its fourth day, and the baroness still has not seen a man ‘capable of making an independent decision.’",
  "В этот момент один из женихов подходит к Королю и спрашивает, стоит ли ему подарить Лиссе белого коня или серого. За ним выстраивается очередь из остальных.": "At that moment one of the suitors approaches the King and asks whether he should give Lissa a white horse or a grey one. The others form a queue behind him.",
  "Лисса наблюдает за происходящим с балкона и совершенно не скрывает разочарования.": "Lissa watches from the balcony and makes no attempt to hide her disappointment.",
  "Устроить для женихов турнир": "Hold a tournament for the suitors",
  "Посоветовать баронессе выбрать никого": "Advise the baroness to choose no one",
  "Поручить Ферзю провести одно испытание, после которого половина уйдёт сама": "Ask the Queen to devise one test that will make half of them leave on their own",
  "{queenName} смотрит на очередь. «Кажется, испытание уже идёт. Они просто об этом не знают».": "{queenName} looks at the queue. ‘It seems the test is already under way. They simply do not know it yet.’",
  "Предложить должность в отряде самому толковому претенденту": "Offer a place in the roster to the most sensible candidate",
  "Объехать мост через брод": "Bypass the bridge through the ford",

  "Письмо, которое читает получателя": "The Letter That Reads Its Recipient",
  "В маленьком лесном павильоне эльфийская хранительница Ильве хранит одно письмо уже сто девяносто лет. На конверте нет имени. Каждый, кто берёт его в руки, видит другое обращение.": "In a small woodland pavilion, the elven keeper Ilve has guarded one letter for one hundred and ninety years. There is no name on the envelope. Everyone who takes it in hand sees a different form of address.",
  "Король видит собственный титул. Слон — имя человека, которого давно нет. Один из эльфов Ильве утверждает, что видит слово «Предатель» и потому не прикасается к письму много десятилетий.": "The King sees his own title. The Bishop sees the name of someone long dead. One of Ilve's elves claims to see the word ‘Traitor’ and has therefore refused to touch the letter for decades.",
  "Печать цела. Но бумага изнутри тёплая, как кожа живого человека.": "The seal is intact. But the paper is warm from within, like living skin.",
  "Открыть письмо самому Королю": "Have the King open the letter",
  "Сжечь письмо, не читая": "Burn the letter without reading it",
  "Поручить Слону обезвредить чары, не вскрывая конверт": "Ask the Bishop to neutralize the spell without opening the envelope",
  "{bishopName} не тянется к печати. «Оно не знает, кто мы. Оно ищет, чем нас можно заставить открыть его».": "{bishopName} does not reach for the seal. ‘It does not know who we are. It is searching for something that will make us open it.’",
  "Оставить письмо там, где оно лежало два века": "Leave the letter where it has rested for two centuries",

  "Олень на должности судьи": "The Deer Serving as Judge",
  "На лесной развилке идёт суд. Между двумя спорящими эльфами стоит огромный белый олень. Перед ним лежат две дощечки с рунами «прав» и «неправ».": "A trial is taking place at a forest fork. An enormous white deer stands between two arguing elves. Before it lie two tablets bearing the runes ‘right’ and ‘wrong.’",
  "Торговец древесиной обвиняет лесничих в незаконной конфискации телеги. Лесничие обвиняют его в рубке живых деревьев. Решение должен вынести Аэр — священный олень, который традиционно выбирает одну из дощечек.": "A timber merchant accuses the foresters of unlawfully confiscating his cart. The foresters accuse him of felling living trees. The verdict must be delivered by Aer, a sacred deer who traditionally chooses one of the tablets.",
  "Проблема в том, что олень третий час ест обе дощечки по очереди.": "The problem is that the deer has spent the last three hours eating both tablets in turn.",
  "Король наблюдает, как исчезает последний кусок слова «прав». «Неожиданно радикальная судебная реформа».": "The King watches the last piece of the word ‘right’ disappear. ‘An unexpectedly radical judicial reform.’",
  "Предложить обычное расследование вместо гадания": "Propose a normal investigation instead of divination",
  "Подкупить оленя яблоками, чтобы он подошёл к нужной стороне": "Bribe the deer with apples so it approaches the desired side",
  "Проверить древесину на следы живой магии": "Check the timber for traces of living magic",
  "Признать, что олень воздержался, и предложить мировое соглашение": "Declare that the deer abstained and propose a settlement",
  "Не вмешиваться в эльфийское правосудие": "Do not interfere with elven justice",

  "Песня для дерева, которое всё слышало": "A Song for the Tree That Heard Everything",
  "У огромного бука сидит эльфийка Маэрин и пытается вспомнить конец песни. Дерево посадила её мать. Мать погибла давно, песня осталась незаконченной, а бук каждую весну повторяет мелодию ветвями — до той самой оборванной строки.": "The elf Maerin sits beneath an enormous beech tree, trying to remember the end of a song. Her mother planted the tree. Her mother died long ago, the song remained unfinished, and every spring the beech repeats the melody with its branches—right up to the line where it breaks off.",
  "Маэрин просит отряд задержаться до заката. Она уверена: если найти верные слова, дерево отдаст то, что хранит в дупле с её детства. Но попыток было много, и каждая неверная версия заставляет корни сжиматься вокруг сундука сильнее.": "Maerin asks the roster to stay until sunset. She is certain that if the right words are found, the tree will release what it has kept in a hollow since her childhood. But there have been many attempts, and every wrong version makes the roots tighten harder around the chest.",
  "Помочь Маэрин подобрать окончание песни на слух": "Help Maerin find the ending of the song by ear",
  "Срубить часть корней и достать сундук силой": "Cut through some of the roots and take the chest by force",
  "Поручить Слону восстановить песню по памяти дерева": "Ask the Bishop to reconstruct the song from the tree's memory",
  "{bishopName} слушает не певицу, а шелест кроны. «Дерево помнит ритм. Слова можно восстановить по паузам».": "{bishopName} listens not to the singer but to the rustling canopy. ‘The tree remembers the rhythm. The words can be reconstructed from the pauses.’",
  "Предложить Маэрин оставить песню незаконченной": "Suggest that Maerin leave the song unfinished",
  "Продолжить путь": "Continue the journey",

  "Тропа, которая ревнует": "The Jealous Path",
  "Проводник Эрен предупреждает: эту часть леса нельзя проходить двумя дорогами подряд. «Тропа обижается».": "Guide Eren warns that you must not cross this part of the forest by two different roads in succession. ‘The path gets offended.’",
  "Он говорит это без улыбки. Вчера караван свернул на удобный объезд, а сегодня старый путь переместился на полмили и вывел прямо в болото. Пока Эрен объясняет правила, тропа под ногами чуть заметно изгибается, уводя Короля от нового указателя.": "He says it without a smile. Yesterday a caravan took a convenient detour, and today the old path shifted half a mile and led straight into a swamp. As Eren explains the rules, the trail beneath your feet bends almost imperceptibly, drawing the King away from the new signpost.",
  "«Ей нравится, когда выбирают её», — шепчет проводник. — «И она очень плохо переносит сравнения».": "‘It likes being chosen,’ the guide whispers. ‘And it takes comparisons very badly.’",
  "Пойти по старой тропе и не спорить": "Take the old path and do not argue",
  "Похвалить тропу вслух и попросить короткую дорогу": "Praise the path aloud and ask it for a shorter route",
  "Поручить Коню проехать вперёд и заставить тропу “догонять”": "Ask the Knight to ride ahead and make the path ‘catch up’",
  "{knightName} смотрит на изгиб дороги. «Если она хочет соревнования, можно дать ей соревнование».": "{knightName} watches the road bend. ‘If it wants a competition, we can give it one.’",
  "Прорубить собственный маршрут": "Cut your own route through the forest",
  "Вернуться и выбрать другую дорогу": "Turn back and choose another road"
});

export { EVENT_EN_V4_01 };
