const EVENT_EN_V4_03 = Object.freeze({
  "Костяной бухгалтер": "The Bone Accountant",
  "Лич Ротмар сидит за письменным столом прямо посреди кладбища. Вокруг него десятки духов стоят в очереди. На табличке написано: «Закрытие долгов перед окончательным упокоением».": "Lich Rotmar sits at a writing desk in the middle of a cemetery. Dozens of spirits queue around him. A sign reads: ‘Debt Settlement Before Final Rest.’",
  "Ротмар объясняет, что при жизни был казначеем и не может уйти, пока баланс не сойдётся до последней монеты. Один крестьянин должен короне три медяка. Рыцарь — сорок золотых. Какой-то герцог, судя по книгам, должен семь кур и мост.": "Rotmar explains that he was a treasurer in life and cannot depart until the accounts balance to the last coin. One peasant owes the Crown three coppers. A knight owes forty gold. According to the books, some duke owes seven chickens and a bridge.",
  "«Мост получить сложнее всего», — жалуется лич.": "‘The bridge is the hardest part to collect,’ the lich complains.",
  "Списать мелкие долги королевским указом": "Cancel the minor debts by royal decree",
  "Собрать с духов всё, что они ещё могут отдать": "Collect whatever the spirits can still pay",
  "Поручить Ферзю свести книги так, чтобы Ротмар наконец получил нулевой баланс": "Ask the Queen to reconcile the books so Rotmar can finally reach a zero balance",
  "{queenName} листает книги. «Он не проклят. Он просто не умеет оставить работу незаконченной».": "{queenName} flips through the ledgers. ‘He is not cursed. He simply does not know how to leave a job unfinished.’",
  "Купить долговую книгу как источник будущих требований": "Buy the debt ledger as a source of future claims",
  "Оставить Ротмара считать дальше": "Leave Rotmar to keep counting",

  "Вдовья свадьба": "The Widow's Wedding",
  "У разрушенной часовни стоит свадебная процессия из призраков. Все ждут жениха. Единственный живой человек среди них — очень старый Ард, который сидит на камне в чистой рубахе и дрожит не от холода.": "A ghostly wedding procession waits beside a ruined chapel. Everyone is waiting for the groom. The only living person among them is the very old Ard, sitting on a stone in a clean shirt and trembling from something other than cold.",
  "Селена погибла в день их свадьбы шестьдесят лет назад. Ард обещал, что однажды вернётся и закончит обряд. Сегодня он пришёл исполнить обещание, но теперь боится, что после клятвы не сможет уйти вместе с живыми.": "Selena died on their wedding day sixty years ago. Ard promised that one day he would return and finish the ceremony. Today he has come to keep that promise, but now fears that after the vow he will no longer be able to leave with the living.",
  "Селена не угрожает. Она просто держит для него место рядом с собой.": "Selena makes no threats. She simply keeps a place for him beside her.",
  "Позволить Арду закончить свадьбу": "Allow Ard to finish the wedding",
  "Уговорить Селену отпустить обещание": "Persuade Selena to release him from the promise",
  "Поручить Слону завершить обряд символически, не связывая Арда с мёртвыми": "Ask the Bishop to complete the rite symbolically without binding Ard to the dead",
  "{bishopName} тихо говорит: «Клятва связывает её. Его держит только чувство вины».": "{bishopName} says quietly, ‘The vow binds her. Only guilt is holding him.’",
  "Увести Арда силой": "Take Ard away by force",

  "Кладбище аплодирует": "The Cemetery Applauds",
  "На пустом кладбище бродячий артист Фелен играет на лютне. После каждой песни из-под земли раздаются аплодисменты. Настоящие, ритмичные, иногда с восторженным стуком по крышкам гробов.": "In an empty cemetery, traveling performer Felen plays the lute. After every song, applause rises from beneath the ground. Real, rhythmic applause, sometimes accompanied by enthusiastic pounding on coffin lids.",
  "Фелен выглядит измученным. Он случайно сыграл здесь три дня назад и теперь не может уйти: стоит ему сделать шаг к воротам, публика начинает свистеть и швырять наружу мелкие кости.": "Felen looks exhausted. He happened to play here three days ago and now cannot leave: the moment he takes a step toward the gate, the audience begins to boo and throws small bones out of the graves.",
  "«У них очень высокие требования к репертуару», — шепчет артист. — «И совершенно нет чувства времени».": "‘They have very high standards for repertoire,’ the performer whispers. ‘And absolutely no sense of time.’",
  "Король слушает очередные аплодисменты. «Пожалуй, самая преданная публика из всех, что я встречал».": "The King listens to another round of applause. ‘Perhaps the most devoted audience I have ever encountered.’",
  "Дать Фелену новый репертуар и помочь закончить выступление": "Give Felen new material and help him finish the performance",
  "Заплатить артисту и забрать его с собой": "Pay the performer and take him with you",
  "Сыграть последнюю песню самим": "Play the final song yourselves",
  "Разрушить сцену и прекратить концерт силой": "Destroy the stage and end the concert by force",
  "Послушать одну песню и уйти, пока публика довольна": "Listen to one song and leave while the audience is satisfied",

  "Сторож, который забыл умереть": "The Guard Who Forgot to Die",
  "На перевале один скелет в проржавевших доспехах удерживает мост против стаи тварей из ущелья. Он сражается плохо: щит расколот, меч туп, одна рука держится на ремне. Но каждый раз возвращается на середину моста.": "At the mountain pass, a lone skeleton in rusted armor holds a bridge against a pack of creatures from the gorge. He fights poorly: his shield is split, his sword is blunt, and one arm is held on by a strap. Yet each time he returns to the center of the bridge.",
  "За ним прячется караван живых беженцев. Никто не знает имени стража. На нагруднике осталась только половина старого герба.": "A caravan of living refugees shelters behind him. No one knows the guard's name. Only half of an old crest remains on his breastplate.",
  "Когда Король подходит ближе, скелет поворачивает пустой череп и произносит: «Смена прибыла?»": "When the King comes closer, the skeleton turns his empty skull and asks, ‘Has the relief arrived?’",
  "Король снимает перчатку и касается старого герба. «Да. Смена прибыла».": "The King removes a glove and touches the old crest. ‘Yes. The relief has arrived.’",
  "Принять бой вместо стража": "Take the guard's place in the fight",
  "Помочь каравану уйти скрытно, пока Варек держит мост": "Help the caravan escape unseen while Varek holds the bridge",
  "Предложить Вареку место в отряде после боя": "Offer Varek a place in the roster after the battle",
  "Попытаться упокоить стража прямо сейчас": "Try to lay the guard to rest immediately",
  "Обойти перевал": "Bypass the pass",

  "Паутина с ценником": "The Web with a Price Tag",
  "В узком каньоне дорогу перекрывает паутина толщиной с корабельный канат. На ней висят маленькие таблички: «Проход — 8 золотых», «Разрезание полотна — 25 золотых», «Жалобы принимаются по вторникам».": "In a narrow canyon, a web as thick as ship's rope blocks the road. Small signs hang from it: ‘Passage — 8 gold,’ ‘Cutting the web — 25 gold,’ ‘Complaints accepted on Tuesdays.’",
  "Тёмная эльфийка Нерисс сидит в кресле под навесом и ведёт счёт. Рядом огромный паук спокойно плетёт новый участок дороги в сеть.": "The dark elf Neriss sits in a chair beneath an awning keeping accounts. Beside her, an enormous spider calmly weaves another section of road into its web.",
  "«Не я придумала пошлину, — говорит Нерисс. — Он». Паук стучит лапой по табличке с ценой.": "‘I did not invent the toll,’ Neriss says. ‘He did.’ The spider taps a price sign with one leg.",
  "Заплатить 8 Gold и пройти": "Pay 8 Gold and pass",
  "Попробовать торговаться с Нерисс": "Try to bargain with Neriss",
  "Поручить Коню найти маршрут по стене каньона в обход сети": "Ask the Knight to find a route along the canyon wall around the web",
  "{knightName} смотрит на крепления сети. «Паутина закрывает дорогу. Но сама дорога всё ещё наша».": "{knightName} studies the web's anchor points. ‘The web blocks the road. But the road itself is still ours.’",
  "Разрубить паутину": "Cut through the web",
  "Вернуться назад": "Turn back",

  "Убийца просит свидетеля": "The Assassin Asks for a Witness",
  "Под старым акведуком тёмная эльфийка Вессара ждёт отряд рядом со связанным человеком. Она не прячется и не держит оружие в руках. Два кинжала лежат на камне перед ней.": "Beneath an old aqueduct, the dark elf Vessara waits for the roster beside a bound man. She makes no attempt to hide and carries no weapon in her hands. Two daggers lie on a stone before her.",
  "«Я пришла убить его, — говорит она. — Но заказ оказался ложным. Теперь заказчик заплатит другому убийце, а этот человек всё равно умрёт. Мне нужен свидетель, что контракт расторгнут по причине мошенничества».": "‘I came to kill him,’ she says. ‘But the contract was fraudulent. Now the client will pay another killer and this man will die anyway. I need a witness that the contract was terminated for fraud.’",
  "Купец Олм кивает слишком быстро и обещает Королю всё что угодно. На его пальце — кольцо того же дома, что стоит на контракте Вессары.": "Merchant Olm nods too quickly and promises the King anything at all. On his finger is a ring bearing the same house mark as Vessara's contract.",
  "Засвидетельствовать расторжение контракта": "Witness the termination of the contract",
  "Потребовать показать весь контракт и приложение к нему": "Demand to see the entire contract and its appendix",
  "Поручить Ферзю вывести Олма на противоречиях": "Ask the Queen to expose Olm's contradictions",
  "{queenName} смотрит на кольцо Олма. «Он не случайная жертва. Вопрос только в том, какую роль он играет в собственной казни».": "{queenName} looks at Olm's ring. ‘He is not a random victim. The only question is what role he is playing in his own execution.’",
  "Передать Олма Вессаре и не задавать вопросов": "Hand Olm over to Vessara and ask no questions",
  "Арестовать обоих": "Arrest them both",

  "Чужая тень": "Someone Else's Shadow",
  "Проводник Саэр встречает отряд у входа в подземный тракт и первым делом просит никому не смотреть ему под ноги. Разумеется, все смотрят.": "Guide Saer meets the roster at the entrance to an underground road and immediately asks everyone not to look at his feet. Naturally, everyone looks.",
  "Его тень отстаёт на полшага. Когда Саэр останавливается, она делает ещё один шаг. Когда он поднимает левую руку, тень поднимает правую.": "His shadow lags half a step behind. When Saer stops, it takes one more step. When he raises his left hand, the shadow raises its right.",
  "«Три дня назад она была моей», — говорит Саэр. — «Теперь я не уверен». Тень поворачивает голову к Королю, хотя сам проводник продолжает смотреть прямо.": "‘Three days ago it was mine,’ Saer says. ‘Now I am not sure.’ The shadow turns its head toward the King while the guide himself continues staring straight ahead.",
  "Идти с Саэром, не вмешиваясь": "Travel with Saer without interfering",
  "Отделить Саэра от тени ярким светом": "Separate Saer from the shadow with bright light",
  "Поручить Слону определить, кому принадлежит тень на самом деле": "Ask the Bishop to determine whom the shadow really belongs to",
  "{bishopName} закрывает фонарь заслонкой. «Она не повторяет его. Она учится быть им».": "{bishopName} shutters the lantern. ‘It is not copying him. It is learning to be him.’",
  "Предложить тени договориться напрямую": "Offer to negotiate with the shadow directly",
  "Отказаться от проводника": "Refuse the guide",

  "Паук проиграл всадника": "The Spider Lost Its Rider",
  "На каменной площадке гигантская паучиха Сита сидит у стены и демонстративно отвернулась от своего всадника. Кель стоит рядом с седлом в руках и выглядит оскорблённым сильнее, чем человек после дуэли.": "On a stone platform, the giant spider Sita sits by the wall and pointedly turns away from her rider. Kel stands nearby holding a saddle and looks more offended than a man after a duel.",
  "Оказывается, накануне он проиграл Ситу в кости. Ставкой было право выбирать маршрут три дня. Паучиха выбрала вертикальную стену ущелья. Кель считает, что это «буквальное издевательство над условиями пари».": "It turns out he lost to Sita at dice the night before. The wager was the right to choose the route for three days. The spider chose the vertical wall of the gorge. Kel considers this ‘a literal mockery of the terms of the wager.’",
  "Сита аккуратно выкладывает перед Королём три игральные кости. Две из них явно подпилены.": "Sita carefully places three dice before the King. Two of them have clearly been shaved.",
  "Признать победу Ситы и помочь Келю поднять груз по стене": "Acknowledge Sita's victory and help Kel haul the cargo up the wall",
  "Потребовать переигровку честными костями": "Demand a rematch with honest dice",
  "Поручить Коню провести честную скачку вместо азартной игры": "Ask the Knight to hold a fair race instead of another game of chance",
  "{knightName} берёт одну кость. «Не уверен, что паук здесь самый нечестный игрок».": "{knightName} picks up one die. ‘I am not sure the spider is the least honest player here.’",
  "Купить подпиленные кости как улику": "Buy the shaved dice as evidence",
  "Уйти, пока спор не перерос в семейную драму всадника и паука": "Leave before the dispute becomes a family drama between rider and spider",

  "Обсидиан помнит прикосновения": "Obsidian Remembers Touch",
  "В подземном зале стоит чёрная обсидиановая плита. Если провести ладонью по её поверхности, она показывает последнее сильное воспоминание человека, касавшегося её до вас.": "A black obsidian slab stands in an underground hall. If you run a palm across its surface, it reveals the last powerful memory of the person who touched it before you.",
  "Семья погибшего князя хочет узнать, кто последним видел его живым. Камнерез Эшра утверждает, что плита готова, но предупреждает: каждое новое прикосновение стирает часть предыдущего следа.": "The family of a dead prince wants to know who saw him alive last. Stonecutter Eshra says the slab is ready, but warns that every new touch erases part of the previous trace.",
  "Есть только одна попытка. И внезапно выясняется, что все четверо наследников хотят прикоснуться первыми.": "There is only one attempt. And suddenly it becomes clear that all four heirs want to touch it first.",
  "Разрешить старшему наследнику коснуться плиты": "Allow the eldest heir to touch the slab",
  "Коснуться плиты Королём, приняв риск чужого воспоминания": "Have the King touch the slab and accept the risk of another person's memory",
  "Поручить Ферзю определить наиболее подозрительного наследника до использования плиты": "Ask the Queen to identify the most suspicious heir before the slab is used",
  "{queenName} не смотрит на плиту. Она смотрит на наследников. «Тот, кто больше всех торопится увидеть правду, может бояться, что её увидят без него».": "{queenName} does not look at the slab. She watches the heirs. ‘The one most eager to see the truth may be afraid that it will be seen without him.’",
  "Отказать семье и запечатать плиту": "Refuse the family and seal the slab",
  "Продать право первого прикосновения тому, кто заплатит больше": "Sell the right of first touch to the highest bidder",

  "Чай у палача": "Tea with the Executioner",
  "Дом палача Мерета стоит рядом с дорогой и ничем не отличается от обычной дачи, если не считать идеально заточенного топора над камином. Мерет приглашает отряд на чай. Он печёт удивительно хорошие булочки.": "Executioner Meret's house stands beside the road and looks like an ordinary country cottage, except for the perfectly sharpened axe above the fireplace. Meret invites the roster in for tea. He bakes surprisingly good buns.",
  "За столом его дочь Лиан объявляет, что хочет стать лекарем. Отец против. «Семейное ремесло», — говорит он и кивает на топор.": "At the table, his daughter Lian announces that she wants to become a healer. Her father objects. ‘Family trade,’ he says, nodding toward the axe.",
  "«У нас и так много семейного ремесла», — отвечает Лиан. На полке стоят семь поколений подписанных капюшонов.": "‘We already have plenty of family trade,’ Lian replies. Seven generations of labeled hoods sit on a shelf.",
  "Король берёт вторую булочку. «Удивительно, как быстро разговор о профессии становится опаснее самого топора».": "The King takes a second bun. ‘Remarkable how quickly a conversation about careers becomes more dangerous than the axe itself.’",
  "Поддержать Лиан и оплатить её дорогу к лекарям": "Support Lian and pay for her journey to the healers",
  "Согласиться с Меретом: ремеслу нужен наследник": "Agree with Meret that the trade needs an heir",
  "Предложить компромисс: Лиан учится лечить, но знает анатомию лучше любого палача": "Propose a compromise: Lian studies healing but learns anatomy better than any executioner",
  "Пригласить Лиан в поход как полевого лекаря": "Invite Lian into the campaign as a field healer",
  "Допить чай и не лезть в чужую семью": "Finish the tea and stay out of another family's affairs"
});

export { EVENT_EN_V4_03 };
