const EVENT_EN_V5_07=Object.freeze({
"Если его заставить идти сейчас, через милю он действительно станет памятником трудовому спору":"If we force him to walk now, in a mile he really will become a monument to a labor dispute",
"Механизм повторяет команду. Второй голос команду даёт":"The mechanism repeats the command. The second voice is giving it",
"Солнце оставим на месте. Амбар тоже. А вот зеркало можно поставить":"We will leave the sun where it is. The barn too. The mirror, however, can be moved",
"Сделка становится заметно сложнее, когда товар способен отказаться":"A deal becomes considerably more complicated when the merchandise can refuse",
"Часы не смеются сами. Они вызывают кого-то":"Clocks do not laugh by themselves. They are summoning someone",
"Сначала я хочу понять, что именно его создатели называли отсутствием Короля. У инженеров бывают опасные определения":"First I want to know what its creators meant by the King's absence. Engineers can have dangerous definitions",
"По-моему, он не захватил дом. Он заселился":"I do not think he seized the house. I think he moved in",
"Она не считает деньги. Она считает охрану":"She is not counting the money. She is counting the guards",
"Он не заманивает. Он торопит":"He is not luring us. He is rushing us",
"И, к сожалению для Лема, по делу":"And unfortunately for Lem, with good reason",
"Иногда человек возвращается, а место, которого ты ждал, — нет. Покажем ему дорогу ещё раз":"Sometimes the person returns, but the place you waited for does not. We will show him the road once more",
"Это не вода изменила направление. Кто-то наверху собирает добычу":"The water did not change direction. Someone upstream is collecting the catch",
"Начнём с вопроса, почему предмет сделки выглядел как монета":"Let us begin by asking why the object in the deal looked like a coin",
"Если атакуем, это будет самая унизительная осада в моей жизни":"If we attack, this will be the most humiliating siege of my life",
"Он не знает мёртвых. Он знает нас":"It does not know the dead. It knows us",
"Я могу закончить эту войну ведром воды. Но, кажется, это обидит обе армии":"I can end this war with a bucket of water. But I suspect that would offend both armies",
"Она смотрит не на дорогу. Она смотрит на солнце":"She is not looking at the road. She is looking at the sun",
"У некоторых корон срок жизни — один рассвет. Обязательства обычно держатся дольше":"Some crowns last only one dawn. Obligations usually last longer",
"Он продаёт не место. Он продаёт чужое терпение":"He is not selling a place. He is selling someone else's patience",
"Удивительно. Он предусмотрел невозможность исполнения и назвал её услугой":"Remarkable. He anticipated that fulfillment was impossible and called it a service",
"Поворот я восстановлю. А вот насколько опасно было после слова “опасно”, придётся выяснять на месте":"I can reconstruct the turn. How dangerous things became after the word “dangerous” we will have to learn on site",
"У меня таких было три. Теперь жалею, что тратил на еду":"I had three of those. Now I regret spending them on food",
"Мы можем снять его без лестницы. Только Зику это не понравится":"We can get him down without a ladder. Zik will not like it",
"Сундук безопасен. Для всех, кроме того, кто внутри":"The chest is safe. For everyone except whoever is inside",
"Он продал ангелу светящееся кольцо и всё ещё пытается увеличить чек. Смелость впечатляет":"He sold an angel a glowing ring and is still trying to increase the bill. The courage is impressive",
"Мне больно это признавать, но она действительно держит":"It pains me to admit it, but it really is holding",
"Тогда сначала надо вспомнить не дорогу. Имя":"Then the first thing to remember is not the road. It is the name",
"Если тянуть ангела вниз, сеть затянется. Сначала надо договориться с восьминогим владельцем":"If we pull the angel down, the web will tighten. First we need to negotiate with the eight-legged owner",
"Когда право на землю сводят к достоинству правителя, отказаться от проверки труднее, чем кажется":"When the right to land is reduced to a ruler's worthiness, refusing the test is harder than it looks",
"Не знаю, что хуже: охрана или программа лояльности":"I do not know which is worse: the security or the loyalty program",
"Надпись старая. Имя нанесли тогда же. Значит, кто-то знал Эдрана раньше, чем он родился":"The inscription is old. The name was carved at the same time. That means someone knew Edran before he was born",
"Если организаторы хотели запретить нежить, стоило написать “нежить”, а не философское определение жизни":"If the organizers wanted to ban the undead, they should have written “undead,” not a philosophical definition of life",
"Он говорит правду. Дерево уже умирает изнутри":"He is telling the truth. The tree is already dying from within",
"Милосердие ничего не доказывает, пока защищать приходится того, кого защищать неприятно":"Mercy proves nothing until you have to defend someone unpleasant to defend",
"Они оба правы. Просто один говорит о рассвете, другая — о вечере":"They are both right. One is speaking about dawn, the other about evening",
"Удивительно. Впервые на поле есть командующий, который точно не понимает, что от него хотят":"Remarkable. For once, there is a commander on the field who definitely does not understand what anyone wants from him",
"Наконец-то рынок, к которому я готов":"Finally, a market I am prepared for",
"Они не спорят о том, что произошло. Они описывают четыре разных момента одной ночи":"They are not arguing about what happened. They are describing four different moments from the same night"
});export{EVENT_EN_V5_07};