const EVENT_EN_V4_02 = Object.freeze({
  "Пустая охота": "The Empty Hunt",
  "Охотница Сиэль встречает отряд у ряда аккуратно развешенных луков. Луки принадлежат её товарищам, ушедшим ночью на охоту. Их самих нет.": "Huntress Siel meets the roster beside a row of neatly hung bows. The bows belong to her companions, who went hunting during the night. The hunters themselves are gone.",
  "Следы уходят в лес и обрываются одновременно, будто трое людей в один момент перестали касаться земли. На ветке над последним отпечатком висит свежая стрела. К ней привязана полоска ткани с надписью: «Охота окончена. Теперь очередь леса».": "The tracks lead into the forest and all end at once, as though three people simply stopped touching the ground at the same moment. A fresh arrow hangs from a branch above the final print. A strip of cloth tied to it reads: ‘The hunt is over. Now it is the forest's turn.’",
  "Из глубины чащи доносится человеческий свист. Сиэль вздрагивает: так её брат всегда подзывал собак.": "A human whistle comes from deep in the thicket. Siel flinches: that is how her brother always called the dogs.",
  "Идти за свистом всей группой": "Follow the whistle with the entire group",
  "Развести огонь и заставить похитителей показаться": "Light a fire and force the abductors to reveal themselves",
  "Поручить Коню проверить кроны и верхние тропы": "Ask the Knight to check the canopy and upper trails",
  "{knightName} смотрит вверх, а не на следы. «Они не исчезли. Их унесли».": "{knightName} looks upward instead of at the tracks. ‘They did not disappear. They were carried away.’",
  "Убедить Сиэль не рисковать остальными": "Convince Siel not to risk the others",

  "Дерево наследников": "The Heirs' Tree",
  "Трое эльфийских наследников стоят вокруг молодого дерева и спорят, кому принадлежит родовое поместье. По традиции древо должно распустить листья в сторону законного наследника. Сегодня оно распустило три ветви — по одной к каждому.": "Three elven heirs stand around a young tree arguing over who owns the ancestral estate. Tradition says the tree should unfurl its leaves toward the rightful heir. Today it has grown three branches—one toward each of them.",
  "Садовник Финн тихо объясняет Королю, что никто из троих не знает главного: их мать при жизни собиралась разделить земли, но не успела оформить волю. Сам Финн видел письмо, однако спрятал его после её смерти, опасаясь семейной войны.": "Gardener Finn quietly explains to the King that none of the three knows the most important fact: while alive, their mother intended to divide the lands, but never formalized her wishes. Finn himself saw the letter, but hid it after her death for fear of a family war.",
  "«Теперь война всё равно пришла, — говорит он. — Только пока без мечей».": "‘Now the war has come anyway,’ he says. ‘Only without swords so far.’",
  "Потребовать от Финна показать письмо": "Demand that Finn produce the letter",
  "Признать раздел поместья на три части": "Recognize the division of the estate into three parts",
  "Поручить Ферзю провести переговоры так, чтобы никто не проиграл публично": "Ask the Queen to negotiate so that no one loses publicly",
  "{queenName} наблюдает за наследниками. «Их спор не о земле. Каждый хочет услышать, что мать любила именно его больше остальных».": "{queenName} watches the heirs. ‘Their argument is not about the land. Each of them wants to hear that their mother loved them most.’",
  "Пусть дерево решит ещё раз после ночи": "Let the tree decide again after the night",
  "Отказаться судить чужую семью": "Refuse to judge another family",

  "Орк, который сдаётся слишком хорошо": "The Orc Who Surrenders Too Well",
  "Орк Браг выходит на дорогу, бросает топор, поднимает руки и объявляет: «Сдаюсь! Без условий!» За кустами тут же появляются ещё четыре орка и тоже сдаются. Один даже принёс верёвку, чтобы его связали.": "The orc Brag steps onto the road, drops his axe, raises his hands, and announces: ‘I surrender! No conditions!’ Four more orcs immediately emerge from behind the bushes and surrender as well. One has even brought rope so he can be tied up.",
  "Через минуту выясняется причина. Их вождь проиграл спор и приказал пятерым неделю чистить выгребные ямы лагеря. Плен у Короля кажется им более достойной альтернативой.": "A minute later the reason becomes clear. Their chief lost a wager and ordered the five of them to clean the camp latrines for a week. Captivity under the King seems like the more dignified alternative.",
  "«Мы честные пленные, — уверяет Браг. — Можем даже попытаться сбежать, если у вас так принято».": "‘We are honest prisoners,’ Brag assures you. ‘We can even try to escape, if that is customary here.’",
  "Король смотрит на пятерых добровольных пленников. «Мне не нравится, когда капитуляция выглядит как выгодное предложение для проигравшей стороны».": "The King looks at the five voluntary prisoners. ‘I do not like surrender looking like a bargain for the losing side.’",
  "Взять их пленными и заставить работать на переходе": "Take them prisoner and make them work during the march",
  "Вернуть их вождю за награду": "Return them to their chief for a reward",
  "Предложить одному орку честное место в отряде": "Offer one orc an honest place in the roster",
  "Помочь им придумать испытание лучше выгребных ям": "Help them devise a trial better than cleaning latrines",
  "Отправить пятерых обратно немедленно": "Send all five back immediately",

  "Барабан, который вызывает дождь. Иногда": "The Drum That Summons Rain. Sometimes",
  "Шаман Урх показывает огромный барабан, натянутый синей кожей. По его словам, барабан вызывает дождь. Племя очень нуждается в дожде. Проблема в том, что последние три попытки вызвали сначала град, потом стаю гусей, а затем налогового чиновника из соседнего княжества.": "Shaman Urkh shows you an enormous drum stretched with blue hide. According to him, the drum summons rain. The tribe badly needs rain. The problem is that the last three attempts summoned hail, then a flock of geese, and finally a tax official from a neighboring principality.",
  "«Чиновник был хуже града», — мрачно говорит Урх.": "‘The official was worse than the hail,’ Urkh says grimly.",
  "Орки предлагают Королю ударить в барабан как «человеку с большой судьбой». Небо при этом совершенно ясное.": "The orcs invite the King to strike the drum as ‘a man with a great destiny.’ The sky is perfectly clear.",
  "Ударить в барабан Королём": "Have the King strike the drum",
  "Продать оркам идею просто выкопать колодец": "Sell the orcs on the idea of simply digging a well",
  "Поручить Слону исправить руны призыва": "Ask the Bishop to correct the summoning runes",
  "{bishopName} рассматривает знаки на ободе. «Это не заклинание дождя. Это заклинание призыва. А вот кого именно — написано очень неразборчиво».": "{bishopName} examines the markings around the rim. ‘This is not a rain spell. It is a summoning spell. What exactly it summons is written very poorly.’",
  "Купить барабан": "Buy the drum",
  "Уйти до появления следующего чиновника": "Leave before the next official appears",

  "Долг за выбитый зуб": "A Debt for a Knocked-Out Tooth",
  "Воительница Гарра просит Короля рассудить спор. Молодой Пик выбил ей зуб на тренировке и теперь, по обычаю племени, обязан либо заплатить, либо дать выбить себе такой же.": "Warrior Garra asks the King to settle a dispute. Young Pik knocked out one of her teeth during training and, by tribal custom, must either pay compensation or let her knock out one of his.",
  "Пик согласен на второй вариант, но Гарра отказывается. «У него зубы хуже. Неравный обмен».": "Pik agrees to the second option, but Garra refuses. ‘His teeth are worse. Unequal trade.’",
  "Пик предлагает два зуба. Гарра считает это хвастовством. Через несколько минут спор о компенсации превращается в серьёзный вопрос чести, хотя всё началось с тренировочного локтя.": "Pik offers two teeth. Garra considers that boasting. Within minutes, the argument over compensation turns into a serious matter of honor, though it all began with an elbow during training.",
  "Заплатить Гарре от имени Пика": "Pay Garra on Pik's behalf",
  "Разрешить поединок до первой крови": "Allow a duel to first blood",
  "Поручить Ферзю предложить компенсацию, сохраняющую честь обоих": "Ask the Queen to propose compensation that preserves both their honor",
  "{queenName} тихо говорит Королю: «Они не спорят о зубе. Они спорят о том, кто имеет право быть великодушным».": "{queenName} says quietly to the King, ‘They are not arguing about a tooth. They are arguing over who has the right to be generous.’",
  "Предложить Пику вступить в отряд и “отработать зуб” службой": "Offer Pik a place in the roster and let him ‘work off the tooth’ through service",

  "Камень имени": "The Name Stone",
  "У подножия чёрной скалы сидит молодой орк без оружия. Сегодня он должен получить взрослое имя. По обычаю он кладёт ладонь на Камень Имени, а старейшина произносит то слово, которое «услышит» в ударе сердца.": "A young unarmed orc sits at the foot of a black cliff. Today he is to receive his adult name. By custom, he places his palm on the Name Stone and an elder speaks the word they ‘hear’ in his heartbeat.",
  "Старейшина Ома уже трижды начинала ритуал и трижды отдёргивала руку. Камень шепчет ей одно и то же имя: имя давно казнённого предателя.": "Elder Oma has begun the ritual three times and pulled her hand away three times. The stone keeps whispering the same name: the name of a traitor executed long ago.",
  "Подросток не знает об этом. Он ждёт, стараясь выглядеть бесстрашным.": "The youth knows none of this. He waits, trying to look fearless.",
  "Сказать подростку правду и оставить выбор ему": "Tell the youth the truth and leave the choice to him",
  "Назвать другое имя и скрыть шёпот камня": "Give him another name and conceal the stone's whisper",
  "Поручить Слону отделить память предка от судьбы потомка": "Ask the Bishop to separate an ancestor's memory from a descendant's fate",
  "{bishopName} прислушивается к камню. «Он не предсказывает судьбу. Он помнит кровь».": "{bishopName} listens to the stone. ‘It does not predict fate. It remembers blood.’",
  "Разбить Камень Имени": "Break the Name Stone",

  "Волк в начальниках": "The Wolf in Command",
  "Орочий патруль стоит по стойке смирно перед огромным серым волком. Волк сидит на ящике, на шее у него висит капитанский знак.": "An orc patrol stands at attention before an enormous grey wolf. The wolf sits on a crate with a captain's insignia hanging from its neck.",
  "Капитан Тург объясняет: ночью он проиграл командование Клыку в традиционной игре «Кто первым моргнёт». По закону клана победитель командует патрулём до следующего заката. Клык уже отменил строевую подготовку, приказал всем идти к реке и дважды пытался объявить белку разведчиком.": "Captain Turg explains that during the night he lost command to Fang in the traditional game of ‘Who Blinks First.’ Clan law says the winner commands the patrol until the next sunset. Fang has already canceled drill, ordered everyone to the river, and twice attempted to appoint a squirrel as a scout.",
  "«Формально он действует в рамках полномочий», — мрачно говорит Тург.": "‘Technically, he is acting within his authority,’ Turg says grimly.",
  "Признать полномочия Клыка и попросить безопасный проход": "Recognize Fang's authority and request safe passage",
  "Выкупить капитанский знак мясом": "Buy back the captain's insignia with meat",
  "Поручить Коню договориться с Клыком через язык поведения и жестов": "Ask the Knight to negotiate with Fang through behavior and gestures",
  "{knightName} смотрит на волка. «Если это командир, с ним надо говорить как с командиром».": "{knightName} looks at the wolf. ‘If that is the commander, we should speak to him like a commander.’",
  "Вызвать Клыка на новую игру “кто первым моргнёт”": "Challenge Fang to another game of ‘who blinks first’",
  "Оставить орков их уставу": "Leave the orcs to their regulations",

  "Чужой костёр": "Another's Campfire",
  "Две орочьи семьи спорят у костра из-за человеческого солдата. Его нашли в овраге после боя. Одна семья хочет обменять пленника на золото. Другая настаивает, что раненого, которому дали воду у костра, уже нельзя продавать: по их обычаю он стал гостем до рассвета.": "Two orc families argue beside a campfire over a human soldier found in a ravine after a battle. One family wants to exchange the prisoner for gold. The other insists that a wounded man given water by the fire can no longer be sold: by their custom he is a guest until dawn.",
  "Сам солдат едва в сознании. На его форме знак отряда, который недавно грабил орочьи деревни.": "The soldier is barely conscious. His uniform bears the insignia of a unit that recently raided orc villages.",
  "«Гость до рассвета, враг после рассвета», — говорит старший орк. До света остаётся меньше часа.": "‘A guest until dawn, an enemy after dawn,’ says the elder orc. Less than an hour remains until first light.",
  "Король смотрит на бледнеющее небо. «Удобно, когда честь имеет точное время окончания».": "The King looks at the paling sky. ‘Convenient when honor has a precise expiration time.’",
  "Выкупить солдата до рассвета": "Buy the soldier's freedom before dawn",
  "Убедить семьи продлить право гостя ещё на день": "Convince the families to extend his guest-right for another day",
  "Оставить решение оркам": "Leave the decision to the orcs",
  "Предложить солдату самому выбрать: плен или служба Королю": "Let the soldier choose for himself: captivity or service to the King",
  "Потребовать пленника как королевскую собственность": "Claim the prisoner as royal property",

  "Покойник с расписанием": "The Dead Man with a Schedule",
  "На старой дороге стоит полуразвалившийся дилижанс. На козлах сидит скелет в форме кондуктора и раздражённо сверяется с карманными часами.": "A half-collapsed stagecoach stands on the old road. A skeleton in a conductor's uniform sits on the box, irritably checking a pocket watch.",
  "«Опоздание — сто сорок два года», — сообщает он Королю. Внутри дилижанса сидят двенадцать скелетов-пассажиров. У каждого билет. Рем объясняет, что обязан доставить их в город, которого больше не существует, и не может изменить маршрут без подписи «действующего монарха».": "‘One hundred and forty-two years late,’ he informs the King. Twelve skeletal passengers sit inside the coach, each holding a ticket. Rem explains that he is required to deliver them to a city that no longer exists and cannot change the route without the signature of a ‘reigning monarch.’",
  "Он протягивает Королю перо. Чернила в пузырьке всё ещё свежие.": "He offers the King a quill. The ink in the bottle is still fresh.",
  "Король рассматривает формуляр. «Наконец-то чиновник, которого нельзя обвинить в медленной работе. Он буквально пережил ведомство».": "The King studies the form. ‘At last, an official who cannot be accused of working slowly. He has literally outlived the department.’",
  "Подписать изменение маршрута до ближайшего кладбища": "Sign a route change to the nearest cemetery",
  "Подписать закрытие рейса и освободить Рема от службы": "Sign the route closed and release Rem from service",
  "Потребовать оплатить дорожный налог за 142 года": "Demand payment of 142 years of road tax",
  "Не подписывать ничего, написанного чернилами неизвестного происхождения": "Sign nothing written in ink of unknown origin",

  "Дом, где мёртвые снимают обувь": "The House Where the Dead Remove Their Shoes",
  "Одинокий дом у дороги выглядит жилым. В печи огонь, на столе четыре миски, у порога аккуратно стоят три пары старых сапог. Хозяйка Агна приглашает отряд переждать грозу, но просит не трогать обувь.": "A lonely roadside house looks inhabited. A fire burns in the stove, four bowls sit on the table, and three pairs of old boots are neatly arranged by the threshold. The owner, Agna, invites the roster to wait out the storm but asks that no one touch the shoes.",
  "После полуночи к дому подходят трое мертвецов. Они снимают сгнившие ботинки, ставят рядом с остальными и входят босиком. Агна не пугается. «Муж и сыновья, — говорит она. — Возвращаются каждую грозу. Сидят до рассвета. Ничего плохого не делают».": "After midnight three dead men approach the house. They remove their rotted boots, place them beside the others, and enter barefoot. Agna is not afraid. ‘My husband and sons,’ she says. ‘They return with every storm. Sit until dawn. Never do any harm.’",
  "Сегодня четвёртая миска стоит перед пустым стулом Короля.": "Tonight the fourth bowl sits before the King's empty chair.",
  "Остаться до рассвета и не нарушать обычай дома": "Stay until dawn and respect the house's custom",
  "Спросить Агну, для кого четвёртая миска": "Ask Agna who the fourth bowl is for",
  "Поручить Слону выяснить, кого именно ждут мёртвые": "Ask the Bishop to determine exactly whom the dead are waiting for",
  "{bishopName} смотрит на пустой стул. «Они пришли не за ним. Они ждут того, кто должен был прийти вместе с ними».": "{bishopName} looks at the empty chair. ‘They did not come for him. They are waiting for the one who was supposed to come with them.’",
  "Изгнать мертвецов из дома": "Drive the dead out of the house",
  "Уйти до наступления ночи": "Leave before nightfall"
});

export { EVENT_EN_V4_02 };
