const EVENT_EN_V4C_02 = Object.freeze({
'Часы требуют точного времени':'The Clock Demands the Exact Time',
'На площади стоит гигантский механический часовой столб. Он остановился на 13:17 и объявил через медную трубу: «ВРЕМЯ НЕКОРРЕКТНО. ДВИЖЕНИЕ ЗАПРЕЩЕНО ДО УТОЧНЕНИЯ».':'A giant mechanical clock pillar stands in the square. It stopped at 13:17 and announced through a copper horn: “TIME INCORRECT. MOVEMENT PROHIBITED UNTIL CLARIFIED.”',
'После этого маленькие сторожевые автоматы перекрыли все дороги. Староста клянётся, что часы раньше просто звонили по праздникам.':'After that, small guard automatons blocked every road. The village elder swears the clock used to do nothing more than chime on holidays.',
'Проблема неожиданно философская: у трёх городских часов разное время, солнечные часы закрыты облаками, а единственный астроном уехал на свадьбу.':'The problem turns unexpectedly philosophical: the town’s three clocks all show different times, the sundial is hidden by clouds, and the only astronomer has left for a wedding.',
'Король смотрит на три разных циферблата. «Никогда не думал, что свобода передвижения однажды будет зависеть от ответа на вопрос “который час?”».':'The King looks at three different clock faces. “I never thought freedom of movement would one day depend on the answer to ‘what time is it?’”',
'Выбрать среднее время и установить его как официальное':'Choose the average time and declare it official',
'Сломать блокирующие автоматы':'Break the blocking automatons',
'Найти время по звёздам, дождавшись ночи':'Wait for night and determine the time from the stars',
'Объявить королевским указом, что сейчас ровно полдень':'Declare by royal decree that it is exactly noon',
'Обойти поселение':'Go around the settlement',

'Запасная личность':'A Spare Identity',
'М-9 приходит к мастеру памяти Элле на плановую замену кристалла. Старый носитель повреждён и скоро разрушится. Новый уже готов.':'M-9 comes to memory-master Ella for a scheduled crystal replacement. The old medium is damaged and will soon fail. The new one is ready.',
'Элла предупреждает: копирование сохранит воспоминания, навыки и характер, но старый кристалл всё равно перестанет работать. М-9 задаёт Королю вопрос, который мастер старается обходить: «ТОТ, КТО ПРОСНЁТСЯ В НОВОМ КРИСТАЛЛЕ, БУДУ ЛИ ЭТО Я?»':'Ella warns that copying will preserve memories, skills, and personality, but the old crystal will still stop functioning. M-9 asks the King the question the master keeps avoiding: “THE ONE WHO WAKES IN THE NEW CRYSTAL — WILL THAT BE ME?”',
'В мастерской становится очень тихо.':'The workshop becomes very quiet.',
'Посоветовать перенос: память и выборы важнее материала':'Advise the transfer: memory and choices matter more than the material',
'Посоветовать отказаться и прожить оставшееся время в старом теле':'Advise against it and live out the remaining time in the old body',
'Поручить Слону провести ритуал непрерывности сознания вместе с переносом':'Ask the Bishop to perform a continuity-of-consciousness rite during the transfer',
'{bishopName} говорит после долгой паузы: «Я могу проверить непрерывность памяти. Но не могу доказать ему непрерывность души».':'After a long pause, {bishopName} says, “I can verify continuity of memory. I cannot prove continuity of soul.”',
'Купить старый кристалл после переноса':'Buy the old crystal after the transfer',
'Не давать совет':'Offer no advice',

'Медведь и мёд, который ему не принадлежит':'The Bear and the Honey That Is Not His',
'Медведь сидит посреди пасеки с лапой в бочке мёда. Пасечница Дора стоит в десяти шагах с вилами. Никто не двигается.':'A bear sits in the middle of an apiary with one paw in a barrel of honey. Dora the beekeeper stands ten paces away holding a pitchfork. Nobody moves.',
'Медведь явно понимает, что его поймали. Он медленно вытаскивает лапу, облизывает её и делает вид, что просто проходил мимо. Затем садится на вторую бочку, окончательно уничтожая линию защиты.':'The bear clearly understands he has been caught. He slowly pulls out his paw, licks it, and pretends he was merely passing by. Then he sits on a second barrel, finally destroying the defensive line.',
'Дора шепчет: «Это третий раз. Он уже знает, где я храню лучшие рамки».':'Dora whispers, “This is the third time. He already knows where I keep the best combs.”',
'Отогнать медведя шумом':'Drive the bear away with noise',
'Оставить ему одну бочку и перенести остальное':'Leave him one barrel and move the rest',
'Поручить Пешке устроить безопасное кормовое место подальше от пасеки':'Ask the Pawn to make a safe feeding place away from the apiary',
'{pawnName} смотрит на следы. «Он приходит одной дорогой и уходит другой. Значит, можно договориться с его привычкой, даже если нельзя с ним самим».':'{pawnName} studies the tracks. “He comes by one route and leaves by another. We can negotiate with his habits even if we cannot negotiate with him.”',
'Атаковать медведя':'Attack the bear',

'Ворон возвращает долги':'The Raven Repays Debts',
'Каждое утро старый ворон приносит на площадь блестящий предмет и кладёт у ног одного из жителей. Сегодня он принёс серебряное кольцо вдове. Вчера — монету трактирщику. Позавчера — ключ кузнецу.':'Every morning an old raven brings a shiny object to the square and drops it at the feet of one resident. Today he brought a silver ring to a widow. Yesterday, a coin to the innkeeper. The day before, a key to the smith.',
'Люди поняли закономерность: птица возвращает вещи, которые кто-то когда-то украл у этих людей. Где он их берёт — неизвестно.':'The villagers have noticed the pattern: the bird returns things that were once stolen from these people. Where he finds them is unknown.',
'Когда появляется Король, ворон долго рассматривает его, улетает и через час возвращается с маленькой короной из детской игрушки.':'When the King appears, the raven studies him for a long time, flies away, and returns an hour later carrying a tiny crown from a child’s toy.',
'Король берёт деревянную корону. «Не припомню, чтобы заявлял о пропаже. Но теперь мне интересно, у кого она была».':'The King takes the wooden crown. “I do not remember reporting it missing. Now I am curious who had it.”',
'Проследить за вороном до его тайника':'Follow the raven to his cache',
'Оставить птицу в покое и позволить ей продолжать возвращать вещи':'Leave the bird alone and let it keep returning things',
'Попытаться обменять блестящие монеты на доступ к тайнику':'Offer shiny coins in exchange for access to the cache',
'Поймать ворона':'Catch the raven',
'Сохранить игрушечную корону':'Keep the toy crown',

'Волки ведут караван':'Wolves Escort the Caravan',
'На снегу видны следы каравана, вокруг которых идут волчьи лапы. Не нападают. Не приближаются к лошадям. Просто сопровождают с обеих сторон.':'Caravan tracks cross the snow, flanked by prints from wolf paws. The wolves do not attack. They do not approach the horses. They simply escort the caravan on both sides.',
'Через несколько миль отряд находит сам караван. Купцы напуганы, но целы. Они говорят, что волки появились ночью и с тех пор каждый раз рычат, когда возницы пытаются свернуть на восточную дорогу.':'A few miles later the roster finds the caravan itself. The merchants are frightened but unharmed. They say the wolves appeared during the night and have growled every time the drivers tried to turn onto the eastern road.',
'На востоке всё выглядит спокойно. Волки смотрят именно туда и не моргают.':'Everything to the east looks peaceful. The wolves stare in that direction without blinking.',
'Послушать волков и вести караван другим маршрутом':'Trust the wolves and lead the caravan by another route',
'Проверить восточную дорогу всем отрядом':'Investigate the eastern road with the full roster',
'Поручить Коню разведать опасность, ориентируясь по поведению стаи':'Ask the Knight to scout the danger, using the pack’s behavior as a guide',
'{knightName} осматривает восточную дорогу. «Они не пасут караван. Они не дают ему войти куда-то».':'{knightName} studies the eastern road. “They are not herding the caravan. They are keeping it from entering something.”',
'Отогнать волков и продолжить прямо':'Drive the wolves away and continue straight ahead',
'Оставить караван и волков друг другу':'Leave the caravan and the wolves to each other',

'Лошадь выбирает хозяина':'The Horse Chooses Its Master',
'Конезаводчик Пат продаёт великолепного вороного жеребца. Проблема: жеребец отказывается принимать любого покупателя. Одного сбросил в корыто, второго загнал на дерево, третьему аккуратно снял зубами шляпу и бросил в навоз.':'Horse breeder Pat is selling a magnificent black stallion. The problem is that the stallion refuses every buyer. He threw one into a trough, chased another up a tree, and delicately removed a third man’s hat with his teeth before dropping it in manure.',
'При виде королевского отряда конь проходит мимо Короля, мимо Коня, мимо Ферзя — и останавливается перед Пешкой. Затем кладёт голову ей на плечо.':'When the royal roster arrives, the horse walks past the King, past the Knight, past the Queen — and stops in front of the Pawn. Then he rests his head on the Pawn’s shoulder.',
'Пат смотрит на это как человек, потерявший контроль над собственной торговой моделью.':'Pat watches like a man who has lost control of his own business model.',
'Купить жеребца для отряда':'Buy the stallion for the roster',
'Отказать и оставить выбор коня без результата':'Decline and leave the horse’s choice unanswered',
'Поручить Пешке провести жеребца через короткое испытание доверия':'Ask the Pawn to put the stallion through a short test of trust',
'{pawnName} осторожно гладит жеребца. «Я ничего не делал. Это он что-то решил».':'{pawnName} gently strokes the stallion. “I did not do anything. He decided something.”',
'Предложить Пату использовать жеребца не как товар, а как племенного коня':'Suggest Pat keep the stallion as breeding stock instead of merchandise',
'Попробовать продать право “быть выбранным королевским конём” богатому покупателю':'Try to sell a wealthy buyer the right to “be chosen by the royal horse”',

'Птицы замолчали':'The Birds Fell Silent',
'Сначала отряд замечает не звук, а его отсутствие. В лесу нет ни одной птицы. Даже насекомые будто стали тише.':'At first the roster notices not a sound, but its absence. There is not a single birdcall in the forest. Even the insects seem quieter.',
'На ветках сидят десятки воробьёв, синиц, ворон. Все живы. Все смотрят в одну сторону и не издают ни звука. Когда человек делает шаг туда, птицы синхронно поворачивают головы к нему.':'Dozens of sparrows, tits, and ravens sit on the branches. All alive. All staring in one direction without making a sound. When someone steps that way, every bird turns its head toward them at once.',
'На земле впереди лежит олень. На его боку нет раны, но тень под телом движется сама по себе.':'A deer lies on the ground ahead. There is no wound on its flank, but the shadow beneath the body moves on its own.',
'Развернуться и уйти тем же путём':'Turn around and leave the way you came',
'Проверить тело оленя':'Examine the deer’s body',
'Поручить Слону определить природу движущейся тени издалека':'Ask the Bishop to determine the nature of the moving shadow from a distance',
'{bishopName} говорит шёпотом: «Они молчат не потому, что боятся шума. Они боятся, что оно услышит, где они».':'{bishopName} whispers, “They are not silent because they fear noise. They are afraid it will hear where they are.”',
'Разжечь яркий огонь и выгнать сущность на свет':'Light a bright fire and force the entity into the light',
'Идти вперёд молча':'Move forward in silence',

'Черепаха опоздала на войну':'The Tortoise Was Late for the War',
'На дороге медленно движется огромная черепаха в старом армейском панцире. На боку выцветший номер полка. Ветеран Харс узнаёт знак и начинает смеяться, потом плакать.':'An enormous tortoise in an old military shell moves slowly along the road. A faded regimental number is painted on its side. Veteran Hars recognizes the mark, starts laughing, then begins to cry.',
'Сорок лет назад полк получил в подарок молодую боевую черепаху и отправил её с донесением в крепость. Никто не дождался. Война закончилась. Полк расформировали. Крепость стала рынком.':'Forty years ago, the regiment received a young war tortoise as a gift and sent it to a fortress carrying a dispatch. Nobody waited long enough. The war ended. The regiment was disbanded. The fortress became a market.',
'Черепаха всё ещё несёт под панцирем запечатанный пакет.':'The tortoise is still carrying a sealed packet beneath its shell.',
'Король принимает пакет. «Некоторые приказы переживают тех, кому были нужны».':'The King accepts the packet. “Some orders outlive the people who needed them.”',
'Доставить пакет в бывшую крепость и формально завершить поручение':'Deliver the packet to the former fortress and formally complete the assignment',
'Вскрыть пакет сейчас':'Open the packet now',
'Оставить письмо запечатанным и отпустить черепаху':'Leave the letter sealed and release the tortoise',
'Купить старый армейский панцирь у Харса':'Buy the old military shell from Hars',
'Продолжить путь':'Continue the journey',

'Фея украла тень Короля':'The Fae Stole the King’s Shadow',
'В полдень Король замечает, что у него нет тени. Она находится в трёх шагах впереди и пляшет под дудочку крошечной феи Пири.':'At noon the King notices he has no shadow. It is three paces ahead, dancing to the pipe of a tiny fae named Piri.',
'Пири утверждает, что не крала ничего материального. «Тень сама пошла. Ей скучно повторять одно и то же».':'Piri insists she stole nothing material. “The shadow left on its own. It was bored of repeating the same thing.”',
'Тень в подтверждение делает поклон, которого Король не делал. Затем пытается убежать в траву.':'As if in confirmation, the shadow makes a bow the King did not make. Then it tries to run into the grass.',
'Король смотрит на собственный силуэт. «Предательство от самого близкого спутника. В буквальном смысле».':'The King looks at his own silhouette. “Betrayal by my closest companion. Literally.”',
'Заплатить Пири за возвращение тени':'Pay Piri to return the shadow',
'Поймать собственную тень в круг света':'Trap your own shadow in a circle of light',
'Предложить тени один час свободы в обмен на добровольное возвращение':'Offer the shadow one hour of freedom in exchange for returning willingly',
'Потребовать дуэль с Пири за право собственности':'Challenge Piri to a duel over ownership',
'Идти дальше без тени':'Continue without a shadow',

'Муравьи выносят приговор':'The Ants Deliver a Verdict',
'Фея Тилли сидит внутри круга из сахарной пудры. Вокруг неё движется колонна муравьёв. По местному обычаю они должны решить, виновна ли она в краже росы из священного цветка: если муравьи пересекут круг — виновна; если обойдут — невиновна.':'The fae Tilly sits inside a circle of powdered sugar. A column of ants marches around her. Local custom says they must decide whether she stole dew from a sacred flower: if the ants cross the circle, she is guilty; if they go around it, she is innocent.',
'Проблема в том, что рядом кто-то уронил кусочек засахаренной груши. Муравьи явно колеблются между правосудием и обедом.':'The problem is that someone dropped a piece of candied pear nearby. The ants are clearly torn between justice and lunch.',
'Жрица предлагает Королю «не влиять на независимый суд», но сама осторожно подталкивает грушу палочкой.':'The priestess asks the King “not to influence the independent court,” while discreetly nudging the pear with a stick.',
'Убрать грушу и дать муравьям пройти свободно':'Remove the pear and let the ants move freely',
'Подвинуть грушу в сторону круга':'Move the pear toward the circle',
'Поручить Пешке найти, кто первым принёс приманку':'Ask the Pawn to find out who brought the bait',
'{pawnName} смотрит на следы сахара. «Если это суд, кто-то уже подкупает присяжных фруктом».':'{pawnName} studies the sugar trail. “If this is a court, someone is already bribing the jury with fruit.”',
'Объявить муравьиный суд недействительным':'Declare the ant court invalid',

'Маска смеётся раньше хозяина':'The Mask Laughs Before Its Wearer',
'Актёр Люм сидит у костра с деревянной маской на коленях. Он отказывается её надевать. Маска время от времени улыбается сама.':'Actor Lum sits by a fire with a wooden mask on his knees. He refuses to put it on. From time to time, the mask smiles by itself.',
'Люм купил её для комедии. На первом спектакле зрители смеялись ещё до шуток. На втором — смех начался до выхода актёров. На третьем люди продолжали смеяться после того, как один зритель упал замертво.':'Lum bought it for a comedy. At the first performance, the audience laughed before the jokes. At the second, the laughter began before the actors came on stage. At the third, people kept laughing after one spectator dropped dead.',
'Маска тихо хихикает. Люм просит уничтожить её. Маска просит надеть её на кого-нибудь «с чувством юмора».':'The mask giggles softly. Lum asks you to destroy it. The mask asks to be placed on someone “with a sense of humor.”',
'Сжечь маску':'Burn the mask',
'Продать маску коллекционеру через Люма':'Sell the mask to a collector through Lum',
'Поручить Слону снять чары смеха, сохранив обычную маску':'Ask the Bishop to remove the laughter enchantment while preserving the ordinary mask',
'{bishopName} не прикасается к маске. «Она питается не весельем. Она питается моментом, когда человек уже не может остановиться».':'{bishopName} does not touch the mask. “It does not feed on joy. It feeds on the moment when a person can no longer stop.”',
'Надеть маску на короткое время':'Wear the mask for a short time',
'Оставить маску завернутой и уйти':'Leave the mask wrapped up and depart',

'Цветок, который выбирает имя':'The Flower That Chooses a Name',
'В маленьком саду феи собрались вокруг единственного синего цветка. По их обычаю ребёнок получает имя, когда цветок впервые раскрывается рядом с ним. Но этот цветок уже раскрылся трижды — и каждый раз показывает разные узоры на лепестках.':'In a small garden, the fae gather around a single blue flower. By their custom, a child receives a name when the flower first opens beside them. But this flower has already opened three times, revealing a different pattern on its petals each time.',
'Неми, мать ребёнка, устала от советчиков. Один старейшина читает в узорах имя воина, другая — имя певца, третий вообще уверен, что цветок советует назвать младенца «Дождём, который приходит во вторник».':'Nemi, the child’s mother, is exhausted by advisers. One elder reads a warrior’s name in the patterns, another a singer’s name, and a third is convinced the flower recommends naming the baby “Rain That Comes on Tuesday.”',
'Ребёнок тем временем тянется не к цветку, а к грязной деревянной ложке.':'Meanwhile, the child reaches not for the flower but for a dirty wooden spoon.',
'Король смотрит на спорящих старейшин. «Иногда самое тяжёлое наследство — это ожидания, которые кладут в колыбель раньше имени».':'The King watches the arguing elders. “Sometimes the heaviest inheritance is the expectations placed in a cradle before a name.”',
'Предложить Неми самой выбрать имя, не спрашивая цветок':'Suggest that Nemi choose the name herself without asking the flower',
'Подождать четвёртого раскрытия':'Wait for a fourth bloom',
'Попросить ребёнка “выбрать” предмет и назвать по ассоциации':'Let the child “choose” an object and name them by association',
'Купить цветок у старейшин как редкую магическую реликвию':'Buy the flower from the elders as a rare magical relic',
'Не вмешиваться в семейный обряд':'Do not interfere with the family rite',

'Божья коровка не отдаёт мост':'The Ladybug Will Not Surrender the Bridge',
'Через ручей перекинут крошечный фейский мост, который для людей выглядит как декоративная арка. На нём сидит гигантская божья коровка Лала размером с телёнка и не позволяет строителям снять старые доски.':'A tiny fae bridge crosses the stream, looking to humans like a decorative arch. On it sits Lala, a giant ladybug the size of a calf, refusing to let the builders remove the old planks.',
'Феи объясняют: мост давно нужно заменить. Лала считает его своей крепостью. Она прожила под ним семь лет, пережила две грозы и один набег муравьёв.':'The fae explain that the bridge has needed replacement for years. Lala considers it her fortress. She has lived beneath it for seven years and survived two storms and an ant raid.',
'Когда строитель приближается с молотком, Лала расправляет крылья и издаёт неожиданно грозное жужжание.':'When a builder approaches with a hammer, Lala spreads her wings and produces a surprisingly menacing buzz.',
'Отогнать Лалу и начать ремонт':'Drive Lala away and begin repairs',
'Оставить старый мост и построить второй рядом':'Leave the old bridge and build another beside it',
'Поручить Ладье спроектировать новую конструкцию, сохранив убежище Лалы':'Ask the Rook to design a new structure while preserving Lala’s shelter',
'{rookName} осматривает опоры. «Можно построить новый мост поверх старого и оставить ей нижний ярус. Фактически — крепость с крышей».':'{rookName} examines the supports. “We can build the new bridge above the old one and leave her the lower level. Effectively, a fortress with a roof.”',
'Предложить Лале новое место с лучшей защитой':'Offer Lala a new home with better protection',
'Обойти ручей вброд':'Ford the stream',

'Бабочка знает короткую дорогу':'The Butterfly Knows a Shortcut',
'Фея Пэт уверяет, что её бабочка может провести отряд через лес за один час вместо целого дня. Бабочка действительно летит вперёд, оглядывается и ждёт.':'The fae Pat insists her butterfly can lead the roster through the forest in one hour instead of a full day. The butterfly does indeed fly ahead, look back, and wait.',
'Есть только одно условие: нельзя спрашивать, куда ведёт дорога. «Она обижается на недоверие», — говорит Пэт.':'There is only one condition: no one may ask where the road leads. “She is offended by distrust,” Pat says.',
'На третьем повороте лес становится незнакомым. На четвёртом солнце оказывается не с той стороны. На пятом бабочка пролетает сквозь ствол дерева и снова ждёт.':'At the third turn the forest becomes unfamiliar. At the fourth, the sun is on the wrong side. At the fifth, the butterfly flies through a tree trunk and waits again.',
'Следовать молча до конца':'Follow silently to the end',
'Спросить Пэт, где именно вы находитесь':'Ask Pat exactly where you are',
'Поручить Коню держать темп и запоминать точки перехода':'Ask the Knight to keep pace and memorize the transition points',
'{knightName} смотрит на исчезнувшую бабочку. «Она ведёт не через лес. Она срезает расстояние».':'{knightName} watches the vanished butterfly. “It is not leading us through the forest. It is cutting through distance.”',
'Попытаться поймать бабочку':'Try to catch the butterfly',
'Вернуться на обычную дорогу':'Return to the ordinary road'
});
export { EVENT_EN_V4C_02 };
