const EVENT_EN_V4C_03 = Object.freeze({
'Повар требует дуэль ложками':'The Cook Demands a Spoon Duel',
'Гоблин Губб выносит на дорогу гигантский котёл и объявляет Короля «оскорбителем супа». Никто из отряда суп не видел.':'Gubb the goblin rolls a giant cauldron into the road and declares the King an “insulter of soup.” Nobody in the roster has even seen the soup.',
'Выясняется, что неделю назад через эти места проходил человек в похожем плаще и сказал, что похлёбка Губба «слишком солёная». Повар запомнил только королевские цвета и теперь требует сатисфакции: дуэль гигантскими деревянными ложками до первого разбитого горшка.':'It turns out that a week ago a man in a similar cloak passed through and called Gubb’s stew “too salty.” The cook remembers only the royal colors and now demands satisfaction: a duel with giant wooden spoons until the first pot is broken.',
'Помощники уже принимают ставки.':'The assistants are already taking bets.',
'Король смотрит на ложку длиной с копьё. «Я готов отвечать за многие решения короны. За чужой отзыв о супе — пока нет».':'The King looks at a spoon as long as a spear. “I am prepared to answer for many decisions of the crown. Someone else’s opinion of soup is not yet one of them.”',
'Принять дуэль Королём':'Accept the duel as the King',
'Заплатить за “оскорбление” и попробовать суп':'Pay for the “insult” and taste the soup',
'Поручить Ладье выступить чемпионом в дуэли ложками':'Ask the Rook to serve as champion in the spoon duel',
'{rookName} берёт ложку и проверяет баланс. «Удивительно. Это плохая ложка, но вполне приличная дубина».':'{rookName} takes the spoon and checks its balance. “Remarkable. It is a terrible spoon, but a perfectly decent club.”',
'Найти настоящего критика по описанию':'Find the real critic from the description',
'Просто уйти':'Simply leave',

'Банк на колёсах':'The Bank on Wheels',
'На телеге с железными ставнями висит вывеска: «МОБИЛЬНЫЙ БАНК ШИККА. ВКЛАДЫ. КРЕДИТЫ. ПОГОНЯ ЗА ДОЛЖНИКАМИ». Сам Шикк сидит за окошком и щёлкает костяшками абака.':'A wagon with iron shutters bears a sign: “SHIKK’S MOBILE BANK. DEPOSITS. LOANS. DEBTOR PURSUIT.” Shikk himself sits behind a window clicking the beads of an abacus.',
'Он предлагает Королю кредит под 0% на первый день. На второй ставка становится 5%. На третий — 20%. На четвёртый «банк начинает интересоваться личным имуществом».':'He offers the King a loan at 0% for the first day. On the second, the rate becomes 5%. On the third, 20%. On the fourth, “the bank begins taking an interest in personal property.”',
'Сзади к телеге привязан человек с табличкой «НЕ ПРОЧИТАЛ ЧЕТВЁРТЫЙ ДЕНЬ».':'A man is tied to the back of the wagon wearing a sign: “DID NOT READ DAY FOUR.”',
'Взять 30 Gold и вернуть сразу же в тот же день':'Borrow 30 Gold and repay it immediately the same day',
'Положить 20 Gold на краткий вклад':'Deposit 20 Gold for a short term',
'Поручить Ферзю найти в правилах способ обратить проценты против банка':'Ask the Queen to find a clause that turns the interest against the bank',
'{queenName} смотрит на таблицу процентов. «Это не кредит. Это ловушка, которая умеет считать».':'{queenName} studies the interest table. “This is not a loan. It is a trap that knows arithmetic.”',
'Освободить привязанного должника силой':'Free the bound debtor by force',
'Не пользоваться гоблинским банком':'Do not use the goblin bank',

'Крыса выиграла гонку заранее':'The Rat Won the Race in Advance',
'На обочине проходит гоблинская гонка на гигантских крысах. Главный фаворит — Плюха — лежит на спине и спит. Её жокей Тик совершенно спокоен.':'A goblin race on giant rats is taking place by the roadside. The favorite, Plukha, lies on her back asleep. Her jockey Tik is perfectly calm.',
'Он показывает правила: победителем считается тот, чья крыса первой «пересечёт линию любым способом». Ночью Тик перенёс финишную ленту под спящую Плюху. Формально она уже пересекла линию.':'He shows you the rules: the winner is whoever’s rat first “crosses the line by any means.” During the night, Tik moved the finish ribbon underneath the sleeping Plukha. Technically, she has already crossed it.',
'Остальные жокеи только что заметили это и требуют судью. Судья убежал.':'The other jockeys have just noticed and are demanding a referee. The referee has fled.',
'Признать победу Плюхи по букве правил':'Recognize Plukha’s victory by the letter of the rules',
'Объявить перезаезд с новой формулировкой правил':'Order a rerun with newly worded rules',
'Поручить Пешке найти другой пункт, отменяющий трюк Тика':'Ask the Pawn to find another clause that invalidates Tik’s trick',
'{pawnName} перечитывает правила. «Он жульничает. Но хуже всего то, что он жульничает грамотно».':'{pawnName} rereads the rules. “He is cheating. The worst part is that he is cheating competently.”',
'Поставить 10 Gold на Плюху в честном перезаезде':'Bet 10 Gold on Plukha in a fair rerun',

'Карта сокровищ нарисована на самом сокровище':'The Treasure Map Is Drawn on the Treasure',
'Гоблин Ниб продаёт карту сокровищ. Карта выгравирована на тяжёлой золотой пластине. Стоимость самого металла, по ощущениям, выше большинства сокровищ, которые обычно ищут по картам.':'Nib the goblin is selling a treasure map. The map is engraved on a heavy gold plate. The metal itself appears to be worth more than most treasures people normally use maps to find.',
'Ниб не видит проблемы. «Это карта богатого качества».':'Nib sees no problem. “It is a rich-quality map.”',
'Маршрут ведёт в пещеру в трёх милях отсюда. Первый знак на карте гласит: «Если вы читаете это, вы уже держите половину сокровища».':'The route leads to a cave three miles away. The first inscription on the map reads: “If you are reading this, you are already holding half the treasure.”',
'Купить карту за 18 Gold и идти в пещеру':'Buy the map for 18 Gold and go to the cave',
'Купить карту и переплавить её, не ища клад':'Buy the map and melt it down without seeking the treasure',
'Поручить Коню быстро проверить пещеру до сделки':'Ask the Knight to quickly scout the cave before the deal',
'{knightName} смотрит на направление. «Пещеру можно проверить. Но пластину я бы из рук не выпускал».':'{knightName} looks toward the cave. “We can scout the cave. I would not let go of the plate, though.”',
'Убедить Ниба, что сама карта и есть товар, и сбить цену':'Convince Nib that the map itself is the merchandise and bargain down the price',
'Не покупать':'Do not buy it',

'Бочка, которая матерится':'The Barrel That Swears',
'Перевозчик Жук просит помочь с грузом. Одна из бочек ругается на него человеческим голосом. Очень изобретательно.':'Zhukh the carrier asks for help with his cargo. One of the barrels is cursing him in a human voice. Very creatively.',
'Жук утверждает, что внутри обычные маринованные грибы. Бочка утверждает, что внутри «жертва преступной логистики». Когда крышку пытаются открыть, она захлопывается сама и переходит на личности.':'Zhukh claims it contains ordinary pickled mushrooms. The barrel claims it contains “a victim of criminal logistics.” When anyone tries to open the lid, it slams itself shut and starts making personal insults.',
'После особенно длинной тирады Жук признаётся: бочку он купил дешёво на распродаже имущества мага.':'After an especially long tirade, Zhukh admits he bought the barrel cheaply at a wizard’s estate sale.',
'Разбить бочку':'Smash the barrel',
'Купить ругающуюся бочку у Жука':'Buy the swearing barrel from Zhukh',
'Поручить Слону снять говорящие чары с древесины':'Ask the Bishop to remove the speaking enchantment from the wood',
'{bishopName} стучит по обручу. «Голос идёт не изнутри. Заклинание сидит в древесине».':'{bishopName} taps the hoop. “The voice is not coming from inside. The spell is in the wood.”',
'Продать бочку обратно ближайшему магу':'Sell the barrel back to the nearest wizard',
'Оставить Жука спорить со своим грузом':'Leave Zhukh arguing with his cargo',

'Гоблин умер понарошку':'The Goblin Pretended to Die',
'У дороги идёт похороны. В гробу лежит гоблин Брик. Он время от времени приоткрывает один глаз и проверяет, ушёл ли страховой агент.':'A funeral is taking place by the road. Brik the goblin lies in the coffin. From time to time he cracks one eye open to see whether the insurance agent has left.',
'Вдова Тана шепчет Королю, что Брик жив и пытается получить выплату по страховке. Страховой агент, судя по выражению лица, тоже всё понимает, но не может отказать без «неоспоримого доказательства жизнедеятельности».':'The widow Tana whispers to the King that Brik is alive and trying to collect an insurance payout. Judging by his face, the insurance agent understands perfectly well, but cannot refuse without “indisputable evidence of biological activity.”',
'Брик чихает. Агент вздыхает: «Недостаточно. В договоре не уточняется, что мёртвые не чихают».':'Brik sneezes. The agent sighs. “Insufficient. The contract does not specify that dead people cannot sneeze.”',
'Король смотрит на агента. «Я начинаю подозревать, что эта компания заслуживает Брика как клиента».':'The King looks at the agent. “I am beginning to suspect this company deserves Brik as a client.”',
'Заставить Брика встать из гроба':'Make Brik get out of the coffin',
'Подтвердить смерть и взять долю страховой выплаты':'Confirm the death and take a share of the insurance payout',
'Предложить агенту проверку пульса как “неоспоримое доказательство”':'Suggest a pulse check as “indisputable evidence”',
'Пригласить Брика в отряд: ему явно нужна новая профессия':'Invite Brik into the roster: he clearly needs a new profession',

'Два врача, один пациент':'Two Doctors, One Patient',
'На обочине лежит раненый караванщик. Над ним спорят два врача. Эмма хочет остановить кровь и ждать. Крик хочет немедленно оперировать складным набором инструментов, половина которых похожа на столовые приборы.':'A wounded caravaner lies by the roadside while two doctors argue over him. Emma wants to stop the bleeding and wait. Krik wants to operate immediately with a folding set of tools, half of which resemble cutlery.',
'Оба компетентны. Оба ненавидят методы другого. Пациент в сознании и на каждое новое предложение тихо спрашивает: «А третьего врача нет?»':'Both are competent. Both hate the other’s methods. The patient is conscious and quietly asks after every new suggestion, “Is there no third doctor?”',
'Времени мало: рана ухудшается.':'There is little time: the wound is getting worse.',
'Поддержать Эмму':'Support Emma',
'Поддержать Крика':'Support Krik',
'Поручить Слону заставить их работать последовательно, а не спорить':'Ask the Bishop to make them work in sequence instead of arguing',
'{bishopName} осматривает рану. «Они оба правы, но говорят о разных рисках. Сначала кровь, потом операция».':'{bishopName} examines the wound. “They are both right, but they are talking about different risks. Stop the bleeding first, operate second.”',
'Использовать 2 Supplies и дать врачам всё необходимое':'Use 2 Supplies and give the doctors everything they need',

'Волк охраняет гоблинского младенца':'The Wolf Guards a Goblin Baby',
'Под корнями упавшего дерева лежит гоблинский младенец. Рядом — взрослая волчица. Она не подпускает никого, но и не угрожает ребёнку. Наоборот: укрывает его хвостом от ветра.':'A goblin baby lies beneath the roots of a fallen tree. An adult she-wolf is beside it. She allows no one near, but does not threaten the child. On the contrary, she shields the baby from the wind with her tail.',
'Через несколько минут появляются гоблины с факелами. Они ищут пропавшего ребёнка и, увидев волчицу, сразу поднимают оружие.':'A few minutes later, goblins with torches arrive searching for the missing child. The moment they see the she-wolf, they raise their weapons.',
'Младенец просыпается и тянет волчицу за ухо. Та терпеливо ложится ниже.':'The baby wakes and pulls the wolf by the ear. She patiently lowers herself.',
'Передать ребёнка семье и позволить убить волчицу':'Return the child to the family and allow them to kill the she-wolf',
'Защитить волчицу и объяснить, что она спасла ребёнка':'Protect the wolf and explain that she saved the child',
'Поручить Пешке спокойно забрать ребёнка, не пугая волчицу':'Ask the Pawn to retrieve the child calmly without frightening the wolf',
'{pawnName} встаёт между охотниками и волчицей. «Если бы она хотела его съесть, мы бы нашли совсем другую сцену».':'{pawnName} steps between the hunters and the she-wolf. “If she wanted to eat him, we would have found a very different scene.”',
'Предложить семье оставить волчице пищу и не преследовать её':'Ask the family to leave food for the wolf and not pursue her',

'Ангел и демон делят одно тело':'An Angel and a Demon Share One Body',
'Человек Невен говорит тремя голосами. Первый — его собственный. Второй принадлежит ангелу Саэлю. Третий — демону Мору.':'A human named Neven speaks with three voices. The first is his own. The second belongs to the angel Sael. The third belongs to the demon Mor.',
'Оба духа вселились в него во время магической аварии и теперь физически не могут выйти по отдельности. Саэль предлагает ритуал очищения. Мор предупреждает, что тот убьёт Невена. Мор предлагает другой ритуал. Саэль предупреждает, что он, вероятно, убьёт всех остальных.':'Both spirits entered him during a magical accident and now physically cannot leave separately. Sael proposes a cleansing rite. Mor warns it will kill Neven. Mor proposes a different ritual. Sael warns that one will probably kill everyone else.',
'Невен устало спрашивает Короля: «Есть вариант, где хоть кто-нибудь сначала спросит меня?»':'Neven wearily asks the King, “Is there an option where someone asks me first?”',
'Поддержать ангельский ритуал':'Support the angelic ritual',
'Поддержать демонический ритуал':'Support the demonic ritual',
'Поручить Слону разработать третий ритуал, исходя из воли Невена':'Ask the Bishop to devise a third ritual based on Neven’s wishes',
'{bishopName} слушает все три голоса. «Пока они спорят о том, кто имеет право его спасать, единственный хозяин тела остаётся без права голоса».':'{bishopName} listens to all three voices. “While they argue over who has the right to save him, the only owner of the body is left without a say.”',
'Оставить троих искать решение самостоятельно':'Leave the three of them to find a solution themselves',
'Попытаться изгнать обоих силой':'Try to exorcise both by force',

'Дварф построил мост для эльфийского дерева':'A Dwarf Built a Bridge for an Elven Tree',
'Посреди стройки растёт огромное старое дерево. Дварф Борда должен провести через это место каменный мост. Эльф Лиэль запрещает рубить дерево: оно старше обеих их семей.':'An enormous old tree grows in the middle of a construction site. Borda the dwarf must build a stone bridge through this spot. Liel the elf refuses to let the tree be cut down: it is older than both their families.',
'Вместо спора Борда уже третий день пытается спроектировать мост, который раздваивается вокруг ствола, а потом снова соединяется. Лиэль в ответ выращивает корни так, чтобы они не давили на фундамент.':'Instead of arguing, Borda has spent three days designing a bridge that splits around the trunk and joins again on the other side. Liel responds by guiding the roots so they do not press against the foundation.',
'Оба устали, оба упрямы и оба явно хотят, чтобы решение получилось.':'Both are tired, both are stubborn, and both clearly want the solution to work.',
'Помочь Борде закончить каменную часть':'Help Borda finish the stonework',
'Помочь Лиэлю укрепить дерево магией':'Help Liel strengthen the tree with magic',
'Поручить Ладье соединить обе конструкции в единый проект':'Ask the Rook to merge both structures into a single design',
'{rookName} рассматривает чертёж и корни. «Они уже сделали половину работы друг за друга. Осталось заставить камень и дерево учитывать рост».':'{rookName} studies the plans and the roots. “They have already done half the work for each other. Now the stone and the tree simply need to account for growth.”',
'Предложить срубить дерево и закончить быстрее':'Suggest cutting down the tree to finish faster',
'Оставить их работать':'Leave them to their work',

'Орк читает эльфийскую поэзию':'An Orc Reads Elven Poetry',
'У костра орк Гром читает вслух эльфийское стихотворение. Очень громко. Каждую строку он сопровождает ударом кулака по колену, чтобы «ритм не убегал».':'By the fire, Grom the orc reads an elven poem aloud. Very loudly. He punctuates every line by slamming a fist against his knee so “the rhythm does not escape.”',
'Поэтесса Элиан сидит напротив и закрывает лицо ладонями. Это её стихотворение. Гром его обожает. Просто он уверен, что любовная баллада о тихом озере — это военная песня о засаде.':'The poet Elian sits opposite him with her face in her hands. It is her poem. Grom adores it. He is merely convinced that a love ballad about a quiet lake is a war song about an ambush.',
'«Смотри: “луна дрожит в воде” — разведчик боится! Великолепно!»':'“Look: ‘the moon trembles in the water’ — the scout is afraid! Magnificent!”',
'Король слушает ещё одну строфу. «Не уверен, что автор потерял смысл. Возможно, он просто приобрёл вторую жизнь».':'The King listens to another stanza. “I am not sure the author lost the meaning. Perhaps it simply gained a second life.”',
'Объяснить Грому настоящий смысл стихотворения':'Explain the poem’s true meaning to Grom',
'Убедить Элиан позволить новой трактовке жить':'Convince Elian to let the new interpretation live',
'Предложить им вместе написать боевую песню':'Suggest they write a battle song together',
'Продать копии “оркской версии” в лагере':'Sell copies of the “orc version” around camp',
'Просто послушать':'Simply listen',

'Нежить пришла за пенсией':'The Undead Came for a Pension',
'Скелет Йосс стоит у городской казны с военным удостоверением. Он прослужил двадцать лет, погиб на войне, поднялся как нежить ещё через сорок и теперь требует пенсию за весь период.':'The skeleton Yoss stands at the city treasury holding military papers. He served for twenty years, died in the war, rose as undead forty years later, and now demands a pension for the entire period.',
'Казначей утверждает, что выплаты прекращаются со смертью. Йосс указывает на формулировку: «до конца жизни». «Жизнь закончилась. Служба государству — нет. А теперь я снова хожу».':'The treasurer insists payments end at death. Yoss points to the wording: “until the end of life.” “Life ended. Service to the state did not. And now I walk again.”',
'В очереди за ним стоят ещё трое скелетов с папками.':'Three more skeletons with folders are waiting in line behind him.',
'Признать право Йосса на выплату':'Recognize Yoss’s right to payment',
'Отказать по факту смерти':'Refuse on the grounds of death',
'Поручить Ферзю установить новую категорию выплат для возвращённых ветеранов':'Ask the Queen to establish a new payment category for returned veterans',
'{queenName} листает старый устав. «Проблема не в том, имеет ли он право. Проблема в том, что закон написан для мира, где люди умирают только один раз».':'{queenName} pages through the old statute. “The problem is not whether he is entitled. The problem is that the law was written for a world where people die only once.”',
'Предложить Йоссу службу в походе вместо пенсии':'Offer Yoss service in the campaign instead of a pension',
'Передать вопрос следующему чиновнику':'Pass the matter to the next official',

'Дракон и гоблин спорят о патенте':'A Dragonkin and a Goblin Argue over a Patent',
'Харк показывает огнемёт, работающий на его собственном дыхании. Гоблин Слип показывает почти такой же огнемёт и утверждает, что придумал его раньше. Разница только в том, что устройство Слипа работает на маринованных перцах и иногда взрывается.':'Hark demonstrates a flamethrower powered by his own breath. Slip the goblin shows an almost identical device and claims he invented it first. The only difference is that Slip’s machine runs on pickled peppers and occasionally explodes.',
'Оба зарегистрировали патент в разных городах. Оба требуют запретить устройство другого.':'Both registered patents in different cities. Both demand that the other device be banned.',
'Для демонстрации Слип нажимает рычаг. Пламя вырывается не из ствола, а из задней части аппарата и поджигает его шляпу.':'For the demonstration, Slip pulls a lever. Flame bursts not from the barrel but from the back of the machine and sets his hat on fire.',
'Признать патент Харка':'Recognize Hark’s patent',
'Признать патент Слипа':'Recognize Slip’s patent',
'Поручить Ладье провести техническую экспертизу и признать устройства разными':'Ask the Rook to conduct a technical examination and classify the devices as distinct',
'{rookName} осматривает оба механизма. «Они похожи только снаружи. Один использует давление, другой — очень плохое решение».':'{rookName} examines both machines. “They only look alike from the outside. One uses pressure. The other uses a very bad idea.”',
'Купить прототип Слипа':'Buy Slip’s prototype',
'Запретить оба до нормальных испытаний':'Ban both until proper testing',

'Паук и ангел на одной крыше':'A Spider and an Angel on One Roof',
'На крыше разрушенной башни застряли тёмная эльфийка Иара и ангел Тал. Между ними сидит гигантский паук и не позволяет ни одному приблизиться к лестнице.':'A dark elf named Iara and an angel named Tal are stranded on the roof of a ruined tower. A giant spider sits between them and allows neither to approach the stairs.',
'Оба утверждают, что паук принадлежит Иаре. Точнее, Иара говорит, что это её ездовой зверь. Тал говорит, что паук сам спас его от падения и теперь, возможно, считает обоих своим выводком.':'Both say the spider belongs to Iara. More precisely, Iara says it is her mount. Tal says the spider saved him from falling and may now consider both of them part of its brood.',
'Снизу ситуация выглядит нелепо. Сверху — значительно опаснее.':'From below, the situation looks ridiculous. From above, it is considerably more dangerous.',
'Приманить паука вниз едой':'Lure the spider down with food',
'Приказать Иаре взять зверя под контроль':'Order Iara to control her beast',
'Поручить Коню разыграть “уход”, чтобы заставить паука сменить позицию':'Ask the Knight to stage a “departure” and force the spider to change position',
'{knightName} наблюдает за пауком. «Он не охраняет лестницу. Он каждый раз закрывает путь тому, кто первым пытается уйти».':'{knightName} watches the spider. “It is not guarding the stairs. It blocks whoever tries to leave first.”',
'Разрушить часть крыши и открыть новый выход':'Break part of the roof to create another exit',
'Оставить троицу разбираться':'Leave the three of them to sort it out'
});
export { EVENT_EN_V4C_03 };
