const EVENT_EN_V5_02=Object.freeze({
"Золото оставим на потом. Сначала решим, что именно вы продаёте":"We can leave the gold for later. First, let us decide what exactly you are selling",
"Клятва требует честного поединка. Значит, победить нужно так, чтобы даже проигравший не смог назвать это обманом":"The oath requires a fair duel. So we must win in a way even the loser cannot call cheating",
"Справедливую долю обычно не приходится пересчитывать четыре раза. Давайте начнём с первой цифры":"A fair share usually does not need to be recalculated four times. Let us start with the first number",
"Язык старый. Намерение — вполне современное":"The language is old. The intention is thoroughly modern",
"Нас пытаются поторопить. Значит, время сейчас на нашей стороне":"They are trying to rush us. That means time is on our side",
"Свежий. Они ещё не знают, что мы уже рядом":"Fresh. They do not know we are already close",
"Один против одного? Наконец кто-то предлагает честную глупость":"One on one? At last someone offers an honest kind of foolishness",
"Пусть идут. Только пусть идут туда, куда мы им оставим дорогу":"Let them come. Just make sure they come where we leave them a path",
"Редкий случай: легенда врёт меньше, чем продавец":"A rare case: the legend lies less than the merchant",
"Следов слишком много, чтобы выбирать самый заметный. Сначала отделим тех, кто шёл, от тех, кто хотел, чтобы его нашли":"There are too many tracks to choose the most obvious one. First we separate those who traveled from those who wanted to be found",
"Сломано не там, где шумит":"The break is not where the noise is",
"Командная руна всё ещё отдаёт приказ. Сначала выясним, кому именно она считает себя обязанной подчиняться":"The command rune is still issuing an order. First we find out whom it believes it is bound to obey",
"Голем уже разваливается. Самая опасная деталь сейчас — та, которую кто-нибудь решит вытащить первой":"The golem is already falling apart. The most dangerous part now is whichever one someone decides to pull out first",
"Читается справа налево. А предупреждение — наоборот":"It reads right to left. The warning is the other way around",
"Переход есть. Просто сейчас он об этом не знает":"The crossing exists. It just does not know it yet",
"Станки не сошли с ума одновременно. Один из них задаёт остальным неправильный ритм — найдём первый":"The machines did not all go mad at once. One of them is feeding the others the wrong rhythm—we find that one first",
"Память не разрушена. Она ходит по кругу. Нужно дать ей точку, из которой можно выйти":"The memory is not destroyed. It is looping. We need to give it a point it can leave from",
"Кто-то прошёл здесь раньше нас. И очень хотел, чтобы мы этого не заметили":"Someone passed through here before us. And very much wanted us not to notice",
"Медведя не нужно побеждать. Нужно убедить его, что дальше щита ничего интересного нет":"We do not need to defeat the bear. We need to convince it there is nothing interesting beyond the shield",
"Это не украшение. Кто-то очень хотел, чтобы сюда пришёл именно понимающий":"This is not decoration. Someone very much wanted a person who understands it to come here",
"Они будут смотреть сюда. Значит, мы пойдём там":"They will be watching here. So we will go there",
"Главное — не смотреть туда, куда можно упасть":"The important thing is not to look where you could fall",
"Там тесно. Значит, большим неприятностям тоже будет тесно":"It is cramped in there. That means big trouble will be cramped too",
"Грибы отвечают на старый ритуал. Повторим его точно и посмотрим, кого они считают гостями":"The mushrooms respond to an old ritual. We will repeat it exactly and see whom they consider guests",
"Страж маленький только издалека. Я приму первый натиск — остальные увидят, как он атакует":"The guardian only looks small from a distance. I will take the first charge so the others can see how it attacks",
"Бабочка ведёт слишком уверенно для случайного полёта. Я пойду параллельно и отмечу, где она действительно меняет маршрут":"The butterfly is flying too deliberately for chance. I will move in parallel and mark where it truly changes course",
"Это отвечает не на вопрос. Это отвечает на то, чего мы боимся услышать":"It is not answering the question. It is answering what we are afraid to hear",
"Вот эти растут к солнцу. Остальные — к теплу. Ночью это будет существенная разница":"These grow toward sunlight. The others grow toward warmth. At night, that distinction will matter",
"На клятву лучше отвечать клятвой. Но своей — чтобы никто не решил за нас, что именно мы пообещали":"An oath is best answered with an oath. But our own—so nobody decides for us what exactly we promised",
"Набор выгодный только потому, что продавец перечисляет полезное и молчит о лишнем. Сейчас посчитаем наоборот":"The bundle looks profitable only because the seller lists what is useful and stays silent about the excess. Now we count the other way around",
"Перейти можно. Сначала я превращу эту кучу в конструкцию, которая сама об этом знает":"It can be crossed. First I will turn this pile into a structure that knows it",
"Самое опасное здесь специально сделано похожим на мелочь":"The most dangerous part here has deliberately been made to look insignificant",
"Колёс четыре. Этого уже достаточно для тактики":"It has four wheels. That is already enough for tactics",
"Съедобно. Вопрос только — для кого именно. Дайте мне посмотреть, что он бросал в котёл":"Edible. The question is—for whom exactly. Let me see what he put in the cauldron",
"Теперь можно обсуждать настоящие условия":"Now we can discuss the real terms",
"Овраг удобен для тех, кто хочет смотреть сверху. Я проверю края раньше, чем мы спустимся внутрь":"The ravine favors anyone who wants the high ground. I will check the edges before we go down inside",
"Это не одна вера. Кто-то собрал обряд из чужих частей — и сделал это совсем недавно":"This is not one faith. Someone assembled this rite from borrowed pieces—and did it very recently",
"Если трое наёмников продают одну и ту же услугу, пусть сначала объяснят, почему цена у каждого считается честной":"If three mercenaries sell the same service, let them first explain why each of their prices is supposed to be fair",
"У всякой стены есть место, которое она считает своим секретом":"Every wall has a place it considers its secret",
"Главное — не жадничать на каждом шаге":"The important thing is not to get greedy at every step",
"Теперь можно слушать":"Now we can listen",
"Если бой всё-таки случится, лучше решить заранее, где он случится":"If the battle happens anyway, we should decide in advance where it happens",
"Вес отряда выдержит. Ошибку — нет":"It will hold the roster's weight. It will not hold a mistake",
"Вода сильная, но предсказуемая. Люди в панике — нет. Пойдём по моей команде":"The water is strong, but predictable. People in panic are not. We move on my command",
"Если снизу кто-то плачет, шумная лестница — худший способ представиться. Я спущусь первым":"If someone is crying below, a noisy descent is the worst way to introduce ourselves. I will go down first",
"Посвящение стёрто не временем — его меняли. Если восстановить ранний слой, станет ясно, кому была открыта ладонь":"The dedication was not worn away by time—it was altered. Restore the earlier layer and we will know whom the open palm was meant for",
"Они уже торгуются. Просто пока делают вид, что спорят о принципах":"They are already bargaining. For now, they are merely pretending to argue about principles",
"Здесь нет следов заклятия. Это хуже. Значит, условие срабатывает только после согласия":"There are no traces of a spell here. That is worse. It means the condition activates only after consent",
"Чары держатся не на вещи. Они держатся на условии":"The magic is not anchored to the thing. It is anchored to a condition",
"У башни нет двери для тех, кто ищет дверь. Зато кладка уже показала, где строители боялись собственного веса":"The tower has no door for those looking for a door. But the masonry has already shown where the builders feared its own weight",
"Вход здесь. Просто башня считает дверью не камень, а правильное намерение":"The entrance is here. The tower simply considers the correct intention, not stone, to be the door",
"Огонь погас давно. А страх здесь остался свежим":"The fire went out long ago. The fear here is still fresh",
"Путь, который сам назначает цену, обычно пытается решить за путника и направление":"A road that sets its own price is usually trying to choose the traveler's direction as well"
});export{EVENT_EN_V5_02};