const EVENT_EN_V5_09=Object.freeze({
"Слишком удобная улика. Настоящие враги редко работают так вежливо":"Too convenient a clue. Real enemies are rarely this polite",
"Я обещаю только первое":"I promise only the first",
"У них уже есть граница, торговый спор и вопрос воздушного пространства. Осталось учредить два государства":"They already have a border, a trade dispute, and an airspace issue. All that remains is to establish two states",
"Страх не мешает идти. Он просто требует больше времени на первый шаг":"Fear does not stop you from walking. It only makes the first step take longer",
"Похоже, единственная сторона без документов и есть главная причина спора":"It seems the only party without documents is the main cause of the dispute",
"Если там есть кухня, значит, продукты как-то попадают внутрь":"If there is a kitchen in there, food must be getting inside somehow",
"Можно взять не весь цветок. Для лекарства хватит части корня — если работать осторожно":"We do not need the whole flower. Part of the root will be enough for the medicine—if we work carefully",
"Если хотя бы половина истории правда, ему нужен не девятый шанс, а новая профессия":"If even half the story is true, he does not need a ninth chance. He needs a new profession",
"После восьмой чудом пережитой смерти перестаёшь спорить со словом “последняя”. Сначала уведём его отсюда":"After surviving death by miracle eight times, you stop arguing with the word “last.” First we get him out of here",
"Память хороша. Нотариальное оформление — ещё лучше":"Memory is good. Notarization is better",
"Судя по голосу, выгонять его до развязки действительно опаснее":"Judging by the voice, throwing him out before the ending really is more dangerous",
"Он исправен. Это делает спор значительно интереснее":"He is functioning correctly. That makes the dispute considerably more interesting",
"Механика исправна. Значит, проблема именно во “внутреннем решении”":"The mechanism is sound. So the problem really is the “internal decision”",
"Он признаёт все доказательства и всё равно отказывает. Очень человеческая бюрократия для машины":"It accepts all the evidence and still refuses. Very human bureaucracy for a machine",
"Механизм не теряет минуту. Он её избегает":"The mechanism is not losing a minute. It is avoiding it",
"Вопрос уже не в том, откуда он это знает. Вопрос — почему именно теперь вспомнил":"The question is no longer how it knows this. The question is why it remembered now",
"Прежде чем обсуждать право машины закончить службу, я хочу исключить сломанный узел, который говорит её голосом":"Before we discuss a machine's right to end its service, I want to rule out a broken component speaking in its voice",
"У меня впервые есть предмет, который дорожает от того, что бесполезен":"For the first time, I own something that becomes more valuable by being useless",
"Он не держит мост. Он следит за рекой":"He is not holding the bridge. He is watching the river",
"Поймать его нетрудно. Поймать его без колокола в лоб — сложнее":"Catching him is not hard. Catching him without taking a bell to the face is harder",
"Дисциплина лучше, чем у половины ополчения, которое я видел":"Better discipline than half the militia I have seen",
"Он не охраняет тело от людей. Он лежит рядом с ним":"He is not guarding the body from people. He is lying beside it",
"Они не охраняют повозку. Они ждут возвращения именно сюда":"They are not guarding the wagon. They are waiting for a return to this exact place",
"Возврат средств я понимаю. Возврат вчера потребует более сильного отдела обслуживания":"I understand refunds. Returning yesterday will require a stronger customer service department",
"Для них это уже не мусор. Пожалуй, именно так и начинаются святыни":"To them, it is no longer trash. I suppose this is how shrines begin",
"Наконец-то маршрут, где полезно демонстративно ошибаться":"Finally, a route where making obvious mistakes is useful",
"Впервые вижу стража, которого нельзя подкупить и который при этом формально прав":"For the first time, I see a guard who cannot be bribed and is technically correct",
"Броня ещё пригодна. Как недвижимость — тоже, судя по всему":"The armor is still usable. Apparently, so is the real estate",
"Главное — не выбирать. За минуту выбор опаснее цены":"The important thing is not to choose. With one minute, choice is more dangerous than price",
"Как военный объект дом слабый. Как реклама — впечатляет":"As a military position, the house is weak. As advertising, it is impressive",
"Очень редкий вид дракона. Судя по следу, сделан из сосны":"A very rare species of dragon. Judging by the footprint, made of pine",
"Я уважаю ложь, в которую вложено двадцать три названия. Но сначала посмотрим, сколько там еды":"I respect a lie with twenty-three names invested in it. But first let us see how much food there actually is",
"По крайней мере, парковаться она умеет":"At least she knows how to park",
"Если это действительно все его записи, банк удивительно легко помещается в детских руках":"If those truly are all his records, the bank fits surprisingly easily in a child's hands",
"Катапульта исправна. Сервис доставки — нет":"The catapult works. The delivery service does not",
"Восхищает, что никто не спросил самих путников, куда они едут":"Impressive that nobody asked the travelers where they are actually going",
"Я не уверен насчёт радуги. Но конструкцию он собрал отлично":"I am not sure about the rainbow. But he built the structure very well",
"Похоже, он сменил пост, но не профессию":"It seems he changed his post, but not his profession",
"Не думал, что спор о природе души закончится дробями":"I did not expect a debate about the nature of the soul to end in fractions",
"Юридически он подготовился. Практически — забыл, что клиент дышит огнём":"Legally, he prepared well. Practically, he forgot the client breathes fire",
"Они оба правы. Купец ушёл сам, а преследователь выбрал другой путь":"They are both right. The merchant left willingly, and the pursuer chose another route",
"Если продолжит, семьи объединятся хотя бы ради того, чтобы остановить его":"If he keeps going, the families will unite at least long enough to stop him",
"Он может не считать себя святым. Это никогда не мешало людям считать иначе":"He may not consider himself a saint. That has never stopped people from thinking otherwise",
"Можно спорить о длине. Главное, что она не меняется под ногами":"You can argue about the length. What matters is that it does not change under your feet",
"Он действительно самый спокойный участник этой сцены":"He really is the calmest participant in this scene",
"Я бы тоже не торопился":"I would not hurry either",
"Развести противников проще, если каждый уверен, что именно ему достался лучший берег":"Separating the opponents is easier if each is convinced they got the better bank",
"Они спорят не о цветке. Они спорят о том, кто имеет право назвать его лишним":"They are not arguing about the flower. They are arguing about who has the right to call it unnecessary",
"Метод сомнительный. Забота — нет":"The method is questionable. The care is not",
"Не исправляйте пьесу. Сначала расскажите, кто дал вам право на эту версию Короля":"Do not fix the play. First tell me who gave you the right to this version of the King",
"Они не нападают и не говорят. Просто выполняют последний маршрут — но, похоже, уже не тот":"They do not attack or speak. They are simply completing their final route—but apparently not the right one anymore",
"Он уже пережил худшую часть этой дороги. Не заставляйте его доказывать это ещё раз":"He already survived the worst part of this road. Do not make him prove it again",
"Предлагаю начать с тех, кто ещё не успел поставить кассу":"I suggest we begin with those who have not yet managed to set up a toll booth",
"Если каждый владеет дорогой только потому, что когда-то по ней прошёл, она не принадлежит никому. Значит, пусть будет общей":"If everyone owns the road merely because they once walked it, then it belongs to no one. So let it be shared"
});export{EVENT_EN_V5_09};