const EVENT_EN_V5_04=Object.freeze({
"Это не бессмертие. Это отсрочка последствий":"This is not immortality. It is a delay of consequences",
"Хорошая новость: даже бездна признаёт расторжение договора. Плохая — только если всё оформлено правильно":"Good news: even the abyss recognizes contract termination. Bad news: only if the paperwork is correct",
"Приказ можно догнать завтра. Людей под этими балками — нет":"We can catch the order tomorrow. We cannot catch the people under those beams tomorrow",
"Спор о собственности можно продолжить после того, как собственность перестанет его уносить":"The ownership dispute can continue after the property stops carrying it away",
"Он звонит на намерение солгать. Кто-то уже решил, что скажет":"It rings at the intention to lie. Someone has already decided what they are going to say",
"Он законен только потому, что никто не предполагал, что кто-то попробует такое написать":"It is legal only because nobody imagined someone would try to write such a thing",
"Если покаяние удобно, человек обычно заканчивает его раньше, чем понимает зачем начал":"When repentance is convenient, people usually finish it before they understand why they began",
"Если закон зависит от того, насколько хорош был лекарь, это уже не закон":"If the law depends on how good the healer was, it is no longer a law",
"Чудо не отменяет вины. Но наказание, которое ничего не исправляет, тоже не становится священным":"A miracle does not erase guilt. But punishment that fixes nothing does not become sacred either",
"Кристалл не охлаждает тело. Он меняет само пламя внутри":"The crystal does not cool the body. It changes the flame inside",
"Фраза была метафорой. Проблема в том, что клятва услышала её буквально":"The phrase was a metaphor. The problem is that the oath heard it literally",
"Это не голос ребёнка. Кто-то говорит через него из пещеры":"That is not a child's voice. Someone in the cave is speaking through it",
"Если его хотят проверить как воина, пусть проверяют как воина":"If they want to test him as a warrior, then let them test him as a warrior",
"Самая ценная часть этого сокровища — момент, когда кто-то наконец записал правду":"The most valuable part of this treasure is the moment someone finally wrote down the truth",
"Обряд нужен живым. Мёртвым редко требуется правильная форма прощания":"The rite is for the living. The dead rarely need the proper form of farewell",
"Если человек не может оставить пост, можно временно перенести пост туда, где ему удобно":"If a person cannot leave the post, we can temporarily move the post somewhere more convenient for them",
"Пост существует ради ворот, а не ворота ради поста. Перенесём службу туда, где она ещё имеет смысл":"The post exists for the gate, not the gate for the post. We will move the duty somewhere it still makes sense",
"Животные редко понимают закон. Зато отлично понимают, кто ведёт себя странно":"Animals rarely understand the law. They understand perfectly well who is behaving strangely",
"Если совет ждёт от тебя голос предка, начни с собственного":"If the council expects an ancestor's voice from you, begin with your own",
"Можно сохранить часть старого моста внутри нового. Не как украшение — как опору":"We can preserve part of the old bridge inside the new one. Not as decoration—as support",
"Широко — это когда спорят о смысле статьи. Здесь он просто надеется, что никто не прочитает заголовок":"Broad interpretation is when people argue over the meaning of a clause. Here he is simply hoping nobody reads the heading",
"Память и плоть — не одно и то же. Первую нужно вернуть семье. О второй можно говорить с Кеш":"Memory and flesh are not the same thing. The first should be returned to the family. The second can be discussed with Kesh",
"Он может сидеть. Просто создатель не предусмотрел, что когда-нибудь придётся объяснять зачем":"He can sit. His creator simply never expected anyone would need to explain why",
"У него не одна воля. Кто-то дал руке отдельную команду":"He does not have one will. Someone gave the hand a separate command",
"Ей не нужно приказать остановиться. Нужно доказать, что лучшая позиция уже была здесь":"She does not need to be ordered to stop. We need to prove the best position was already here",
"Не останавливайте её. Дайте направление, которое нам выгоднее":"Do not stop her. Give her a direction that benefits us more",
"Она не охраняет дом. Она выполняет последнюю просьбу ребёнка":"She is not guarding the house. She is carrying out a child's final request",
"Пусть спорят сколько угодно. Небо уже знает, который час":"Let them argue as long as they like. The sky already knows the time",
"Я могу проверить непрерывность памяти. Но не могу доказать ему непрерывность души":"I can test the continuity of memory. I cannot prove the continuity of his soul",
"Он приходит одной дорогой и уходит другой. Значит, можно договориться с его привычкой, даже если нельзя с ним самим":"He comes by one road and leaves by another. That means we can negotiate with his habit even if we cannot negotiate with him",
"Он не ворует случайно. Значит, у его тайника есть история — и порядок":"He does not steal at random. That means his cache has a history—and an order",
"Они не пасут караван. Они не дают ему войти куда-то":"They are not herding the caravan. They are preventing it from entering somewhere",
"Я ничего не делал. Это он что-то решил":"I did nothing. It decided something",
"Они молчат не потому, что боятся шума. Они боятся, что оно услышит, где они":"They are silent not because they fear noise. They fear it will hear where they are",
"Приказ, который никто не отменил, всё ещё держит солдата в строю. Даже если солдат — черепаха":"An order nobody canceled still keeps a soldier in formation. Even if the soldier is a turtle",
"Раз она уже сбежала, ловить поздно. Давайте хотя бы договоримся о времени возвращения":"If she has already escaped, it is too late to catch her. Let us at least agree on when she returns",
"Если это суд, кто-то уже подкупает присяжных фруктом":"If this is a trial, someone is already bribing the jury with fruit",
"Она питается не весельем. Она питается моментом, когда человек уже не может остановиться":"It does not feed on joy. It feeds on the moment when a person can no longer stop"
});export{EVENT_EN_V5_04};