const EVENT_EN_V5_10=Object.freeze({
"Если механизм исправен, значит, кто-то очень старательно делает его неисправным каждый день":"If the mechanism is sound, then someone is working very hard to make it unsound every day",
"Он защищал город от армии. Не думаю, что хотел защищать его от торговли следующие восемнадцать лет":"He defended the city from an army. I doubt he meant to defend it from trade for the next eighteen years",
"Ворота должны помнить войну. Но не обязаны продолжать её после всех остальных":"The gates should remember the war. They do not have to keep fighting it after everyone else stops",
"Я вижу страх, усталость и очень плохую бухгалтерию. Болезни пока не вижу":"I see fear, exhaustion, and very bad accounting. I do not see a disease yet",
"Это первый раз, когда я вижу сооружение, которое нужно победить до того, как им воспользоваться":"This is the first structure I have ever seen that must be defeated before it can be used",
"Я видел много плохих переправ. Эта хотя бы честно показывает, что строили её не ради путников":"I have seen many bad crossings. At least this one honestly shows it was not built for travelers",
"Если догоню — сначала остановлю карету. Потом пусть продолжают правосудие сколько хотят":"If I catch it, I stop the carriage first. Then they can continue administering justice as long as they like",
"Он учит их переживать поражение. Обычно эту часть военной науки начинают преподавать слишком поздно":"He is teaching them how to survive defeat. Usually that part of military science is taught far too late",
"Оно не проклято. Оно действительно просто оскорблено. Честно говоря, это хуже":"It is not cursed. It is genuinely offended. Frankly, that is worse",
"Ритм повторяется. Может, нам не нужен певец — нужен тот, кто умеет запоминать":"The rhythm repeats. Perhaps we do not need a singer—just someone who knows how to remember",
"Я могу его перехватить. Но мне очень не нравится мысль о погоне за священным почтальоном":"I can intercept him. I very much dislike the idea of chasing a sacred courier",
"Святость, возможно, переживёт рубахи. А вот хранитель — не уверен":"The sanctity may survive the shirts. I am less certain about the keeper",
"Я понимаю традицию. Я не понимаю, почему мишени поставили рядом с людьми":"I understand the tradition. I do not understand why the targets were placed next to people",
"Возможно, последнего шага никогда не было одного. Две группы расходятся намеренно":"Perhaps there was never a single final step. The two groups separate deliberately",
"Если это действительно еда перед последней атакой, я хотел бы уточнить, почему все просят добавки":"If this truly is food before the final attack, I would like to know why everyone is asking for seconds",
"Силу можно измерить камнем. Принадлежность к семье — вряд ли":"Strength can be measured with a stone. Belonging to a family, probably not",
"К вечеру у них либо кончатся деньги, либо останется слишком много новых шрамов":"By evening they will either run out of money or end up with far too many new scars",
"Не думаю, что его можно убедить копьём. Попробую договориться как с коллегой":"I do not think a spear will persuade him. I will try speaking to him as a colleague",
"Ошибки тут нет. Здесь целая новая внешняя политика":"There is no mistake here. There is an entire new foreign policy",
"Полезное пророчество. Особенно если когда-нибудь узнаем, к какому вопросу оно относилось":"A useful prophecy. Especially if we ever learn which question it answered",
"Кажется, один из избирателей всё-таки хочет пересчитать голоса":"It seems one of the voters does want a recount after all",
"Он не проклят. Он просто пятьдесят лет ходит не по адресу":"He is not cursed. He has simply been going to the wrong address for fifty years",
"Кто-то не просто вошёл без ключа. Он ещё и хотел, чтобы подозрение выглядело скучно":"Someone did not merely enter without a key. They also wanted the suspicion to look boring",
"Бессмертие тоже держится на вещах, которые можно потерять. Откроем сундук осторожно":"Immortality also depends on things that can be lost. We will open the chest carefully",
"Предлагаю сначала считать живых. Бумаги можно похоронить позже":"I suggest we count the living first. The paperwork can be buried later",
"Голосов несколько. И они не поют для того, чтобы нас напугать":"There are several voices. And they are not singing to frighten us",
"Я умею работать с упрямыми ездовыми животными. Но обычно они не ядовитые и не участвуют в бракоразводном процессе":"I know how to work with stubborn mounts. Usually they are not venomous and are not part of divorce proceedings",
"Редкий случай, когда мне хочется, чтобы трудовой спор длился как можно дольше":"A rare case where I hope the labor dispute lasts as long as possible",
"Неприятная правда перестаёт быть услугой в тот момент, когда продавец скрывает, что именно продаёт":"An unpleasant truth stops being a service the moment the seller hides what exactly is being sold",
"Они спорят не о том, чья она дочь. Они спорят о том, какой договор признать первым":"They are not arguing over whose daughter she is. They are arguing over which contract should be recognized first",
"Хорошая новость: убийца ещё не напал. Плохая: мы уже минуту стоим на очень удобном месте":"Good news: the killer has not attacked yet. Bad news: we have been standing in a very convenient spot for a full minute",
"Кажется, я поняла грамматику":"I think I understand the grammar",
"Стена держится. Что находится за ней — совсем другой вопрос":"The wall is holding. What lies behind it is a completely different question",
"Если арка рухнет, подпись всё равно окажется на полу. Только вместе с кварталом":"If the arch collapses, the signature will end up on the floor anyway. Along with the whole district",
"Победителя можно будет объявить после того, как мы перестанем тонуть":"We can declare a winner after we stop drowning",
"Статую не поворачивали. Но кто-то очень недавно был у её руки":"The statue was not turned. But someone was near its hand very recently",
"Я впервые вижу налоговую систему, которую можно обмануть ножницами":"This is the first tax system I have seen that can be cheated with scissors",
"Ещё один спор — и данные получат уже о второй стадии обрушения":"One more argument and they will collect data on the second stage of the collapse",
"Формулировка безупречна. Именно поэтому он так зол":"The wording is flawless. That is exactly why he is so angry",
"Первое правило сна — не относиться к нему как к осаде крепости":"The first rule of sleep is not to treat it like a siege",
"Кажется, мать уже ищет. Я бы предпочёл, чтобы она нашла ребёнка раньше нас":"It seems the mother is already searching. I would prefer she find the child before she finds us",
"Он уже выбрал, кому доверяет. Возможно, разумные существа тоже иногда могут это уважать":"He has already chosen whom he trusts. Perhaps intelligent beings can occasionally respect that too",
"Не думала, что спасение души может зависеть от хорошего почерка. Но спорить с результатом не стану":"I did not think salvation of a soul could depend on good handwriting. I will not argue with the result",
"Обычно я беспокоюсь, когда отражение живёт своей жизнью. Здесь меня больше беспокоит оригинал":"Usually I worry when a reflection has a life of its own. Here I am more worried about the original",
"Если небеса действительно выбрали тебя, они только что подали официальную жалобу":"If heaven truly chose you, it has just filed an official complaint",
"Не обещаю вернуть каждому его чудо. Но хотя бы перестанем советовать детям ремонтировать крепости":"I cannot promise to return everyone's miracle. But at least we can stop advising children to repair fortresses",
"Значит, нам нужна не ложь. Нам нужен вопрос, на который они забудут получить ответ":"Then we do not need a lie. We need a question they forget to get an answer to",
"Если памятник рассказывает другую биографию, право последней правки должно быть хотя бы у живого оригинала":"If the monument tells a different biography, the living original should at least have the right to the final edit",
"Она не играет быстрее него. Она просто знает, что он сделает за два хода до того, как он сам решит":"She does not play faster than him. She simply knows what he will do two moves before he decides",
"Прощение не обязано означать отсутствие последствий. Иначе оно слишком удобно только одной стороне":"Forgiveness does not have to mean absence of consequences. Otherwise it is far too convenient for only one side",
"Проблема не в огне. Проблема в том, что воздух выходит не туда":"The problem is not the fire. The problem is that the air is leaving in the wrong direction",
"Если первое впечатление стало обрядом, давайте хотя бы закончим обряд правильно":"If a first impression has become a ritual, let us at least finish the ritual properly"
});export{EVENT_EN_V5_10};