const EVENT_EN_V4C_01 = Object.freeze({
'Яйцо просит вернуть его обратно':'The Egg Wants to Go Back',
'Таар несёт огромное драконье яйцо в плетёной люльке. Изнутри время от времени доносится стук. На третий такой стук из скорлупы ясно произносят: «Назад».':'Taar carries an enormous dragon egg in a woven cradle. From time to time, something knocks from within. On the third knock, a clear word comes through the shell: “Back.”',
'Хранитель бледнеет. Яйца его рода не говорят до вылупления. Таар забрал кладку из пещеры, где началось землетрясение, и считает, что спас будущего ребёнка. Яйцо, похоже, считает иначе.':'The keeper goes pale. Eggs of his kind do not speak before hatching. Taar took the clutch from a cave when an earthquake began and believes he saved the unborn child. The egg seems to disagree.',
'Когда отряд поворачивает в сторону старой пещеры, скорлупа заметно теплеет.':'When the roster turns toward the old cave, the shell grows noticeably warmer.',
'Вернуть яйцо в пещеру':'Return the egg to the cave',
'Унести яйцо как можно дальше':'Carry the egg as far away as possible',
'Поручить Слону определить источник голоса':'Ask the Bishop to identify the source of the voice',
'{bishopName} кладёт ладонь на люльку. «Это не голос ребёнка. Кто-то говорит через него из пещеры».':'{bishopName} lays a hand on the cradle. “That is not the child’s voice. Someone in the cave is speaking through it.”',
'Разбить скорлупу раньше срока':'Break the shell before its time',
'Отказаться участвовать':'Refuse to get involved',

'Рыцарь без огня':'The Knight Without Fire',
'Воин Керр тренируется у дороги, снова и снова пытаясь выдохнуть пламя. Каждый раз получается только дым. Оруженосец Нима делает вид, что не замечает.':'Kerr trains by the roadside, trying again and again to breathe flame. Every attempt produces only smoke. His squire, Nima, pretends not to notice.',
'Завтра Керр должен пройти обряд вступления в гвардию. В его роду способность к огненному дыханию считается доказательством силы крови. Сам Керр отлично владеет копьём и уже спасал людей в бою, но уверен, что без пламени всё это «не считается».':'Tomorrow Kerr must undergo the rite of entry into the guard. In his bloodline, fire breath is taken as proof of a strong lineage. Kerr is an excellent spearman and has already saved lives in battle, yet he is convinced none of it “counts” without flame.',
'Нима тихо говорит Королю: «Он боится не провала. Он боится увидеть лицо отца».':'Nima quietly tells the King, “He is not afraid of failing. He is afraid of seeing his father’s face.”',
'Помочь Керру подготовить дыхание алхимическими средствами':'Help Kerr prepare his breath with alchemical means',
'Уговорить его отказаться от обряда':'Persuade him to abandon the rite',
'Поручить Коню устроить испытание мастерства, которое нельзя выиграть одним пламенем':'Ask the Knight to arrange a test of skill that fire alone cannot win',
'{knightName} смотрит на очередную попытку. «Если его хотят проверить как воина, пусть проверяют как воина».':'{knightName} watches another attempt. “If they want to test him as a warrior, then let them test him as a warrior.”',
'Предложить Керру присоединиться к походу и доказать себя делом':'Invite Kerr to join the campaign and prove himself through deeds',
'Не вмешиваться':'Do not interfere',

'Сокровище, которое никто не хочет':'The Treasure Nobody Wants',
'В маленькой крепости драконорождённые охраняют сундук уже четыреста лет. В летописях он назван «Сокровищем Пепельного Владыки». За него погибли три вора и один слишком любопытный историк.':'In a small fortress, the dragonkin have guarded a chest for four hundred years. The chronicles call it “The Treasure of the Ashen Lord.” Three thieves and one overly curious historian have died for it.',
'Сегодня Сарра наконец вскрыла печати. Внутри — медные монеты, давно вышедшие из обращения, и записка: «На пиво тем, кто дочитал до конца».':'Today Sarra finally broke the seals. Inside are copper coins long out of circulation and a note: “For ale, to whoever read this far.”',
'Никто не смеётся. Слишком много поколений строили вокруг сундука карьеру, престиж и систему охраны.':'Nobody laughs. Too many generations built careers, prestige, and an entire security system around the chest.',
'Король берёт одну медную монету. «Есть наследства, которые становятся ценнее только потому, что никто не решается признать их бесполезными».':'The King picks up a copper coin. “Some inheritances become valuable only because no one dares admit they are worthless.”',
'Предложить устроить на монеты большой общий пир':'Suggest spending the coins on a great communal feast',
'Купить весь сундук как историческую редкость':'Buy the entire chest as a historical curiosity',
'Объявить записку частью сокровища и выставить её на аукцион':'Declare the note part of the treasure and auction it',
'Сказать правду: охранять здесь больше нечего':'Tell the truth: there is nothing left here to guard',
'Оставить крепость решать, как пережить разочарование':'Leave the fortress to decide how to live with the disappointment',

'Спор о последней чешуе':'The Dispute over the Last Scale',
'Варк и Тесса держат над урной одну золотую чешую. По обычаю её надо положить в огонь вместе с прахом матери. Но это последняя чешуя старого рода, и Варк хочет сохранить её как реликвию.':'Vark and Tessa hold a single golden scale above an urn. Custom says it must be placed in the fire with their mother’s ashes. But it is the last scale of an old bloodline, and Vark wants to preserve it as a relic.',
'Тесса считает, что оставить чешую — значит удержать мать среди живых против её воли. Варк отвечает, что сжечь — значит добровольно стереть последнее физическое доказательство её существования.':'Tessa believes keeping the scale would hold their mother among the living against her will. Vark replies that burning it would willingly erase the last physical proof that she ever existed.',
'Огонь уже разожжён. Они спорят столько, что угли начинают гаснуть.':'The fire is already lit. They argue so long that the embers begin to die.',
'Поддержать Тессу и завершить погребение':'Support Tessa and complete the funeral',
'Поддержать Варка и сохранить чешую':'Support Vark and preserve the scale',
'Поручить Слону провести обряд с символической заменой чешуи':'Ask the Bishop to perform the rite with a symbolic replacement for the scale',
'{bishopName} смотрит на урну. «Обряд нужен живым. Мёртвым редко требуется правильная форма прощания».':'{bishopName} looks at the urn. “Rituals are for the living. The dead rarely require the proper form of farewell.”',
'Предложить разделить чешую пополам':'Suggest splitting the scale in two',

'Носорог у ворот':'The Rhino at the Gate',
'У ворот зверолюдского поселения стоит носорог Грум в полном доспехе. Он не пропускает никого. Причина не во врагах: писарь Фек потерял печать, которой подтверждается окончание смены.':'At the gate of a beastfolk settlement stands Grum, a rhinoceros in full armor. He lets no one pass. The problem is not an enemy: the clerk Fek lost the seal that confirms the end of a guard shift.',
'Грум дежурит уже тридцать шесть часов. Устав гласит: «Страж покидает пост после отметки сменщика». Сменщик пришёл, расписался, поел и ушёл спать. Печати нет.':'Grum has been on duty for thirty-six hours. Regulations state: “A guard leaves his post after the replacement is certified.” The replacement came, signed in, ate, and went to sleep. The seal is missing.',
'Грум слишком дисциплинирован, чтобы нарушить правило, и слишком устал, чтобы продолжать понимать мир.':'Grum is too disciplined to break the rule and too exhausted to keep making sense of the world.',
'Помочь искать печать Фека':'Help search for Fek’s seal',
'Приказать Груму оставить пост от имени Короля':'Order Grum to leave his post in the King’s name',
'Поручить Ладье официально перенести караульный знак к казарме':'Ask the Rook to officially relocate the guard marker to the barracks',
'{rookName} смотрит на ворота. «Если человек не может оставить пост, можно временно перенести пост туда, где ему удобно».':'{rookName} looks at the gate. “If a man cannot leave his post, the post can temporarily be moved somewhere more convenient.”',
'Предложить Феку новую печать за плату':'Offer Fek a new seal for a fee',
'Ждать, пока вопрос решится сам':'Wait for the matter to resolve itself',

'Кошка знает, кто вор':'The Cat Knows the Thief',
'У травницы Мары украли мешочек редкого семени. В лавке в момент кражи находились трое: купец-барсук, курьер-заяц и чиновник-ворон. Все позволяют себя обыскать. Семени ни у кого нет.':'A pouch of rare seeds was stolen from Mara the herbalist. Three customers were in the shop at the time: a badger merchant, a hare courier, and a raven official. All allow themselves to be searched. None has the seeds.',
'Мара заявляет, что знает вора по запаху, но отказывается назвать. «Хочу понять, сознается ли сам».':'Mara says she knows the thief by scent, but refuses to name them. “I want to see whether they confess on their own.”',
'Пока она говорит, маленькая домашняя кошка на прилавке медленно подходит к чиновнику и садится ему на сапог. Ворон начинает потеть, хотя у него перья.':'As she speaks, a small house cat on the counter slowly walks over to the official and sits on his boot. The raven begins to sweat despite having feathers.',
'Обвинить чиновника сразу':'Accuse the official immediately',
'Проверить лавку и путь каждого посетителя':'Search the shop and retrace every visitor’s movements',
'Поручить Пешке проследить за реакциями подозреваемых, пока Мара задаёт вопросы':'Ask the Pawn to watch the suspects’ reactions while Mara questions them',
'{pawnName} приседает рядом с кошкой. «Животные редко понимают закон. Зато отлично понимают, кто ведёт себя странно».':'{pawnName} crouches beside the cat. “Animals rarely understand the law. They are very good at noticing who behaves strangely.”',
'Купить потерю Мары и закрыть вопрос':'Compensate Mara for the loss and close the matter',
'Не участвовать':'Stay out of it',

'Лев, который не рычит':'The Lion Who Cannot Roar',
'Молодой лев Рах должен сегодня впервые выступить перед советом прайда. В его семье принято начинать речь громким рыком. Рах физически не может рычать: после детской болезни голос остался тихим и хриплым.':'The young lion Rah must address the pride council for the first time today. In his family, speeches traditionally begin with a thunderous roar. Rah physically cannot roar: a childhood illness left his voice quiet and hoarse.',
'Мать Саара предлагает нанять другого льва, который рыкнет за занавесом. Рах отказывается. «Если им нужен звук, пусть выберут барабан».':'His mother Saara suggests hiring another lion to roar behind a curtain. Rah refuses. “If they want noise, let them choose a drum.”',
'Совет уже собирается. Рах просит Короля не помощи, а совета: стоит ли выходить, зная, что половина зала засмеётся до первого слова.':'The council is already gathering. Rah asks the King not for help but for advice: should he go out there knowing half the hall will laugh before his first word?',
'Король отвечает не сразу. «Иногда приходится говорить тише именно потому, что все ждут от тебя громкости».':'The King does not answer at once. “Sometimes you must speak more quietly precisely because everyone expects you to be loud.”',
'Убедить Раха выступить без подмены':'Convince Rah to speak without a substitute',
'Согласиться на трюк с чужим рыком':'Agree to the trick with another lion’s roar',
'Предложить Раху начать речь вопросом вместо рыка':'Suggest Rah begin his speech with a question instead of a roar',
'Пригласить его выступить перед отрядом как тренировку':'Invite him to practice by speaking before the roster',

'Слон помнит мост':'The Elephant Remembers the Bridge',
'Строители собираются снести древний мост и возвести новый. Старый слон Хадар лёг поперёк дороги и не позволяет начать работы.':'Builders are preparing to demolish an ancient bridge and build a new one. The old elephant Hadar lies across the road and refuses to let the work begin.',
'Когда он был ребёнком, этот мост обрушился во время наводнения. Его мать вытолкнула Хадара на берег и погибла. Позже мост восстановили из тех же камней. Для всех остальных это просто старая конструкция. Для Хадара — последнее место, которое он помнит вместе с ней.':'When he was a child, this bridge collapsed during a flood. His mother pushed Hadar to safety and died. Later the bridge was rebuilt from the same stones. To everyone else it is merely an old structure. To Hadar it is the last place he remembers sharing with her.',
'Инженеры правы: следующую большую воду мост не выдержит.':'The engineers are right: the bridge will not survive the next great flood.',
'Поддержать снос ради безопасности':'Support demolition for safety',
'Остановить работы и оставить мост как есть':'Stop the work and leave the bridge as it is',
'Поручить Ладье встроить старые камни в новую конструкцию':'Ask the Rook to incorporate the old stones into the new structure',
'{rookName} осматривает опоры. «Можно сохранить часть старого моста внутри нового. Не как украшение — как опору».':'{rookName} examines the supports. “Part of the old bridge can remain inside the new one. Not as decoration — as a foundation.”',
'Предложить Хадару выбрать один камень на память':'Suggest Hadar choose one stone as a keepsake',

'Лисий налог':'The Fox Tax',
'Лис Рен поставил у тропы стол и собирает «налог на неожиданное появление королевского отряда». Тариф — пять золотых с каждого, кто увидел Короля и не был морально подготовлен.':'Ren the fox has set up a table by the trail and is collecting a “tax on the unexpected appearance of the royal roster.” The tariff is five gold from anyone who saw the King without being emotionally prepared.',
'На вопрос о правовой основе Рен показывает свиток. В нём действительно есть королевская печать. Текст, однако, посвящён налогам на мосты и ни слова не говорит об эмоциональной готовности населения.':'When asked for the legal basis, Ren produces a scroll. It really does bear a royal seal. The text, however, concerns bridge taxes and says nothing about the population’s emotional preparedness.',
'«Я трактую закон широко», — объясняет Рен. Очередь из путников уже заплатила.':'“I interpret the law broadly,” Ren explains. A line of travellers has already paid.',
'Конфисковать собранное как незаконный сбор':'Confiscate the proceeds as an illegal levy',
'Потребовать Рена вернуть деньги путникам':'Demand that Ren return the travellers’ money',
'Поручить Ферзю официально оштрафовать Рена по настоящей статье':'Ask the Queen to formally fine Ren under an actual statute',
'{queenName} берёт свиток. «Широко — это когда спорят о смысле статьи. Здесь он просто надеется, что никто не прочитает заголовок».':'{queenName} takes the scroll. “Broad interpretation is when people argue over a statute’s meaning. Here he is simply hoping nobody reads the heading.”',
'Взять долю и разрешить работать дальше':'Take a share and let him continue',
'Уехать':'Ride away',

'Ночная трапеза гиены':'The Hyena’s Midnight Meal',
'Ночью у края лагеря появляется гиена Кеш. Она не нападает. Просто ждёт и смотрит на тело неизвестного человека, найденное отрядом у дороги.':'At night, the hyena Kesh appears at the edge of camp. She does not attack. She simply waits and watches the body of an unknown human the roster found by the road.',
'Кеш объясняет, что её народ не считает поедание мёртвых осквернением. Наоборот: «Лучше стать силой живого, чем пищей червей». Но у погибшего есть медальон и след кольца на пальце. Где-то его, возможно, ищет семья.':'Kesh explains that her people do not consider eating the dead a desecration. Quite the opposite: “Better to become the strength of the living than food for worms.” But the dead man wears a medallion and the mark of a ring remains on his finger. Somewhere, a family may be looking for him.',
'Гиена не торопит решение. «До рассвета я подожду. После рассвета запах привлечёт тех, кто спрашивать не будет».':'The hyena does not rush the decision. “I will wait until dawn. After dawn the smell will attract those who will not ask.”',
'Похоронить тело по человеческому обычаю':'Bury the body according to human custom',
'Позволить Кеш совершить обряд своего народа':'Allow Kesh to perform her people’s rite',
'Сохранить медальон и разрешить Кеш забрать тело':'Keep the medallion and allow Kesh to take the body',
'Оставить тело на месте и уйти':'Leave the body where it lies and depart',
'Атаковать Кеш как падальщика':'Attack Kesh as a scavenger',

'Голем требует перерыв':'The Golem Demands a Break',
'Грузовой голем №18 стоит посреди дороги и держит над головой огромный каменный блок. Он отказывается сделать ещё шаг.':'Cargo golem No. 18 stands in the middle of the road holding an enormous stone block above its head. It refuses to take another step.',
'На груди мелом написано: `РАБОТАЮ 63 ГОДА. ПЕРЕРЫВ: 0`. Мастер Коль утверждает, что надпись появилась сама утром. В инструкции к голему нет понятия отдыха, но есть пункт: «При перегреве прекратить эксплуатацию до охлаждения ядра».':'Chalked across its chest are the words: `WORKED 63 YEARS. BREAKS: 0`. Master Kol claims the message appeared by itself this morning. The golem’s manual contains no concept of rest, but it does say: “If overheated, cease operation until the core cools.”',
'№18 не перегрет. Он просто повторяет: «ХОЧУ СЕСТЬ».':'No. 18 is not overheated. It simply repeats: “I WANT TO SIT.”',
'Разрешить голему оставить груз и отдыхать':'Allow the golem to put down the load and rest',
'Приказать продолжить работу':'Order it to continue working',
'Поручить Ладье перенастроить рабочий цикл с обязательными паузами':'Ask the Rook to reconfigure the work cycle with mandatory breaks',
'{rookName} осматривает шарниры. «Он может сидеть. Просто создатель не предусмотрел, что когда-нибудь придётся объяснять зачем».':'{rookName} examines the joints. “It can sit. Its creator simply never expected anyone would need to explain why.”',
'Выкупить №18 у мастера':'Buy No. 18 from its master',
'Обойти блок по обочине':'Go around the block along the roadside',

'Автоматон лжёт':'The Automaton Lies',
'Автоматон С-4 обвиняется в краже. Он утверждает: «Я НЕ БРАЛ КЛЮЧ». Дознаватель Лем уверен, что конструкты не способны лгать, поэтому дело почти закрыто.':'Automaton C-4 is accused of theft. It insists: “I DID NOT TAKE THE KEY.” Investigator Lem is certain constructs cannot lie, so the case seems almost closed.',
'Проблема в том, что ключ нашли внутри корпуса С-4.':'The problem is that the key was found inside C-4’s body.',
'Когда Король спрашивает, как он туда попал, автоматон отвечает: «Я НЕ БРАЛ КЛЮЧ». И после паузы добавляет: «КЛЮЧ ВЗЯЛА МОЯ ЛЕВАЯ РУКА. Я ЕЁ НЕ КОНТРОЛИРОВАЛ».':'When the King asks how it got there, the automaton replies: “I DID NOT TAKE THE KEY.” After a pause it adds: “MY LEFT HAND TOOK THE KEY. I DID NOT CONTROL IT.”',
'Левая рука в этот момент медленно прячется за спину.':'At that moment, the left hand slowly hides behind its back.',
'Признать С-4 виновным как единое существо':'Find C-4 guilty as a single being',
'Снять левую руку и проверить её память':'Remove the left arm and inspect its memory',
'Поручить Слону восстановить цепочку команд':'Ask the Bishop to reconstruct the command chain',
'{bishopName} смотрит на разъёмы плеча. «У него не одна воля. Кто-то дал руке отдельную команду».':'{bishopName} studies the shoulder connectors. “It does not have a single will. Someone gave the arm a separate command.”',
'Купить С-4 как “дефектный” конструкт':'Buy C-4 as a “defective” construct',

'Башня переехала':'The Tower Moved Away',
'На карте здесь должен быть каменный дозорный пост. На месте остался ровный квадрат фундамента. Следы огромных каменных ног уходят на север.':'The map says a stone watchtower should stand here. Only a neat square foundation remains. Tracks from enormous stone legs lead north.',
'Архитектор Бек догоняет отряд и сообщает, что башня «самовольно сменила обзорную позицию». Она была построена как полуразумный оборонительный конструкт и получила приказ искать лучшую точку для наблюдения. Видимо, спустя пятьдесят лет нашла.':'Architect Bek catches up with the roster and reports that the tower has “changed observation positions without authorization.” It was built as a semi-sentient defensive construct and ordered to seek the best vantage point. Apparently, after fifty years, it found one.',
'Из-за холма доносится грохот. Башня шагает прямо к деревне, потому что там действительно отличный обзор.':'A rumble comes from beyond the hill. The tower is walking straight toward a village because the view there really is excellent.',
'Перехватить башню и заблокировать ноги':'Intercept the tower and lock its legs',
'Эвакуировать деревню и позволить башне встать там, где она решила':'Evacuate the village and let the tower stand where it chose',
'Поручить Ладье восстановить сигнальные ориентиры старого поста':'Ask the Rook to restore the old post’s signal markers',
'{rookName} смотрит на старый фундамент. «Ей не нужно приказать остановиться. Нужно доказать, что лучшая позиция уже была здесь».':'{rookName} looks at the old foundation. “It does not need to be ordered to stop. It needs proof that the best position was already here.”',
'Попытаться перенаправить башню на вражескую позицию':'Try to redirect the tower toward an enemy position',

'Кукла с последним приказом':'The Doll with the Final Order',
'Небольшая деревянная кукла стоит перед сгоревшим домом и не пускает никого внутрь. В одной руке игрушечное копьё, в другой — обугленная лента.':'A small wooden doll stands before a burned house and lets no one enter. It holds a toy spear in one hand and a charred ribbon in the other.',
'Она повторяет: «ХОЗЯЙКА СПИТ. НЕ ШУМЕТЬ». Дом сгорел много лет назад. За стеной давно нет ни кровати, ни хозяйки.':'It repeats: “MISTRESS SLEEPING. DO NOT MAKE NOISE.” The house burned many years ago. There has long been neither bed nor mistress behind the wall.',
'Если попытаться пройти, Ло становится в боевую стойку. Копьё игрушечное, но руны на теле — нет.':'If anyone tries to pass, Lo assumes a fighting stance. The spear is a toy. The runes on its body are not.',
'Оставить Ло на посту':'Leave Lo at its post',
'Попытаться объяснить, что хозяйка не спит':'Try to explain that its mistress is not sleeping',
'Поручить Пешке поговорить с Ло как с живым стражем, а не механизмом':'Ask the Pawn to speak to Lo as a living guard rather than a machine',
'{pawnName} присаживается перед куклой на корточки. «Она не охраняет дом. Она выполняет последнюю просьбу ребёнка».':'{pawnName} crouches in front of the doll. “It is not guarding the house. It is carrying out a child’s final request.”',
'Снять ценные руны силой':'Take the valuable runes by force',
'Обыскать дом, не трогая куклу':'Search the house without touching the doll'
});
export { EVENT_EN_V4C_01 };
