const EVENT_EN_V5_08=Object.freeze({
"Вы хотите решить бухгалтерскую ошибку похоронами живого человека?":"You want to solve an accounting error by burying a living person?",
"Повозку можно поднять. А вот решить, кому верить, будет сложнее":"The wagon can be lifted. Deciding whom to believe will be harder",
"Сначала пусть невеста скажет “да”. Потом уже можно спорить, перед каким алтарём это записывать":"Let the bride say “yes” first. Then we can argue about which altar should record it",
"Если люди начинают шептать ругательства в унисон, закон уже не работает":"When people start whispering curses in unison, the law has already stopped working",
"Если это подлинник, покойный король был гораздо интереснее, чем пишут хроники":"If this is authentic, the late king was far more interesting than the chronicles claim",
"Стены не прокляты. Кто-то заставил их говорить":"The walls are not cursed. Someone made them speak",
"Он ещё не умер. Просто перестал стоять":"He is not dead yet. He simply stopped standing",
"Он не убегает от охотников. Он водит их туда, куда хочет":"He is not fleeing the hunters. He is leading them where he wants them to go",
"Кто бы ни ответил, он ждёт именно следующего звука":"Whoever answers, it is waiting specifically for the next sound",
"У неё сильная линия защиты: полное отсутствие уважения к процессу":"She has a strong defense: complete lack of respect for the proceedings",
"Планировка меняется. Несущие стены — нет":"The layout changes. The load-bearing walls do not",
"Они не пишут заново. Они пытаются закончить одно и то же предложение":"They are not rewriting it. They are trying to finish the same sentence",
"Проиграть убедительно иногда труднее, чем победить":"Losing convincingly can sometimes be harder than winning",
"Если они начнут бой, первым погибнет ужин. Это может оказаться худшим исходом для всех":"If they start fighting, dinner will be the first casualty. That may be the worst outcome for everyone",
"Проклятия здесь нет. Но тот, кто шил золотую кайму, действительно очень хотел, чтобы знаменосца было видно издалека":"There is no curse here. But whoever stitched the golden trim really wanted the standard-bearer to be visible from far away",
"Если спор идёт о кайме, значит, само знамя ещё признают все. Сохраним то, что осталось общим":"If the dispute is about the trim, then everyone still recognizes the banner itself. Let us preserve what remains shared",
"Они идут по дороге и одновременно пытаются играть. Догнать будет несложно":"They are walking the road while trying to play at the same time. Catching them will not be difficult",
"Любопытный случай: обе стороны требуют освободить друг друга от одного человека":"Curious. Both sides are demanding to be freed from the same person",
"Иногда клетка становится привычнее дороги. Это не значит, что человеку больше некуда идти":"Sometimes a cage becomes more familiar than the road. That does not mean a person has nowhere else to go",
"Дерево мягкое. Страж — нет":"The wood is soft. The guardian is not",
"Имя убрали намеренно. Камень помнит резец":"The name was removed deliberately. The stone remembers the chisel",
"Они не прокляты играть. Они ждут окончания церемонии, которой никто не провёл":"They are not cursed to keep playing. They are waiting for the end of a ceremony nobody performed",
"Редкий документ: автор присутствует и всё равно не может объяснить, что имел в виду":"A rare document: the author is present and still cannot explain what he meant",
"Внутри восемь этажей. Сто шагов набираются слишком легко":"There are eight floors inside. A hundred steps accumulate far too easily",
"Право на символ можно признать и без необходимости проверять, на чём он будет держаться":"The right to the symbol can be recognized without testing what it will be mounted on",
"Мне очень не нравится, что он уточнил направление":"I very much dislike that he specified the direction",
"В документе всё безупречно. Кроме пункта, где дорога внезапно объявлена собственностью паука":"Everything in the document is flawless except the clause where the road suddenly becomes the spider's property",
"Самая опасная часть здесь не убийство. Пункт о толковании слова “свидетель”":"The most dangerous part here is not the murder. It is the clause defining the word “witness”",
"Камень настоящий. Следов кладки нет. Кто-то очень аккуратно нарушает правила строительства":"The stone is real. There are no traces of masonry. Someone is violating the rules of construction very carefully",
"Удивительно. Здесь честность действительно ухудшает его положение":"Remarkable. Here honesty genuinely makes his position worse",
"Он больше не проверяет ложь. Он подсказывает её":"It is no longer detecting lies. It is suggesting them",
"Они не враждуют. Оба боятся моста":"They are not enemies. Both of them are afraid of the bridge",
"Он создал рынок из ожидания. К сожалению, весьма эффективный":"He created a market out of waiting. Unfortunately, a very effective one",
"Механизм тянет вверх. Что-то снизу тянет сильнее":"The mechanism is pulling upward. Something below is pulling harder",
"Совет уже высказался. Теперь спросите тех, кто варит это каждый день":"The council has spoken. Now ask the people who brew it every day",
"Если он требует уважения, возможно, кто-то всё-таки дал ему достаточно мозгов, чтобы обижаться":"If it demands respect, perhaps someone did give it enough brains to take offense",
"Это уже не гвоздь. Но я не уверен, что им стоит об этом говорить":"That is no longer a nail. But I am not sure we should tell them",
"Он описал дорогу слишком подробно, чтобы придумать её. Значит, ошибка либо в карте, либо в мире":"He described the road too precisely to have invented it. So either the map is wrong or the world is",
"Честность не делает сделку хорошей. Но хотя бы сокращает чтение мелкого шрифта":"Honesty does not make a deal good. But at least it shortens the fine print",
"Если дать им ещё сутки, они начнут войну не из-за ада, а из-за очереди":"Give them another day and they will start a war not over hell, but over the queue",
"Оно не боится темноты. Оно боится того, что приходит вместе с ней":"It is not afraid of the dark. It is afraid of what comes with it",
"Хорошая новость: договор короткий. Плохая: ошибка занимает половину текста":"Good news: the contract is short. Bad news: the mistake takes up half the text",
"Удивительно мирный способ провести день для существа из ада":"A remarkably peaceful way for a creature from hell to spend the day",
"Портал стоит крепко. Жаль, что не там":"The portal is standing firmly. Pity it is standing in the wrong place",
"Иногда признать опоздание полезнее, чем пытаться исправить его ещё одним событием":"Sometimes admitting you are late is more useful than trying to fix it with yet another ceremony",
"Он горячий, тонкий и светится. По крайней мере, проблема честная":"It is hot, thin, and glowing. At least the problem is honest",
"Намерение может быть грехом. Но приговор за несовершённый поступок — уже грех суда":"Intent may be a sin. But sentencing someone for an act not committed is already a sin of the court",
"Похоже, он пытался ответить на вопрос, который ему вообще не задавали":"It seems he was trying to answer a question nobody asked him",
"Они не ищут его. Они знают, где он, и идут без спешки":"They are not searching for him. They know where he is and are coming without haste",
"Охотники уже идут сюда. Я знаю, как выглядит путь того, кому некуда возвращаться":"The hunters are already coming here. I know what the road looks like for someone with nowhere to return to",
"Поздравляю. Мы нашли спор о земле, где одна из сторон — воздух":"Congratulations. We have found a land dispute where one party is the air",
"Дорога не перестаёт быть дорогой только потому, что кто-то временно решил поселиться над ней":"A road does not stop being a road just because someone temporarily decided to live above it",
"Редкий случай, когда богатство действительно мешает получить деньги":"A rare case where wealth genuinely makes it harder to get money",
"Если он способен отказаться выходить, возможно, сначала стоит спросить почему":"If he is capable of refusing to come out, perhaps we should first ask why"
});export{EVENT_EN_V5_08};