const EVENT_EN_V4_04 = Object.freeze({
  "Лифт на семьдесят второй этаж": "The Elevator to the Seventy-Second Floor",
  "В горной шахте сломался главный подъёмник. Клетка зависла между уровнями, внутри двенадцать шахтёров и один бочонок пива. По голосам снизу понятно: пиво пока спасает моральный дух, но ресурс ограничен.": "The main lift in a mountain mine has broken down. The cage is suspended between levels with twelve miners and one keg of beer inside. Judging by the voices below, the beer is sustaining morale for now, but supplies are limited.",
  "Подъёмщик Дорн показывает механизм. Один зубец шестерни треснул. Запасной есть — на семьдесят втором этаже, куда обычно доставляет тот самый лифт.": "Lift operator Dorn shows you the mechanism. One gear tooth has cracked. There is a spare—on the seventy-second floor, which is normally reached by that very lift.",
  "«Архитектор считал это элегантным решением», — говорит Дорн. — «Архитектор умер естественной смертью. Удивительно».": "‘The architect considered it an elegant solution,’ Dorn says. ‘The architect died of natural causes. Surprisingly.’",
  "Спуститься по аварийным лестницам за шестернёй": "Take the emergency ladders to retrieve the gear",
  "Поднять клетку вручную всем отрядом": "Have the entire roster haul the cage up by hand",
  "Поручить Ладье собрать временную передачу из вагонеток и цепей": "Ask the Rook to build a temporary transmission from mine carts and chains",
  "{rookName} заглядывает в шахту. «Нам не нужен лифт. Нам нужна одна шестерня и способ заставить её подняться».": "{rookName} peers down the shaft. ‘We do not need the lift. We need one gear and a way to make it come up.’",
  "Срезать клетку и ловить её на нижнем тормозе": "Cut the cage loose and catch it on the lower brake",
  "Оставить дварфам их инженерную проблему": "Leave the dwarves to their engineering problem",

  "Дварфийское завещание": "The Dwarven Will",
  "Два брата спорят над завещанием отца. Текст выбит на железной плите и звучит просто: «Кузню получает тот, кто лучше меня».": "Two brothers argue over their father's will. The text is engraved on an iron plate and sounds simple enough: ‘The forge goes to whoever is better than me.’",
  "Проблема очевидна: отец умер и не оставил критериев. Брун лучше куёт мечи. Келд лучше делает замки. Оба уверены, что покойный имел в виду именно их ремесло.": "The problem is obvious: their father is dead and left no criteria. Brun forges better swords. Keld makes better locks. Both are certain the deceased meant their particular craft.",
  "Нотариус Мара уже предложила бросить монету. Братья объявили это «человеческой ересью» и теперь требуют решения Короля.": "Notary Mara has already suggested flipping a coin. The brothers declared that ‘human heresy’ and now demand the King's ruling.",
  "Провести состязание в ремесле": "Hold a contest of craftsmanship",
  "Разделить мастерскую между братьями": "Divide the workshop between the brothers",
  "Поручить Ферзю выяснить, что отец действительно ценил в сыновьях": "Ask the Queen to determine what the father truly valued in his sons",
  "{queenName} постукивает по плите ногтем. «Он не написал “лучший кузнец”. Он написал “лучше меня”. Возможно, речь вообще не о кузне».": "{queenName} taps a fingernail against the plate. ‘He did not write “the better smith.” He wrote “better than me.” Perhaps this is not about smithing at all.’",
  "Выкупить спорную кузню у обоих": "Buy the disputed forge from both brothers",
  "Отказаться толковать дварфийские завещания": "Refuse to interpret dwarven wills",

  "Пушка против горы": "Cannon Versus Mountain",
  "На перевале дварфы установили пушку размером с небольшой дом. Орудие называется «Малютка». Его ствол направлен не на армию, а на гору.": "At the pass, the dwarves have installed a cannon the size of a small house. The weapon is called ‘Little One.’ Its barrel points not at an army, but at a mountain.",
  "Фрида объясняет: лавина перекрыла единственный проход, а расчищать снег вручную займёт неделю. План — выстрелить в склон так, чтобы вызвать «правильную вторую лавину», которая столкнёт первую в ущелье.": "Frida explains that an avalanche has blocked the only passage, and clearing the snow by hand would take a week. The plan is to fire into the slope and trigger ‘the correct second avalanche,’ which will push the first one into the gorge.",
  "«Мы посчитали угол», — говорит она. Один из расчётчиков тихо добавляет: «Три раза. Ответы разные».": "‘We calculated the angle,’ she says. One of the crew quietly adds, ‘Three times. Different answers.’",
  "Разрешить дварфам стрелять по текущим расчётам": "Allow the dwarves to fire using the current calculations",
  "Помочь расчистить дорогу вручную": "Help clear the road by hand",
  "Поручить Ладье пересчитать нагрузку и поставить подпорные заряды": "Ask the Rook to recalculate the load and place supporting charges",
  "{rookName} просит расчёты и хмурится. «Угол тут ни при чём. Они забыли вес мокрого снега».": "{rookName} asks for the calculations and frowns. ‘The angle is not the problem. They forgot the weight of wet snow.’",
  "Купить один лишний снаряд": "Buy one spare shell",
  "Искать другой перевал": "Look for another pass",

  "Пиво, которое не хочет открываться": "The Beer That Refuses to Open",
  "Пивовар Хальда показывает бочку, которую её дед закрыл сто лет назад «для великого случая». Великий случай наступил: род Хальды выиграл судебный спор, пережил обвал шахты и наконец выплатил долг за пивоварню.": "Brewer Halda shows you a barrel her grandfather sealed a hundred years ago ‘for a great occasion.’ The great occasion has arrived: Halda's clan won a lawsuit, survived a mine collapse, and finally paid off the brewery's debt.",
  "Бочка не открывается. Топор отскакивает. Кран ломается. Руна на крышке каждый раз перестраивается в новое слово. Последняя попытка дала надпись: «НЕ ДОСТАТОЧНО ВЕЛИКО».": "The barrel will not open. An axe bounces off. The tap breaks. The rune on the lid rearranges itself into a new phrase after every attempt. The latest one reads: ‘NOT GREAT ENOUGH.’",
  "Хальда смотрит на Короля. «Ну, если приезд монарха тоже не считается, я уже не знаю, чего эта зараза ждёт».": "Halda looks at the King. ‘Well, if a monarch's arrival does not count either, I have no idea what this cursed thing is waiting for.’",
  "Объявить официальный королевский праздник и попробовать снова": "Declare an official royal holiday and try again",
  "Разбить бочку кузнечным молотом": "Break the barrel with a smithing hammer",
  "Поручить Слону понять, какое событие руна считает “великим”": "Ask the Bishop to determine what event the rune considers ‘great’",
  "{bishopName} улыбается. «Это не замок. Это условие. И кто-то из предков был очень драматичным человеком».": "{bishopName} smiles. ‘This is not a lock. It is a condition. And one of the ancestors was a very dramatic person.’",
  "Предложить Хальде продать бочку неоткрытой коллекционеру": "Suggest that Halda sell the unopened barrel to a collector",
  "Оставить легендарное пиво следующему поколению": "Leave the legendary beer to the next generation",

  "Мотоцикл без тормозов": "The Motorcycle Without Brakes",
  "Рёв двигателя появляется раньше самой гонщицы. Дварфка Ринна вылетает из-за поворота на тяжёлом рунном мотоцикле, проносится мимо отряда и кричит: «ТОРМОЗОВ НЕТ!»": "The roar of the engine arrives before the rider herself. The dwarf Rinna bursts around the bend on a heavy runic motorcycle, races past the roster, and shouts: ‘NO BRAKES!’",
  "Через минуту она проезжает обратно в противоположную сторону. Затем ещё раз.": "A minute later she races back in the opposite direction. Then again.",
  "Механик Тоб, запыхавшись, добегает следом и объясняет: двигатель подпитывается от руны движения. Пока машина едет, руна сильнее. Чем сильнее руна, тем труднее остановиться. «Теоретически это очень эффективная система».": "Mechanic Tob catches up, out of breath, and explains: the engine draws power from a rune of motion. The longer the machine moves, the stronger the rune becomes. The stronger the rune becomes, the harder it is to stop. ‘In theory it is a very efficient system.’",
  "Поставить на дороге мягкую баррикаду": "Set up a soft barricade on the road",
  "Попытаться запрыгнуть на мотоцикл на ходу": "Try to jump onto the motorcycle while it is moving",
  "Поручить Коню загнать Ринну на длинный подъём и вымотать руну": "Ask the Knight to drive Rinna onto a long uphill stretch and exhaust the rune",
  "{knightName} следит за очередным кругом Ринны. «Её нельзя догнать. Но можно заставить дорогу догнать её».": "{knightName} watches Rinna make another circuit. ‘We cannot catch her. But we can make the road catch her.’",
  "Предложить Тобу просто снять источник питания выстрелом": "Suggest that Tob simply shoot out the power source",
  "Отойти с дороги": "Get off the road",

  "Самолёт, который боится высоты": "The Airplane Afraid of Heights",
  "На лугу стоит дварфийский самолёт с медными крыльями. Пилот Окко уверяет, что машина исправна. Двигатель запускается, винт крутится, руны горят. Но стоит колёсам оторваться от земли на ладонь, самолёт сам глушит двигатель и садится.": "A dwarven airplane with copper wings stands in a meadow. Pilot Okko insists the machine is in working order. The engine starts, the propeller spins, the runes glow. But the moment the wheels rise a handspan above the ground, the airplane shuts down its own engine and lands.",
  "Окко ругает автоматику. «Синица» отвечает через табличку диагностики: `ВЫСОКО. НЕ ХОЧУ.`": "Okko curses the controls. ‘Titmouse’ answers through its diagnostic display: `TOO HIGH. DO NOT WANT.`",
  "Механический аппарат, похоже, приобрёл не только разум, но и вполне конкретную фобию.": "The mechanical craft appears to have acquired not only intelligence, but a very specific phobia.",
  "Отключить блок страха принудительно": "Disable the fear module by force",
  "Предложить Окко продать машину как наземный транспорт": "Suggest that Okko sell the machine as ground transport",
  "Поручить Ладье постепенно испытать систему на малых подъёмах": "Ask the Rook to test the system gradually at low altitude",
  "{rookName} стучит по корпусу и говорит уже самолёту: «Тебе не нужно любить высоту. Тебе нужно доверять крыльям».": "{rookName} knocks on the fuselage and speaks directly to the airplane. ‘You do not have to love heights. You have to trust your wings.’",
  "Полететь вместе с Окко, чтобы “показать пример”": "Fly with Okko to ‘set an example’",
  "Не лечить тревожность у самолёта посреди похода": "Do not treat an airplane's anxiety in the middle of a campaign",

  "Демон продаёт честные сделки": "The Demon Selling Honest Deals",
  "Демон Фазз поставил у дороги киоск с вывеской: «ЧЕСТНЫЕ СДЕЛКИ. БЕЗ МЕЛКОГО ШРИФТА». Под вывеской висит вторая: «МЕЛКИЙ ШРИФТ ЗАПРЕЩЁН КОРОЛЕВСКИМ УКАЗОМ №17». Никто в отряде не помнит такого указа.": "The demon Fazz has set up a roadside stall with a sign: ‘HONEST DEALS. NO FINE PRINT.’ Beneath it hangs another: ‘FINE PRINT PROHIBITED BY ROYAL DECREE No. 17.’ No one in the roster remembers such a decree.",
  "Фазз действительно пишет огромными буквами. Его договор занимает сорок семь листов, каждый размером с дверь.": "Fazz really does write in enormous letters. His contract occupies forty-seven sheets, each the size of a door.",
  "«Всё прозрачно», — говорит демон. На странице 31 крупно написано: `ПОКУПАТЕЛЬ ПРИЗНАЁТ, ЧТО ПОНЯТИЕ “ПРОЗРАЧНО” НОСИТ МЕТАФОРИЧЕСКИЙ ХАРАКТЕР`. ": "‘Everything is transparent,’ the demon says. Page 31 declares in large letters: `THE BUYER ACKNOWLEDGES THAT THE TERM “TRANSPARENT” IS METAPHORICAL.`",
  "Купить 3 Supplies за 16 Gold": "Buy 3 Supplies for 16 Gold",
  "Продать Фаззу право назвать мост своим именем": "Sell Fazz the right to name a bridge after himself",
  "Поручить Ферзю найти пункт, позволяющий разорвать договор в пользу покупателя": "Ask the Queen to find a clause that lets the buyer terminate the contract in their favor",
  "{queenName} закрывает договор. «Он не прячет ловушку. Он рассчитывает, что никто не дочитает до неё».": "{queenName} closes the contract. ‘He is not hiding the trap. He is counting on nobody reading far enough to reach it.’",
  "Подписать договор Королём, не читая последние страницы": "Have the King sign the contract without reading the final pages",
  "Уйти": "Leave",

  "Адский пёс хочет палку": "The Hellhound Wants the Stick",
  "Трёхголовый адский пёс размером с телегу блокирует дорогу. Из пастей идёт дым. Земля под лапами обуглена.": "A three-headed hellhound the size of a wagon blocks the road. Smoke pours from its jaws. The ground beneath its paws is scorched.",
  "Демон-егерь Кхар стоит в стороне и орёт: «НЕ БЕГИТЕ!» Затем добавляет: «И палку ему не показывайте!»": "Demon huntsman Khar stands to one side and shouts: ‘DO NOT RUN!’ Then adds: ‘And do not show him the stick!’",
  "Поздно. Одна из голов уже заметила сломанную ветку в руках Пешки. Хвост начинает вилять так сильно, что сбивает дорожный знак.": "Too late. One of the heads has already spotted the broken branch in the Pawn's hands. The tail starts wagging so hard that it knocks over a road sign.",
  "Бросить палку далеко в сторону и пройти, пока пёс гонится за ней": "Throw the stick far away and pass while the hound chases it",
  "Заплатить Кхару за контроль животного": "Pay Khar to control the animal",
  "Поручить Пешке занять пса игрой и увести от дороги": "Ask the Pawn to distract the hound with play and lead it away from the road",
  "{pawnName} медленно поднимает ветку. «Кажется, у нас есть дипломатический инструмент».": "{pawnName} slowly raises the branch. ‘It seems we have a diplomatic instrument.’",
  "Атаковать чудовище": "Attack the beast",
  "Обойти по осыпи": "Go around via the scree slope",

  "Чужой грех": "Another's Sin",
  "Демон Ишра сидит у костра напротив молодой женщины. Между ними лежит чёрная монета. Мира утверждает, что монета хранит один человеческий грех и избавляет владельца от вины — но переносит сам поступок в память следующего человека, который её возьмёт.": "The demon Ishra sits by a fire opposite a young woman. A black coin lies between them. Mira claims the coin stores one human sin and frees its owner from guilt—but transfers the deed itself into the memory of the next person who takes it.",
  "Она хочет избавиться от монеты. Ишра хочет купить её. Не душу, не кровь, не годы жизни — просто монету.": "She wants to get rid of the coin. Ishra wants to buy it. Not a soul, not blood, not years of life—just the coin.",
  "«У демонов тоже есть коллекционеры», — говорит он. Мира не смеётся.": "‘Demons have collectors too,’ he says. Mira does not laugh.",
  "Позволить Ишре купить монету у Миры": "Allow Ishra to buy the coin from Mira",
  "Разрушить монету": "Destroy the coin",
  "Поручить Слону снять проклятие, не стирая память о поступке": "Ask the Bishop to remove the curse without erasing the memory of the deed",
  "{bishopName} не касается монеты. «Вина здесь не магия. Магия только не даёт человеку забыть, за что ему стыдно».": "{bishopName} does not touch the coin. ‘Guilt is not the magic here. The magic only prevents a person from forgetting what they are ashamed of.’",
  "Взять монету себе": "Take the coin for yourself",

  "Очередь в ад": "The Queue for Hell",
  "Посреди пустоши стоит очередь. В ней призраки, скелеты, один раздражённый купец и два человека, которые явно ещё живы. В конце — окно с табличкой «ПРИЁМ ПО ПРЕДВАРИТЕЛЬНОЙ СМЕРТИ».": "A queue stands in the middle of the wasteland. It contains ghosts, skeletons, one irritated merchant, and two people who are clearly still alive. At the end is a window bearing the sign: ‘SERVICE BY PRIOR DEATH ONLY.’",
  "Демон-регистратор Ульф сообщает, что из-за ошибки портала часть умерших попала не туда и теперь ждёт перераспределения. Живые оказались здесь из-за одинаковых фамилий.": "Demon registrar Ulf explains that a portal error sent some of the dead to the wrong destination, and they are now waiting for reassignment. The living ended up here because of matching surnames.",
  "«Документы решат всё», — обещает Ульф и достаёт стопку толщиной с кирпичную стену.": "‘The paperwork will solve everything,’ Ulf promises, producing a stack as thick as a brick wall.",
  "Король смотрит на очередь. «При жизни бюрократия хотя бы делала вид, что спешит».": "The King looks at the queue. ‘In life, bureaucracy at least pretended to be in a hurry.’",
  "Помочь двум живым доказать, что они ещё живы": "Help the two living people prove that they are still alive",
  "Заплатить Ульфу за ускоренное обслуживание": "Pay Ulf for expedited service",
  "Потребовать закрыть незаконный портал на королевской земле": "Demand that the illegal portal on royal land be closed",
  "Встать в очередь “только спросить”": "Join the queue ‘just to ask a question’",
  "Обойти очередь широкой дугой": "Give the queue a very wide berth"
});

export { EVENT_EN_V4_04 };
