const path=require('path');const assert=require('assert');const{pathToFileURL}=require('url');
(async()=>{const game=path.resolve(__dirname,'..','game');const data=await import(pathToFileURL(path.join(game,'js/events-data.mjs')).href);const core=await import(pathToFileURL(path.join(game,'js/events-core.mjs')).href);const persistence=await import(pathToFileURL(path.join(game,'js/run-persistence.mjs')).href);const travel=await import(pathToFileURL(path.join(game,'js/travel-choice-core.mjs')).href);
assert.strictEqual(data.EVENT_CATALOG.length,100,'Events v1 must contain exactly 100 events');assert.strictEqual(new Set(data.EVENT_IDS).size,100);const choices=data.EVENT_CATALOG.flatMap(e=>e.choices);assert.strictEqual(choices.length,415,'approved catalog must contain 415 authored choices');for(const e of data.EVENT_CATALOG){assert(e.choices.length>=3&&e.choices.length<=5,`${e.id} must have 3-5 choices`);assert(String(e.story).split(/[.!?](?:\s|$)/).filter(Boolean).length>=3,`${e.id} needs mini-story copy`);}const races=['Люди','Эльфы','Орки','Нежить','Тёмные эльфы','Гномы','Демоны','Ангелы','Дракониды','Зверолюди','Конструкты','Животные','Феи','Гоблины'];for(const race of races)assert.strictEqual(data.EVENT_CATALOG.filter(e=>e.race===race).length,6,`${race} must have six events`);
const bag=core.shuffledEventIds('bag-test',0);assert.strictEqual(bag.length,100);assert.strictEqual(new Set(bag).size,100);assert.deepStrictEqual(bag,core.shuffledEventIds('bag-test',0),'shuffle bag must be deterministic');
const generated=travel.createTravelChoices({runId:'events-probability-contract',step:1});assert.strictEqual(generated.length,3);assert.deepStrictEqual(travel.PLAYABLE_TRAVEL_TYPES,['skirmish','battle','settlement','event']);const samples={skirmish:0,battle:0,settlement:0,event:0};for(let i=1;i<=4000;i++)for(const c of travel.createTravelChoices({runId:`prob-${i}`,step:1}))samples[c.type]++;for(const type of Object.keys(samples)){const ratio=samples[type]/12000;assert(ratio>.22&&ratio<.28,`${type} empirical ratio ${ratio} is not near 25%`);}
let run=persistence.createRun({id:'events-economy-test',now:1});const route={id:'travel.event.manual',step:1,type:'event',label:'СОБЫТИЕ',stars:2,threatLabel:'УМЕРЕННАЯ',flavor:'Событие.',mechanicalHint:'Исход неизвестен.',seed:'event-economy-seed',supplyCostAtSelection:1,supplyPaid:1};run={...run,activeTravelChoice:route,currentTravelChoices:null,journeyStep:1};let created=core.createEventState(run,route);run={...created.run,currentEvent:{...created.state,eventId:'E002'}};const trade=core.resolveEventChoice(run,'E002.1');assert.strictEqual(trade.success,true);assert.strictEqual(trade.run.gold,62,'18 Gold purchase must charge exactly 18 Gold');assert.strictEqual(trade.run.supplies,12,'purchase must grant exactly 2 Supplies');const again=core.resolveEventChoice(trade.run,'E002.1');assert.strictEqual(again.reason,'already-resolved');assert.strictEqual(again.run.gold,62,'resolved event cannot charge twice');
let alwaysRun=persistence.createRun({id:'events-always-effect-test',now:2});alwaysRun={...alwaysRun,activeTravelChoice:{...route,seed:'always-effect-seed'},currentTravelChoices:null,journeyStep:1};created=core.createEventState(alwaysRun,alwaysRun.activeTravelChoice);alwaysRun={...created.run,currentEvent:{...created.state,eventId:'E018'}};const ambush=core.resolveEventChoice(alwaysRun,'E018.2');assert.strictEqual(ambush.success,true,'always-effect fixture must resolve');assert(ambush.run.currentEvent.combat,'E018.2 authored alwaysEffect must create combat on either roll result');assert.strictEqual(ambush.run.currentEvent.combat.type,'skirmish');assert.strictEqual(ambush.run.currentEvent.combat.stars,3,'E018.2 +1 threat modifier must apply to route stars');assert(ambush.run.currentEvent.outcome.notes.includes('Начинается Стычка'),'always combat must be visible in outcome notes');
const kingRisks=[];for(const e of data.EVENT_CATALOG)for(const raw of e.choices){const c=core.normalizeChoice(raw);const allEffects=[...c.successEffects,...c.failureEffects,...c.alwaysEffects];const kingDeath=allEffects.some(x=>x.type==='death'&&x.target==='king');if(kingDeath){kingRisks.push(c.id);assert.strictEqual(c.kingRisk,true,`${c.id} King death must be explicitly flagged`);assert(c.warnings.some(w=>w.includes('КОРОЛЬ')),`${c.id} King death must warn in UI`);}for(const effect of allEffects)if(effect.type==='death'&&effect.target==='randomNonKing')assert.notStrictEqual(effect.target,'king');}assert.strictEqual(kingRisks.length,4,'approved v1 contains exactly four explicit King-death choices');
const woundedKing={...persistence.createRun({id:'wounded-king',now:3}),roster:persistence.createRun({id:'tmp',now:3}).roster.map(c=>c.isRunKing?{...c,status:'wounded'}:c)};const skirmish=await import(pathToFileURL(path.join(game,'js/skirmish-core.mjs')).href);const battle=await import(pathToFileURL(path.join(game,'js/battle-core.mjs')).href);assert(skirmish.defaultCombatSelection(woundedKing.roster).includes(woundedKing.roster.find(c=>c.isRunKing).id),'wounded King must remain combat-eligible');assert(battle.defaultBattleSelection(woundedKing.roster).includes(woundedKing.roster.find(c=>c.isRunKing).id),'wounded King must remain Battle-eligible');
console.log('Events 100/415 catalog, races, 25% Travel pool, shuffle bag, idempotent economy, always-effects, King risk and wounded-King continuity: PASS');})().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
