const assert=require('assert'),{chromium}=require('playwright'),{startNewRun}=require('./browser-test-helpers.cjs');const url=process.env.RPCHESS_ACCEPTANCE_URL||'http://127.0.0.1:4173',RUN_KEY='rpchess.reboot.v1.run',cyrillic=/[А-Яа-яЁё]/u;
const eventRoute={id:'manual.event.route',step:1,type:'event',label:'СОБЫТИЕ',stars:12,threatLabel:'ЛЕГЕНДАРНАЯ',flavor:'Необычная встреча на дороге.',mechanicalHint:'',seed:'manual-event-seed',supplyCostAtSelection:1,supplyPaid:1};
async function fresh(page){await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(k=>localStorage.removeItem(k),RUN_KEY);await page.reload({waitUntil:'networkidle'});await startNewRun(page);}
async function seedEvent(page,eventId=null,runId='events-browser'){await page.evaluate(({key,route,eventId,runId})=>{const r=JSON.parse(localStorage.getItem(key));r.id=runId;r.supplies=9;r.journeyStep=1;r.currentTravelChoices=null;r.activeTravelChoice=route;r.currentSettlement=null;r.currentPuzzle=null;r.currentEvent=eventId?{routeId:route.id,eventId,choiceId:null,roll:null,success:null,resolved:false,outcome:null,combat:null}:null;localStorage.setItem(key,JSON.stringify(r));dispatchEvent(new CustomEvent('rpchess:run-updated'));},{key:RUN_KEY,route:eventRoute,eventId,runId});}
(async()=>{const browser=await chromium.launch({headless:true});try{
  const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e.stack||e)));await fresh(page);await seedEvent(page,'E001','events-browser');await page.locator('[data-roster-travel]').click();const screen=page.locator('[data-events-screen]:not([hidden])');await screen.waitFor();
  const paragraphs=page.locator('[data-events-story] p'),storyText=await page.locator('[data-events-story]').innerText();assert.strictEqual(await paragraphs.count(),2,'E001 must render its two canonical literary story paragraphs');assert(storyText.length>=450,'Event scene must preserve the extended canonical literary copy');assert(storyText.includes('«'),'literary scene must include dialogue');const bg=page.locator('[data-events-background]');await bg.waitFor();const bgSrc=await bg.getAttribute('src');assert(bgSrc&&bgSrc.includes('/assets/events/register-04/backgrounds/'),'Event scene must use the explicit canonical backdrop image');assert.strictEqual(await page.locator('[data-events-roster]').count(),0,'obsolete Event Roster shortcut must be absent from the runtime DOM');assert.strictEqual(await page.locator('[data-events-settings]').count(),0,'obsolete Event Settings shortcut must be absent from the runtime DOM');
  const frames=await page.evaluate(()=>({copy:Boolean(document.querySelector('.events-copy-frame')),choices:Boolean(document.querySelector('.events-choice-frame'))}));assert.deepStrictEqual(frames,{copy:true,choices:true},'consolidated Event presentation must expose canonical copy/choice frames');const count=await page.locator('[data-event-choice]').count();assert(count>=3&&count<=5);assert((await screen.innerText()).includes('%')||(await screen.innerText()).includes('ГАРАНТИРОВАННО'));assert.strictEqual(await page.locator('[data-events-outcome]:not([hidden])').count(),0,'outcome dialog must be hidden before a choice');
  const risk=page.locator('[data-event-choice]:not([disabled])').filter({hasText:'%'}).first(),choice=await risk.count()?risk:page.locator('[data-event-choice]:not([disabled])').first();await choice.click();const outcome=page.locator('[data-events-outcome]:not([hidden])');await outcome.waitFor();assert.strictEqual(await outcome.getAttribute('class'),'events-outcome-modal');assert.strictEqual(await page.locator('[data-events-choices]').isVisible(),true,'choice scene stays behind separate modal');
  const saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),RUN_KEY);assert(saved.currentEvent.resolved);assert(saved.currentEvent.choiceId);assert(Number.isInteger(saved.currentEvent.roll));assert.strictEqual(saved.ended,false);const snapshot=JSON.stringify({gold:saved.gold,supplies:saved.supplies,roster:saved.roster,currentEvent:saved.currentEvent});
  await page.reload({waitUntil:'networkidle'});await page.locator('[data-continue-run]').click();await page.locator('[data-roster-screen]:not([hidden])').waitFor();await page.locator('[data-roster-travel]').click();await page.locator('[data-events-outcome]:not([hidden])').waitFor();assert.strictEqual(await page.locator('[data-events-roster],[data-events-settings]').count(),0,'obsolete Event shortcuts must remain absent after reload');const reloaded=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),RUN_KEY);assert.strictEqual(JSON.stringify({gold:reloaded.gold,supplies:reloaded.supplies,roster:reloaded.roster,currentEvent:reloaded.currentEvent}),snapshot);

  const combatPage=await browser.newPage({viewport:{width:1440,height:900}}),combatErrors=[];combatPage.on('pageerror',e=>combatErrors.push(String(e.stack||e)));await fresh(combatPage);await seedEvent(combatPage,'E018','events-combat-browser');await combatPage.locator('[data-roster-travel]').click();await combatPage.locator('[data-events-screen]:not([hidden])').waitFor();await combatPage.locator('[data-event-choice="E018.2"]').click();await combatPage.locator('[data-events-outcome]:not([hidden])').waitFor();const beforeCombat=await combatPage.evaluate(k=>JSON.parse(localStorage.getItem(k)),RUN_KEY);assert(beforeCombat.currentEvent.combat&&beforeCombat.currentEvent.combat.type==='skirmish');assert(beforeCombat.currentEvent.combat.stars>=1&&beforeCombat.currentEvent.combat.stars<=12);assert(['w','b'].includes(beforeCombat.currentEvent.combat.playerColor));assert(beforeCombat.currentEvent.combat.enemyRaceTag);const suppliesBefore=beforeCombat.supplies;await combatPage.locator('[data-events-continue]').click();await combatPage.locator('[data-skirmish-screen]:not([hidden])').waitFor();const routed=await combatPage.evaluate(k=>JSON.parse(localStorage.getItem(k)),RUN_KEY);assert.strictEqual(routed.supplies,suppliesBefore);assert.strictEqual(routed.currentEvent.combat.started,true,'Event combat must be marked started before Skirmish composition');const start=combatPage.locator('[data-skirmish-start]');assert.strictEqual(await start.isEnabled(),true,'Event-origin Skirmish default formation must be startable');await start.click();await combatPage.locator('[data-classic-screen]:not([hidden])').waitFor({timeout:5000});assert.strictEqual(await combatPage.locator('[data-chess-board] [data-square]').count(),64,'Event-origin Skirmish start must open the real chess board');

  const mobile=await browser.newPage({viewport:{width:390,height:844}}),mobileErrors=[];mobile.on('pageerror',e=>mobileErrors.push(String(e.stack||e)));await fresh(mobile);await seedEvent(mobile,'E091','events-mobile');await mobile.locator('[data-roster-travel]').click();await mobile.locator('[data-events-screen]:not([hidden])').waitFor();assert.strictEqual(await mobile.locator('[data-events-roster],[data-events-settings]').count(),0,'obsolete Event shortcuts must stay absent on mobile');const layout=await mobile.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,sh:document.documentElement.scrollHeight,ch:document.documentElement.clientHeight}));assert(layout.sw<=layout.cw+1);assert(layout.sh>layout.ch);

  const enPage=await browser.newPage({viewport:{width:1440,height:900}}),enErrors=[];enPage.on('pageerror',e=>enErrors.push(String(e.stack||e)));await fresh(enPage);await enPage.evaluate(()=>globalThis.RPChessI18n.setLanguage('en'));await seedEvent(enPage,'E147','events-en-e147');await enPage.locator('[data-roster-travel]').click();const enScreen=enPage.locator('[data-events-screen]:not([hidden])');await enScreen.waitFor();assert.strictEqual(await enPage.locator('[data-events-title]').innerText(),'The Pilgrim Who Walks Backward','E147 must render its translated title in the real Event DOM');const en147Text=await enScreen.innerText();assert.strictEqual(cyrillic.test(en147Text),false,'E147 real Event DOM must contain no Cyrillic in EN');await enPage.evaluate(k=>{const r=JSON.parse(localStorage.getItem(k));r.playerName='Qw';localStorage.setItem(k,JSON.stringify(r));},RUN_KEY);await seedEvent(enPage,'E291','events-en-e291');await enPage.waitForFunction(()=>document.querySelector('[data-events-title]')?.textContent?.includes('Lion'));const en291Text=await enScreen.innerText();assert(!cyrillic.test(en291Text)&&en291Text.includes('Qw'),'E291 real Event DOM must stay fully English after player-name personalization');
  assert.deepStrictEqual(errors,[]);assert.deepStrictEqual(combatErrors,[]);assert.deepStrictEqual(mobileErrors,[]);assert.deepStrictEqual(enErrors,[]);console.log('Events identity flow, canonical literary copy, complete EN Event rendering, persistence, Event→Skirmish→board and mobile Chromium acceptance: PASS');
}finally{await browser.close();}})().catch(e=>{console.error(e.stack||e);process.exitCode=1});
