const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
function memoryStorage(){const data=new Map();return{getItem:key=>data.has(key)?data.get(key):null,setItem:(key,value)=>data.set(key,String(value)),removeItem:key=>data.delete(key)}}
(async()=>{
  const game=path.resolve(__dirname,'..','game');
  const core=await import(pathToFileURL(path.join(game,'js/puzzles/puzzle-core.mjs')).href);
  const {PUZZLE_CATALOG}=await import(pathToFileURL(path.join(game,'js/puzzles/puzzle-catalog.mjs')).href);
  const persistence=await import(pathToFileURL(path.join(game,'js/run-persistence.mjs')).href);
  const catalog=PUZZLE_CATALOG;
  const rewardPuzzle=catalog.find(p=>p.difficulty===5) || catalog[0];
  const baseRun=persistence.createRun({id:'puzzle-reward-run',now:100});
  assert.deepStrictEqual(baseRun.puzzleHistory,[],'new runs must initialize persistent Puzzle history');
  const activeChoice={id:'travel.puzzle.reward',step:33,type:'puzzle',label:'ЗАДАЧА',stars:5,threatLabel:'СЛОЖНОСТЬ ★5',flavor:'Задача.',mechanicalHint:'Шахматная задача с конкретной целью.',seed:'puzzle-reward-seed',supplyCostAtSelection:1,supplyPaid:1};
  const initialState=core.createPuzzleState({puzzle:rewardPuzzle,routeId:activeChoice.id,stars:5,week:33});
  const solvedState=core.resolvedPuzzleState({...initialState,errors:1},'solved');
  const firstSettlement=core.applyPuzzleReward({...baseRun,puzzleHistory:[rewardPuzzle.id],journeyStep:33,activeTravelChoice:activeChoice,currentPuzzle:solvedState},solvedState);
  assert.strictEqual(firstSettlement.changed,true);assert.strictEqual(firstSettlement.reward,17);assert.strictEqual(firstSettlement.state.rewardSettled,true);assert.strictEqual(firstSettlement.run.gold,baseRun.gold+17);
  const secondSettlement=core.applyPuzzleReward(firstSettlement.run,firstSettlement.state);
  assert.strictEqual(secondSettlement.changed,false);assert.strictEqual(secondSettlement.reward,0);assert.strictEqual(secondSettlement.run.gold,firstSettlement.run.gold,'reward settlement must be idempotent');
  const storage=memoryStorage();persistence.writeRun(firstSettlement.run,storage,200);const reloaded=persistence.readRun(storage);assert(reloaded);assert.strictEqual(reloaded.currentPuzzle.rewardSettled,true);assert.strictEqual(reloaded.currentPuzzle.result,'solved');assert.strictEqual(reloaded.gold,firstSettlement.run.gold);assert.deepStrictEqual(reloaded.puzzleHistory,[rewardPuzzle.id],'Puzzle history must survive reload');
  const legacyStorage=memoryStorage(),legacyRun={...baseRun,lastPuzzle:{puzzleId:rewardPuzzle.id,routeId:'legacy-route',result:'solved',errors:0,goldReward:24}};delete legacyRun.puzzleHistory;legacyStorage.setItem(persistence.RUN_STORAGE_KEY,JSON.stringify(legacyRun));const migrated=persistence.readRun(legacyStorage);assert(migrated);assert.deepStrictEqual(migrated.puzzleHistory,[rewardPuzzle.id],'legacy lastPuzzle must migrate into no-repeat history');
  const appSource=fs.readFileSync(path.join(game,'js/puzzles/puzzle-app.mjs'),'utf8'),cssSource=fs.readFileSync(path.join(game,'css/puzzles.css'),'utf8');
  assert(appSource.includes("rpchess:puzzle-open"));
  assert(!/hint/i.test(appSource),'Puzzles v1 must not introduce hint UI/mechanics');
  assert(appSource.includes("'Неверный ход'"));
  assert(/errors\s*>=\s*3/.test(appSource));
  assert(appSource.includes('rewardSettled'));
  assert(appSource.includes('resumeSession')&&appSource.includes('playForcedReply'),'reload during persisted opponent reply must self-resume');
  assert(appSource.includes('Восстанавливаем ответ соперника…'));
  assert(appSource.includes('PIECE_GLYPHS')&&appSource.includes('puzzle-piece-marker'),'Puzzle board must expose top-left technical piece glyphs');
  assert(appSource.includes('puzzle-coordinate--file')&&appSource.includes('puzzle-coordinate--rank'),'Puzzle board must render orientation-aware coordinates');
  assert(appSource.includes('puzzleHistory')&&appSource.includes('excludedIds: history'),'Puzzle route must use persistent no-repeat history');
  assert(appSource.includes('css/puzzles.css?v=20260829-puzzles-3'),'Puzzle annotation CSS cachebuster must advance');
  for(const token of ['.puzzle-piece-marker','.puzzle-coordinate--file','.puzzle-coordinate--rank'])assert(cssSource.includes(token),`Puzzle CSS missing ${token}`);
  console.log('Puzzles reward/persistence/history migration/no-repeat/board-annotation UI contracts: PASS');
})().catch(e=>{console.error(e.stack||e);process.exitCode=1});