const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url');
function memoryStorage(){const d=new Map();return{getItem:k=>d.has(k)?d.get(k):null,setItem:(k,v)=>d.set(k,String(v)),removeItem:k=>d.delete(k)}}
(async()=>{
  const game=path.resolve(__dirname,'..','game');
  const travelAppSource=fs.readFileSync(path.join(game,'js/travel-choice-app.mjs'),'utf8');
  const travelCss=fs.readFileSync(path.join(game,'css/travel-choice-compact.css'),'utf8');
  const polish=fs.readFileSync(path.join(game,'js/post-pages-ui-polish.mjs'),'utf8');
  assert(!travelAppSource.includes("document.addEventListener('click'"),'Travel must not intercept combat aftermath clicks globally');
  assert(travelAppSource.includes('recoverAftermathRoute'));assert(travelAppSource.includes("source==='skirmish-aftermath'")&&travelAppSource.includes("source==='battle-aftermath'"));assert(travelAppSource.includes("rpchess:puzzle-open"),'Puzzle routes must dispatch into playable scene');
  assert(travelAppSource.includes('data-travel-power')&&travelAppSource.includes('data-travel-player-threat'),'Travel must show Power and Threat without redesigning route cards');
  assert(travelAppSource.includes("OWNER_STYLE_HREF='css/travel-choice-compact.css'"),'Travel owner must load its compact stylesheet explicitly');
  assert(travelAppSource.includes('data-travel-run-portrait')&&travelAppSource.includes('function renderPortrait()'),'Travel owner must render and refresh the run king portrait itself');
  assert(travelCss.includes('.travel-choice-run-portrait{display:none}'),'Travel portrait must stay hidden outside the compact owner breakpoint');
  assert(travelCss.includes("grid-template-columns:40px minmax(112px,1fr) minmax(100px,1fr) minmax(148px,1.15fr)!important"),'tablet Travel command rhythm must preserve the accepted final cascade');
  assert(travelCss.includes("grid-template-columns:34px minmax(96px,1fr) minmax(88px,1fr) minmax(128px,1.05fr)!important"),'phone Travel command rhythm must preserve the accepted final cascade');
  assert(!polish.includes('body.travel-choice-active'),'post-pages-ui-polish must not retain Travel presentation ownership');
  assert(!fs.existsSync(path.join(game,'js/content/post-pages-ui-polish-constraints.mjs')),'superseded constraints compatibility module must stay deleted');
  assert(!fs.existsSync(path.join(game,'js/content/post-pages-ui-review2.mjs')),'superseded review2 compatibility module must stay deleted');
  assert(!polish.includes('syncTravel')&&!polish.includes('rpchess:travel-open'),'post-pages polish must not retain Travel rendering or Travel-open fan-out');
  const travel=await import(pathToFileURL(path.join(game,'js/travel-choice-core.mjs')).href),difficulty=await import(pathToFileURL(path.join(game,'js/encounter-difficulty.mjs')).href),rating=await import(pathToFileURL(path.join(game,'js/player-rating.mjs')).href),persistence=await import(pathToFileURL(path.join(game,'js/run-persistence.mjs')).href),skirmish=await import(pathToFileURL(path.join(game,'js/skirmish-core.mjs')).href),battle=await import(pathToFileURL(path.join(game,'js/battle-core.mjs')).href);
  assert.deepStrictEqual(travel.PLAYABLE_TRAVEL_TYPES,['skirmish','battle','settlement','event','puzzle']);assert.strictEqual(travel.TRAVEL_CHOICE_COUNT,3);assert.strictEqual(difficulty.MAX_ENCOUNTER_STARS,12);assert.strictEqual(difficulty.difficultyForStars(1).elo,400);assert.strictEqual(difficulty.difficultyForStars(12).elo,2600);
  for(const type of travel.PLAYABLE_TRAVEL_TYPES){assert(Array.isArray(travel.FLAVOR_POOLS[type]));assert(travel.FLAVOR_POOLS[type].length>=10);}
  const first=travel.createTravelChoices({runId:'travel-test-run',step:1,playerPower:500}),repeat=travel.createTravelChoices({runId:'travel-test-run',step:1,playerPower:500});assert.deepStrictEqual(first,repeat);assert.strictEqual(first.length,3);assert.strictEqual(new Set(first.map(c=>c.id)).size,3);assert(first.every(travel.isTravelChoice));assert(first.every(c=>c.difficultyModel==='power-v1'));
  const duplicateFound=Array.from({length:100},(_,i)=>travel.createTravelChoices({runId:`dupe-${i}`,step:1,playerPower:500})).some(f=>new Set(f.map(c=>c.type)).size<3);assert(duplicateFound,'independent pool must still allow duplicate types in one fork');
  const counts={skirmish:0,battle:0,settlement:0,event:0,puzzle:0};for(let i=0;i<5000;i++)for(const c of travel.createTravelChoices({runId:`distribution-${i}`,step:1,playerPower:500}))counts[c.type]++;for(const [type,count] of Object.entries(counts)){const ratio=count/15000;assert(ratio>.18&&ratio<.22,`${type} ratio ${ratio} must stay near 20%`);}
  for(const power of [500,600,1000,1600,2400,2600]){const threat=rating.threatStarsForPower(power);for(const type of ['skirmish','battle','puzzle']){for(let i=0;i<100;i++){const choices=travel.createTravelChoices({runId:`adaptive-${power}-${type}-${i}`,step:37,types:[type],playerPower:power});assert(choices.every(c=>c.stars>=threat&&c.stars<=Math.min(12,threat+3)),`${type} must stay at Threat..Threat+3`);}}}
  const low=Array.from({length:300},(_,i)=>travel.createTravelChoices({runId:`low-${i}`,step:99,types:['puzzle'],playerPower:500})[0]);assert(low.every(c=>c.stars>=1&&c.stars<=4),'journey week must no longer raise Puzzle beyond player-adaptive range');assert(new Set(low.map(c=>c.stars)).size>1,'adaptive Puzzle must expose multiple +0..3 levels');
  const late=Array.from({length:100},(_,i)=>travel.createTravelChoices({runId:`late-${i}`,step:30,playerPower:2400})).flat().filter(c=>c.type==='skirmish'||c.type==='battle');assert(late.some(c=>c.stars===12));assert(late.every(c=>c.stars>=11&&c.stars<=12));assert(late.every(c=>['w','b'].includes(c.playerColor)&&c.enemyRaceTag));assert(late.some(c=>c.playerColor==='b'));
  const run=persistence.createRun({id:'travel-run',now:1000}),storage=memoryStorage();persistence.writeRun({...run,currentTravelChoices:first},storage,1100);assert.deepStrictEqual(persistence.readRun(storage).currentTravelChoices,first);
  const puzzleChoice={...travel.createTravelChoices({runId:'persist-puzzle',step:41,types:['puzzle'],playerPower:500})[0],supplyCostAtSelection:1,supplyPaid:1};persistence.writeRun({...run,journeyStep:41,currentTravelChoices:null,activeTravelChoice:puzzleChoice},storage,1120);const storedPuzzle=persistence.readRun(storage);assert(storedPuzzle&&storedPuzzle.activeTravelChoice.type==='puzzle');assert(storedPuzzle.activeTravelChoice.stars>=1&&storedPuzzle.activeTravelChoice.stars<=4);
  const persistedEvent={...first[0],id:'persist.event',type:'event',label:'СОБЫТИЕ',stars:1,threatLabel:'ОЧЕНЬ НИЗКАЯ',flavor:'Неожиданная встреча у дороги.',mechanicalHint:'',seed:'persist-event'};const eventFork=[persistedEvent,first[1],first[2]];persistence.writeRun({...run,currentTravelChoices:eventFork},storage,1150);const persistedEventFork=persistence.readRun(storage);assert(persistedEventFork);assert.strictEqual(persistedEventFork.currentTravelChoices[0].mechanicalHint,'');
  const persistedTwelve={...first[0],id:'persist.12',type:'skirmish',label:'СТЫЧКА',stars:12,threatLabel:'ЛЕГЕНДАРНАЯ',mechanicalHint:'Нестандартный состав противника.',seed:'persist-12',playerColor:'b',enemyRaceTag:'orcs'};const highStarFork=[persistedTwelve,first[1],first[2]];persistence.writeRun({...run,currentTravelChoices:highStarFork},storage,1200);const persistedFork=persistence.readRun(storage);assert(persistedFork);assert.strictEqual(persistedFork.currentTravelChoices[0].stars,12);
  const activeTwelve={...persistedTwelve,combatCountAtSelection:0,supplyCostAtSelection:1,supplyPaid:1};persistence.writeRun({...run,currentTravelChoices:null,activeTravelChoice:activeTwelve},storage,1300);const persistedActive=persistence.readRun(storage);assert(persistedActive);assert.strictEqual(persistedActive.activeTravelChoice.combatCountAtSelection,0);
  const staleCompleted={...run,updatedAt:1400,skirmishCount:1,currentTravelChoices:null,activeTravelChoice:activeTwelve};storage.setItem(persistence.RUN_STORAGE_KEY,JSON.stringify(staleCompleted));const recovered=persistence.readRun(storage);assert(recovered);assert.strictEqual(recovered.activeTravelChoice.id,activeTwelve.id,'completed power-v1 route must remain until Elo settlement');assert.strictEqual(recovered.skirmishCount,1);
  const legacyActive={...activeTwelve,difficultyModel:undefined};const legacyCompleted={...run,updatedAt:1410,skirmishCount:1,currentTravelChoices:null,activeTravelChoice:legacyActive};storage.setItem(persistence.RUN_STORAGE_KEY,JSON.stringify(legacyCompleted));const legacyRecovered=persistence.readRun(storage);assert(legacyRecovered);assert.strictEqual(legacyRecovered.activeTravelChoice,null,'legacy completed combat route still auto-recovers');
  const manualSkirmish={id:'manual.s',step:1,type:'skirmish',label:'СТЫЧКА',stars:12,threatLabel:'ЛЕГЕНДАРНАЯ',flavor:'Путь.',mechanicalHint:'Нестандартный состав противника.',seed:'manual-s',playerColor:'b',enemyRaceTag:'orcs'};globalThis.RPChessTravelEncounterOverride=manualSkirmish;const rs=skirmish.createEncounter({seed:'fallback',stars:5});assert.strictEqual(rs.seed,'manual-s');assert.strictEqual(rs.stars,12);assert.strictEqual(rs.aiElo,2600);assert.strictEqual(rs.playerColor,'b');
  const manualBattle={...manualSkirmish,id:'manual.b',type:'battle',label:'БИТВА',seed:'manual-b'};globalThis.RPChessTravelEncounterOverride=manualBattle;const rb=battle.createBattleEncounter({seed:'fallback',stars:1});assert.strictEqual(rb.seed,'manual-b');assert.strictEqual(rb.stars,12);assert.strictEqual(rb.aiElo,2600);
  console.log('Travel Choice keeps 5-type ~20% pool, owner-rendered compact UI and player Threat..Threat+3 encounter contract: PASS');
})().catch(e=>{console.error(e.stack||e);process.exitCode=1});