const RU = Object.freeze({
  'classic.ariaLabel':'Классические шахматы','classic.newGame':'Новая партия','classic.menu':'Главное меню','classic.partyAria':'Партия','classic.partyTitle':'Партия','classic.materialAria':'Взятые фигуры и перевес по материалу','classic.side.white':'Белые','classic.side.black':'Чёрные','classic.side.whiteGenitive':'белых','classic.side.blackGenitive':'чёрных','classic.captured.white':'Фигуры, взятые белыми','classic.captured.black':'Фигуры, взятые чёрными','classic.boardAria':'Шахматная доска 8 на 8','classic.boardCell':'{square}: {piece}, {side}','classic.historyAria':'Ходы партии','classic.historyTitle':'Ходы','classic.historyEmpty':'Ходов пока нет',
  'classic.setup.kicker':'НОВАЯ ПАРТИЯ','classic.setup.title':'Выберите соперника','classic.setup.close':'Закрыть','classic.setup.mode':'Режим','classic.setup.mode.ai':'Против компьютера','classic.setup.mode.local':'Локальная партия','classic.setup.strength':'Сила соперника','classic.setup.color':'Ваш цвет','classic.setup.color.white':'Белые','classic.setup.color.black':'Чёрные','classic.setup.license':'лицензия','classic.setup.source':'исходный код','classic.setup.start':'Начать партию','classic.promotion.kicker':'ПРЕВРАЩЕНИЕ','classic.promotion.title':'Выберите фигуру',
  'classic.mode.local':'Локальная партия · два игрока','classic.mode.ai':'Stockfish 18 lite · {profile} · ≈{elo} Elo{fallback}','classic.mode.fallback':' · резервный ход','classic.state.check':'Шах','classic.state.checkmate':'Мат — победа {side}','classic.state.stalemate':'Пат — ничья','classic.state.draw50':'Ничья — правило 50 ходов','classic.state.drawThreefold':'Ничья — троекратное повторение','classic.state.drawInsufficient':'Ничья — недостаточно материала','classic.state.continues':'Партия продолжается','classic.result.checkmateTitle':'Мат','classic.result.checkmateText':'{side} победили.','classic.result.stalemateTitle':'Пат','classic.result.stalemateText':'Легальных ходов нет, шаха нет. Ничья.','classic.result.drawTitle':'Ничья','classic.result.draw50Text':'Пятьдесят ходов прошли без хода пешкой и без взятия.','classic.result.drawThreefoldText':'Одна и та же позиция возникла трижды.','classic.result.drawInsufficientText':'На доске недостаточно материала для мата.','classic.turn.complete':'Партия завершена','classic.turn.active':'Ход {side}','classic.status.thinking':'Компьютер думает…','classic.status.animating':'Ход выполняется','classic.summary.choosing':' выбирают ход.','classic.summary.checked':' под шахом. Нужно защитить короля.','classic.summary.turn':' делают ход.'
});

const EN = Object.freeze({
  'classic.ariaLabel':'Classic Chess','classic.newGame':'New Game','classic.menu':'Main Menu','classic.partyAria':'Game','classic.partyTitle':'Game','classic.materialAria':'Captured pieces and material advantage','classic.side.white':'White','classic.side.black':'Black','classic.side.whiteGenitive':'White','classic.side.blackGenitive':'Black','classic.captured.white':'Pieces captured by White','classic.captured.black':'Pieces captured by Black','classic.boardAria':'8 by 8 chessboard','classic.boardCell':'{square}: {piece}, {side}','classic.historyAria':'Game moves','classic.historyTitle':'Moves','classic.historyEmpty':'No moves yet',
  'classic.setup.kicker':'NEW GAME','classic.setup.title':'Choose an opponent','classic.setup.close':'Close','classic.setup.mode':'Mode','classic.setup.mode.ai':'Vs Computer','classic.setup.mode.local':'Local Game','classic.setup.strength':'Opponent Strength','classic.setup.color':'Your Color','classic.setup.color.white':'White','classic.setup.color.black':'Black','classic.setup.license':'license','classic.setup.source':'source code','classic.setup.start':'Start Game','classic.promotion.kicker':'PROMOTION','classic.promotion.title':'Choose a piece',
  'classic.mode.local':'Local game · two players','classic.mode.ai':'Stockfish 18 lite · {profile} · ≈{elo} Elo{fallback}','classic.mode.fallback':' · fallback move','classic.state.check':'Check','classic.state.checkmate':'Checkmate — {side} wins','classic.state.stalemate':'Stalemate — draw','classic.state.draw50':'Draw — 50-move rule','classic.state.drawThreefold':'Draw — threefold repetition','classic.state.drawInsufficient':'Draw — insufficient material','classic.state.continues':'Game in progress','classic.result.checkmateTitle':'Checkmate','classic.result.checkmateText':'{side} won.','classic.result.stalemateTitle':'Stalemate','classic.result.stalemateText':'No legal moves and no check. Draw.','classic.result.drawTitle':'Draw','classic.result.draw50Text':'Fifty moves passed without a pawn move or capture.','classic.result.drawThreefoldText':'The same position occurred three times.','classic.result.drawInsufficientText':'There is insufficient material on the board to checkmate.','classic.turn.complete':'Game complete','classic.turn.active':'{side} to move','classic.status.thinking':'Computer is thinking…','classic.status.animating':'Move in progress','classic.summary.choosing':' are choosing a move.','classic.summary.checked':' are in check. The King must be defended.','classic.summary.turn':' to move.'
});

export const CLASSIC_UI_MESSAGES = Object.freeze({ ru: RU, en: EN });

function interpolate(message, params = {}) {
  return String(message).replace(/\{([a-zA-Z0-9_]+)\}/g, (match, name) => Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : match);
}

export function classicT(language, key, params = {}) {
  const normalized = language === 'en' ? 'en' : 'ru';
  const message = CLASSIC_UI_MESSAGES[normalized]?.[key] ?? CLASSIC_UI_MESSAGES.ru[key];
  return message === undefined ? `[missing:${key}]` : interpolate(message, params);
}
