const EN_EXACT = Object.freeze({
  'Главное меню': 'Main Menu',
  'Главное меню RPChess': 'RPChess Main Menu',
  'Новая игра': 'New Game',
  'Новая партия': 'New Game',
  'Продолжить': 'Continue',
  'Продолжить путь': 'Continue Journey',
  'Вернуться к отряду': 'Return to Roster',
  'Вернуться в поселение': 'Return to Settlement',
  'В путь': 'Set Out',
  'Начать путешествие': 'Begin Journey',
  'Загрузка пути…': 'Loading route…',
  'Настройки': 'Settings',
  'Язык': 'Language',
  'Назад': 'Back',
  'Закрыть': 'Close',
  'Закрыть настройки': 'Close settings',
  'Закрыть выбор языка': 'Close language selection',
  'Доступные языки': 'Available languages',

  'ТЕКУЩИЙ ЗАБЕГ': 'CURRENT RUN',
  'Отряд': 'Roster',
  'Отряд текущего забега': 'Current run roster',
  'Ваш отряд': 'Your Roster',
  'Фильтр состояния фигур': 'Piece status filter',
  'ВСЕ': 'ALL',
  'ЗДОРОВЫ': 'HEALTHY',
  'РАНЕНЫ': 'WOUNDED',
  'ПОГИБШИЕ': 'DEAD',
  'ЗДОРОВ': 'HEALTHY',
  'ТЯЖЕЛО РАНЕН': 'SEVERELY WOUNDED',
  'ПОГИБ': 'DEAD',
  'КОРОЛЬ ОТРЯДА': 'ROSTER KING',
  'ИМЕННАЯ ФИГУРА': 'NAMED PIECE',
  'КОМАНДНЫЕ ОЧКИ': 'COMMAND POINTS',
  'Командные очки': 'Command points',
  'Не может участвовать в сражениях до лечения.': 'Cannot take part in battles until healed.',
  'Погиб в текущем забеге и остаётся в памяти отряда.': 'Died during this run and remains in the roster’s memory.',
  'В этом забеге пока никто не погиб.': 'No one has died in this run yet.',
  'Нет фигур с таким состоянием.': 'No pieces have this status.',

  'Пешка': 'Pawn',
  'Конь': 'Knight',
  'Слон': 'Bishop',
  'Ладья': 'Rook',
  'Ферзь': 'Queen',
  'Король': 'King',
  'Белые': 'White',
  'Чёрные': 'Black',
  'Случайно': 'Random',

  'Железные Марши': 'Iron Marches',
  'Светлый Синод': 'Luminous Synod',
  'Хранитель Клятвы': 'Oathkeeper',
  'Альдрик Стена': 'Aldric the Wall',
  'Мара Цепь': 'Mara Chain',
  'Немея Перо': 'Nemea Quill',
  'Брат Орелл': 'Brother Orell',
  'Ваэль Молот': 'Vael Hammer',
  'Последний хранитель древней присяги Железных Маршей. После падения родовой крепости он покинул её стены и собрал вокруг себя тех, кто ещё верит, что данное слово важнее трона.': 'The last keeper of an ancient Iron Marches oath. After his ancestral fortress fell, he left its walls and gathered those who still believe a given word matters more than a throne.',
  'Ветеран пограничных гарнизонов, привыкший держать линию до последнего.': 'A veteran of the border garrisons, accustomed to holding the line to the very end.',
  'Упрямая воительница из низших рядов, для которой каждый шаг вперёд имеет цену.': 'A stubborn warrior from the lower ranks, for whom every step forward has a price.',
  'Учёная-путешественница, присоединившаяся к отряду ради истории, которую ещё предстоит написать.': 'A travelling scholar who joined the roster for a story that has yet to be written.',
  'Жрец-кузнец, читающий поле боя так же внимательно, как линии на раскалённом металле.': 'A priest-smith who reads a battlefield as carefully as the lines in glowing metal.',
  'Тяжёлый всадник, предпочитающий решительный манёвр долгому ожиданию.': 'A heavy cavalryman who prefers a decisive manoeuvre to a long wait.',

  'Подготовка к стычке': 'Skirmish Preparation',
  'ПОДГОТОВКА К СТЫЧКЕ': 'SKIRMISH PREPARATION',
  'Стычка': 'Skirmish',
  'Оценка угрозы': 'Threat estimate',
  'Точный состав противника неизвестен': 'The exact enemy composition is unknown',
  'Доступные бойцы': 'Available Fighters',
  'Кликните по здоровой фигуре, чтобы добавить или убрать её.': 'Click a healthy piece to add or remove it.',
  'В ЭТУ БИТВУ': 'FOR THIS FIGHT',
  'Боевой отряд': 'Battle Roster',
  'Автоматическая расстановка': 'Automatic Formation',
  'Предпросмотр автоматической расстановки': 'Automatic formation preview',
  'Параметры боевого отряда': 'Battle roster parameters',
  'ФИГУРЫ': 'PIECES',
  'КОМАНДОВАНИЕ': 'COMMAND',
  'Начать стычку': 'Start Skirmish',
  'Итоги стычки': 'Skirmish Results',
  'СТЫЧКА ЗАВЕРШЕНА': 'SKIRMISH COMPLETE',
  'ИТОГ': 'RESULT',
  'Выжили': 'Survivors',
  'Тяжело ранены': 'Severely Wounded',
  'Погибли': 'Dead',

  'Подготовка к битве': 'Battle Preparation',
  'ПОДГОТОВКА К БИТВЕ': 'BATTLE PREPARATION',
  'Битва': 'Battle',
  'ПОЛНАЯ АРМИЯ · 16 ФИГУР · 39 ОЧКОВ': 'FULL ARMY · 16 PIECES · 39 POINTS',
  'Персональные бойцы': 'Named Fighters',
  'Здоровые бойцы выбраны по умолчанию. Снимите тех, кем не хотите рисковать.': 'Healthy fighters are selected by default. Deselect anyone you do not want to risk.',
  'Ваша полная армия': 'Your Full Army',
  'СТАНДАРТНЫЙ КОМПЛЕКТ': 'STANDARD SET',
  'Ваша армия': 'Your Army',
  'Персональные бойцы заменяют временные фигуры того же типа.': 'Named fighters replace temporary pieces of the same type.',
  'Стандартная стартовая армия': 'Standard starting army',
  'Параметры полной армии': 'Full army parameters',
  'ИМЕННЫЕ': 'NAMED',
  'АРМИЯ': 'ARMY',
  'МАТЕРИАЛ': 'MATERIAL',
  '16 ФИГУР': '16 PIECES',
  '39 ОЧКОВ': '39 POINTS',
  'Начать битву': 'Start Battle',
  'Итоги битвы': 'Battle Results',
  'БИТВА ЗАВЕРШЕНА': 'BATTLE COMPLETE',
  'ЗАБЕГ ЗАВЕРШЁН': 'RUN ENDED',
  'КОРОЛЬ ПОГИБ': 'THE KING IS DEAD',
  'Сражений завершено': 'Battles Completed',
  'Сохранили строй': 'Still Fit to Fight',
  'Состав нельзя использовать в этой битве.': 'This roster cannot be used in this battle.',
  'Король недоступен. Забег не может продолжаться.': 'The King is unavailable. The run cannot continue.',
  'Король обязан участвовать в каждой битве.': 'The King must take part in every battle.',
  'Эта фигура сейчас не может участвовать в битве.': 'This piece cannot take part in the battle right now.',
  '♔ КОРОЛЬ · ОБЯЗАТЕЛЕН': '♔ KING · REQUIRED',

  'Классические шахматы': 'Classic Chess',
  'Партия': 'Game',
  'Локальная партия': 'Local Game',
  'Взятые фигуры и перевес по материалу': 'Captured pieces and material advantage',
  'Фигуры, взятые белыми': 'Pieces captured by White',
  'Фигуры, взятые чёрными': 'Pieces captured by Black',
  'Белые начинают партию.': 'White starts the game.',
  'Ход белых': 'White to move',
  'Ход чёрных': 'Black to move',
  'Партия началась': 'Game started',
  'Шахматная доска 8 на 8': '8 by 8 chessboard',
  'Компьютер думает…': 'Computer is thinking…',
  'Ходы партии': 'Game moves',
  'Ходы': 'Moves',
  'Ходов пока нет': 'No moves yet',
  'НОВАЯ ПАРТИЯ': 'NEW GAME',
  'Выберите соперника': 'Choose an Opponent',
  'Режим': 'Mode',
  'Против компьютера': 'Against Computer',
  'Сила соперника': 'Opponent Strength',
  'Ваш цвет': 'Your Color',
  'Начать партию': 'Start Game',
  'ПРЕВРАЩЕНИЕ': 'PROMOTION',
  'Выберите фигуру': 'Choose a Piece',
  'Новичок I · ≈400 Elo': 'Beginner I · ≈400 Elo',
  'Новичок II · ≈600 Elo': 'Beginner II · ≈600 Elo',
  'Любитель · ≈800 Elo': 'Amateur · ≈800 Elo',
  'Любитель+ · ≈1000 Elo': 'Amateur+ · ≈1000 Elo',
  'Клубный новичок · ≈1200 Elo': 'Club Beginner · ≈1200 Elo',
  'Клубный · ≈1400 Elo': 'Club Player · ≈1400 Elo',
  'Сильный клубный · ≈1600 Elo': 'Strong Club Player · ≈1600 Elo',
  'Эксперт · ≈1800 Elo': 'Expert · ≈1800 Elo',
  'Мастерский · ≈2000 Elo': 'Master Level · ≈2000 Elo',
  'Мастер+ · ≈2200 Elo': 'Master+ · ≈2200 Elo',
  'Очень сильный · ≈2400 Elo': 'Very Strong · ≈2400 Elo',
  'Гроссмейстер · ≈2600 Elo': 'Grandmaster · ≈2600 Elo',
  'лицензия': 'license',
  'исходный код': 'source code',

  'Выбор следующего пути': 'Choose the Next Route',
  'МОЩЬ': 'POWER',
  'УГРОЗА': 'THREAT',
  'Мощь игрока': 'Player power',
  'Ресурсы текущего забега': 'Current run resources',
  'Золото': 'Gold',
  'Припасы': 'Supplies',
  'Три возможных пути': 'Three possible routes',
  'ЛЕЧЕНИЕ · НАЙМ · СНАБЖЕНИЕ': 'HEALING · HIRING · SUPPLIES',
  'СЛОЖНОСТЬ': 'DIFFICULTY',
  'Тренировка': 'Training',
  'Недоступно: для стычки нужен хотя бы один здоровый герой кроме короля.': 'Unavailable: a skirmish requires at least one healthy hero besides the King.',
  'ПЕРЕХОД': 'TRAVEL',
  'ГОЛОД': 'STARVATION',

  'Поселение': 'Settlement',
  'БЕЗОПАСНАЯ ОСТАНОВКА': 'SAFE STOP',
  'Здесь можно привести отряд в порядок перед следующей дорогой.': 'Here you can put the roster back in order before the next journey.',
  'ЗНАХАРКА': 'HEALER',
  'Знахарка': 'Healer',
  'Тяжело раненые бойцы могут вернуться в строй за золото.': 'Severely wounded fighters can return to duty for gold.',
  'ТАВЕРНА': 'TAVERN',
  'Таверна': 'Tavern',
  'Три путника готовы присоединиться к походу. Предложения этого поселения не меняются.': 'Three travellers are ready to join the campaign. This settlement’s offers do not change.',
  'СНАБЖЕНИЕ': 'SUPPLIES',
  'Рынок': 'Market',
  'Запасы ограничены, но каждый купленный припас остаётся с отрядом.': 'Stock is limited, but every purchased supply stays with the roster.',
  'Выход из поселения не расходует дополнительный припас.': 'Leaving the settlement does not consume an additional supply.',
  'Все бойцы готовы к пути.': 'All fighters are ready to travel.',
  'Лечить': 'Heal',
  'В отряде': 'In Roster',
  'Нанять': 'Hire',
  'ОСТАЛОСЬ': 'REMAINING',
  'за 1 припас': 'for 1 supply',
  'Распродано': 'Sold Out',
  'Купить припас': 'Buy Supply',
  'ЛЕЧЕНИЕ': 'HEALING',
  'НОВЫЙ БОЕЦ': 'NEW FIGHTER',

  'Дорожное событие': 'Road Event',
  'СОБЫТИЕ': 'EVENT',
  'ИСХОД': 'OUTCOME',
  'ПРОДОЛЖИТЬ ПУТЬ': 'CONTINUE JOURNEY',
  'УСПЕХ': 'SUCCESS',
  'НЕУДАЧА': 'FAILURE',
  'ГАРАНТИРОВАННО': 'GUARANTEED',
  'Гарантированный исход': 'Guaranteed outcome',
  'Ничего не изменилось.': 'Nothing changed.',
  'ИТОГИ ЗАБЕГА': 'RUN RESULTS',
  'К БИТВЕ': 'TO BATTLE',
  'К СТЫЧКЕ': 'TO SKIRMISH',
  'Именной герой': 'Named hero',
  'Смешанное': 'Mixed',
  'КОРОЛЬ МОЖЕТ ПОГИБНУТЬ': 'THE KING MAY DIE',
  'МОЖЕТ НАЧАТЬСЯ СТЫЧКА': 'MAY START A SKIRMISH',
  'МОЖЕТ НАЧАТЬСЯ БИТВА': 'MAY START A BATTLE',
  'РИСК РАНЕНИЯ': 'WOUND RISK',
  'РИСК ДЛЯ КОРОЛЯ': 'RISK TO THE KING',
  'РАНЕН': 'WOUNDED',

  'Музыка': 'Music',
  'Звуки': 'Sound',
  'Уменьшить анимации': 'Reduce Motion'
});

const EN_PATTERNS = Object.freeze([
  [/^Неделя\s+(\d+)$/u, (_m, n) => `Week ${n}`],
  [/^(\d+)\s+в строю$/u, (_m, n) => `${n} fit for duty`],
  [/^Сила:\s*примерно\s*(.+)$/u, (_m, value) => `Strength: about ${value}`],
  [/^Сила:\s*(.+)$/u, (_m, value) => `Strength: ${value}`],
  [/^Сложность\s+(\d+)\s+из\s+12$/u, (_m, n) => `Difficulty ${n} of 12`],
  [/^Угроза\s+(\d+)\s+из\s+12$/u, (_m, n) => `Threat ${n} of 12`],
  [/^Тактика противника:\s*(.+)$/u, (_m, value) => `Enemy tactic: ${value}`],
  [/^Стоимость пути:\s*(\d+)\s+припас\. Припасов нет — при переходе сработает голод\.$/u, (_m, n) => `Travel cost: ${n} supply. No supplies remain — starvation will trigger on travel.`],
  [/^Стоимость пути:\s*(\d+)\s+припас\.$/u, (_m, n) => `Travel cost: ${n} supply.`],
  [/^Награда за победу:\s*(\d+)\s+золота$/u, (_m, n) => `Victory reward: ${n} gold`],
  [/^(\d+)%\s+УСПЕХА$/u, (_m, n) => `${n}% SUCCESS`],
  [/^Бросок:\s*(\d+)\s*·\s*шанс:\s*(\d+)%$/u, (_m, roll, chance) => `Roll: ${roll} · chance: ${chance}%`],
  [/^🔒\s+(.+)\s+—\s+ПОГИБ$/u, (_m, name) => `🔒 ${name} — DEAD`],
  [/^🔒\s+(.+)\s+—\s+РАНЕН$/u, (_m, name) => `🔒 ${name} — WOUNDED`],
  [/^ВСЕ\s+(\d+)\s+СЛОТА\s+·\s+(.+)\s+ЗАНЯТЫ$/u, (_m, n, type) => `ALL ${n} SLOTS · ${legacyTranslate(type, 'en')} FULL`]
]);

function translateExact(value) {
  return EN_EXACT[value] || null;
}

function legacyTranslate(value, language = 'ru') {
  const source = String(value ?? '');
  if (language !== 'en' || !source) return source;
  const direct = translateExact(source);
  if (direct) return direct;
  for (const [pattern, replacer] of EN_PATTERNS) {
    if (pattern.test(source)) return source.replace(pattern, replacer);
  }
  return source;
}

export { EN_EXACT, EN_PATTERNS, legacyTranslate };
