export const LANGUAGES = Object.freeze([
  Object.freeze({ code: 'ru', label: 'Русский' }),
  Object.freeze({ code: 'en', label: 'English' })
]);

export const UI_MESSAGES = Object.freeze({
  ru: Object.freeze({
    'menu.ariaLabel': 'Главное меню RPChess',
    'menu.actionsLabel': 'Главное меню',
    'menu.newGame': 'Новая игра',
    'menu.continue': 'Продолжить',
    'menu.settings': 'Настройки',
    'menu.language': 'Язык',
    'settings.title': 'Настройки',
    'settings.close': 'Закрыть настройки',
    'settings.music': 'Музыка',
    'settings.sfx': 'Звуки',
    'settings.reducedMotion': 'Уменьшить анимации',
    'language.kicker': 'ЯЗЫК',
    'language.title': 'Язык',
    'language.close': 'Закрыть выбор языка',
    'language.optionsLabel': 'Доступные языки',
    'language.current': 'Выбран: {language}',
    'common.back': 'Назад',
    'settlement.ariaLabel': 'Поселение',
    'settlement.kicker': 'БЕЗОПАСНАЯ ОСТАНОВКА',
    'settlement.title': 'Поселение',
    'settlement.subtitle': 'Здесь можно привести отряд в порядок перед следующей дорогой.',
    'settlement.healer.title': 'Знахарка',
    'settlement.healer.intro': 'Тяжело раненые бойцы могут вернуться в строй за золото.',
    'settlement.healer.empty': 'Все бойцы готовы к пути.',
    'settlement.healer.action': 'Лечить',
    'settlement.tavern.title': 'Таверна',
    'settlement.tavern.intro': 'Три путника готовы присоединиться к походу. Предложения этого поселения не меняются.',
    'settlement.tavern.inRoster': 'В отряде',
    'settlement.tavern.hire': 'Нанять',
    'settlement.market.title': 'Рынок',
    'settlement.market.for': 'за',
    'settlement.market.buy': 'Купить',
    'settlement.market.soldOut': 'Распродано',
    'settlement.footer': 'Выход из поселения не расходует дополнительный припас.',
    'settlement.continue': 'Продолжить путь',
    'resources.ariaLabel': 'Ресурсы текущего забега',
    'resources.gold': 'ЗОЛОТО',
    'resources.supplies': 'ПРИПАСЫ',
    'resources.goldDelta': 'ЗОЛОТА',
    'resources.suppliesDelta': 'ПРИПАС',
    'resources.reward': 'НАГРАДА',
    'resources.combatReward': 'НАГРАДА ЗА БОЙ',
    'resources.healing': 'ЛЕЧЕНИЕ',
    'resources.newFighter': 'НОВЫЙ БОЕЦ',
    'resources.supplyPurchase': 'СНАБЖЕНИЕ'
  }),
  en: Object.freeze({
    'menu.ariaLabel': 'RPChess main menu',
    'menu.actionsLabel': 'Main menu',
    'menu.newGame': 'New Game',
    'menu.continue': 'Continue',
    'menu.settings': 'Settings',
    'menu.language': 'Language',
    'settings.title': 'Settings',
    'settings.close': 'Close settings',
    'settings.music': 'Music',
    'settings.sfx': 'Sound',
    'settings.reducedMotion': 'Reduce motion',
    'language.kicker': 'LANGUAGE',
    'language.title': 'Language',
    'language.close': 'Close language selection',
    'language.optionsLabel': 'Available languages',
    'language.current': 'Selected: {language}',
    'common.back': 'Back',
    'settlement.ariaLabel': 'Settlement',
    'settlement.kicker': 'SAFE STOP',
    'settlement.title': 'Settlement',
    'settlement.subtitle': 'Restore the roster before returning to the road.',
    'settlement.healer.title': 'Healer',
    'settlement.healer.intro': 'Severely wounded fighters can return to action for Gold.',
    'settlement.healer.empty': 'All fighters are ready for the road.',
    'settlement.healer.action': 'Heal',
    'settlement.tavern.title': 'Tavern',
    'settlement.tavern.intro': 'Three travellers are ready to join the journey. This settlement keeps the same offers.',
    'settlement.tavern.inRoster': 'In roster',
    'settlement.tavern.hire': 'Hire',
    'settlement.market.title': 'Market',
    'settlement.market.for': 'for',
    'settlement.market.buy': 'Buy',
    'settlement.market.soldOut': 'Sold out',
    'settlement.footer': 'Leaving the settlement does not spend another Supply.',
    'settlement.continue': 'Continue Journey',
    'resources.ariaLabel': 'Current run resources',
    'resources.gold': 'GOLD',
    'resources.supplies': 'SUPPLIES',
    'resources.goldDelta': 'GOLD',
    'resources.suppliesDelta': 'SUPPLY',
    'resources.reward': 'REWARD',
    'resources.combatReward': 'COMBAT REWARD',
    'resources.healing': 'HEALING',
    'resources.newFighter': 'NEW FIGHTER',
    'resources.supplyPurchase': 'SUPPLIES'
  })
});