import { PIECE_VALUES } from './roster-data.mjs';
const BATTLE_PIECE_COUNT=16,BATTLE_ARMY_POINTS=39,STANDARD_FEN='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const TYPE_CODE=Object.freeze({pawn:'p',knight:'n',bishop:'b',rook:'r',queen:'q',king:'k'}),SLOT_CAPACITY=Object.freeze({king:1,queen:1,rook:2,bishop:2,knight:2,pawn:8}),TYPE_LABELS=Object.freeze({pawn:'Пешка',knight:'Конь',bishop:'Слон',rook:'Ладья',queen:'Ферзь',king:'Король'});
const STANDARD_SLOTS=Object.freeze({w:Object.freeze({rook:Object.freeze(['a1','h1']),knight:Object.freeze(['b1','g1']),bishop:Object.freeze(['c1','f1']),queen:Object.freeze(['d1']),king:Object.freeze(['e1']),pawn:Object.freeze(['a2','b2','c2','d2','e2','f2','g2','h2'])}),b:Object.freeze({rook:Object.freeze(['a8','h8']),knight:Object.freeze(['b8','g8']),bishop:Object.freeze(['c8','f8']),queen:Object.freeze(['d8']),king:Object.freeze(['e8']),pawn:Object.freeze(['a7','b7','c7','d7','e7','f7','g7','h7'])})});
const BATTLE_TIERS=Object.freeze({1:Object.freeze({label:'Пограничное войско',elo:700,tactic:'Неопытный'}),2:Object.freeze({label:'Армия Чёрного Утёса',elo:1000,tactic:'Осторожный'}),3:Object.freeze({label:'Железный гарнизон',elo:1300,tactic:'Уверенный'}),4:Object.freeze({label:'Королевская армия',elo:1700,tactic:'Опасный'}),5:Object.freeze({label:'Легион Чёрной Короны',elo:2100,tactic:'Безжалостный'})});
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function hashSeed(input){let h=2166136261;for(const c of String(input)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function takeTravelEncounterOverride(expectedType){if(typeof globalThis==='undefined')return null;const o=globalThis.RPChessTravelEncounterOverride;if(!o||o.type!==expectedType||!o.seed)return null;try{delete globalThis.RPChessTravelEncounterOverride;}catch{globalThis.RPChessTravelEncounterOverride=null;}return o;}
function createBattleEncounter({seed='rpchess-battle',stars=2}={}){const o=takeTravelEncounterOverride('battle'),resolvedSeed=o?.seed||seed,s=clamp(Math.round(Number(o?.stars??stars)||2),1,5),tier=BATTLE_TIERS[s];return Object.freeze({id:`battle-${hashSeed(resolvedSeed).toString(36)}-${s}`,seed:String(resolvedSeed),stars:s,label:tier.label,aiElo:tier.elo,tactic:tier.tactic,description:s<=2?'Впереди развёрнута полноценная армия. Победа решится по классическим шахматным правилам.':s===3?'Опытный противник вывел полный комплект фигур и готов к открытому сражению.':'Сильная армия заняла поле. На доске не будет места для ошибки.'});}
function combatEligible(character){return Boolean(character&&(character.status==='healthy'||(character.isRunKing&&character.status==='wounded')));}
function selectedMembers(roster,selectedIds){const selected=new Set(selectedIds||[]);return(roster||[]).filter((c)=>selected.has(c.id));}
function selectedTypeCounts(roster,selectedIds){const counts={king:0,queen:0,rook:0,bishop:0,knight:0,pawn:0};for(const c of selectedMembers(roster,selectedIds))if(Object.prototype.hasOwnProperty.call(counts,c.pieceType))counts[c.pieceType]++;return counts;}
function validateBattleSelection(roster,selectedIds){const ids=[...new Set(selectedIds||[])],byId=new Map((roster||[]).map((c)=>[c.id,c])),king=(roster||[]).find((c)=>c.isRunKing);if(!king)return{ok:false,reason:'missing_king'};if(!combatEligible(king))return{ok:false,reason:'king_unavailable'};if(!ids.includes(king.id))return{ok:false,reason:'king_required'};for(const id of ids){const c=byId.get(id);if(!c)return{ok:false,reason:'unknown_character',id};if(!combatEligible(c))return{ok:false,reason:'character_unavailable',id};if(c.pieceType==='king'&&!c.isRunKing)return{ok:false,reason:'invalid_king',id};}const members=selectedMembers(roster,ids),typeCounts=selectedTypeCounts(roster,ids);for(const [pieceType,count] of Object.entries(typeCounts))if(count>SLOT_CAPACITY[pieceType])return{ok:false,reason:'slot_limit',pieceType,count,capacity:SLOT_CAPACITY[pieceType],members,typeCounts};return{ok:true,members,typeCounts,count:members.length};}
function defaultBattleSelection(roster){const eligible=(roster||[]).filter(combatEligible),king=eligible.find((c)=>c.isRunKing);if(!king)return[];const selected=[king.id],counts={king:1,queen:0,rook:0,bishop:0,knight:0,pawn:0};for(const c of eligible){if(c.id===king.id||c.pieceType==='king')continue;const capacity=SLOT_CAPACITY[c.pieceType]||0;if((counts[c.pieceType]||0)>=capacity)continue;selected.push(c.id);counts[c.pieceType]=(counts[c.pieceType]||0)+1;}return selected;}
function formationFor(color,roster=[],selectedIds=[]){const validation=color==='w'?validateBattleSelection(roster,selectedIds):null;if(color==='w'&&!validation.ok)throw new Error(`Invalid Battle selection: ${validation.reason}`);const selected=color==='w'?validation.members:[],byType=new Map();for(const type of Object.keys(SLOT_CAPACITY))byType.set(type,selected.filter((c)=>c.pieceType===type));const placements=[];for(const pieceType of ['rook','knight','bishop','queen','king','pawn']){const chars=byType.get(pieceType)||[],slots=STANDARD_SLOTS[color][pieceType];slots.forEach((square,index)=>{const c=chars[index]||null;placements.push({id:c?.id||null,name:c?.name||`Временная фигура · ${TYPE_LABELS[pieceType]}`,pieceType,type:TYPE_CODE[pieceType],color,square,personalized:Boolean(c)});});}return placements;}
function createBattlePlan({roster,selectedIds,encounter}={}){const validation=validateBattleSelection(roster,selectedIds);if(!validation.ok)throw new Error(`Invalid Battle selection: ${validation.reason}`);const resolved=encounter||createBattleEncounter();return{encounter:resolved,selectedIds:validation.members.map((m)=>m.id),participants:validation.members.map((m)=>m.id),playerFormation:formationFor('w',roster,selectedIds),enemyFormation:formationFor('b'),fullArmyPieces:BATTLE_PIECE_COUNT,fullArmyPoints:BATTLE_ARMY_POINTS,fen:STANDARD_FEN};}
function applyBattleOutcome(run,{capturedIds=[],status=null,playerColor='w',participantIds=[]}={}){const captured=new Set(capturedIds||[]),participants=[...new Set(participantIds||[])],lost=status?.type==='checkmate'&&status.winner&&status.winner!==playerColor;let kingDied=false;const roster=(run?.roster||[]).map((c)=>{if(c.isRunKing&&lost){kingDied=true;return{...c,status:'dead'};}if(!c.isRunKing&&captured.has(c.id)&&c.status==='healthy')return{...c,status:'wounded'};return{...c};}),woundedIds=roster.filter((c)=>captured.has(c.id)&&!c.isRunKing&&c.status==='wounded').map((c)=>c.id);return{...run,roster,ended:Boolean(run?.ended||kingDied),endReason:kingDied?'king_dead':(run?.endReason||null),lastBattle:{result:status?.type||'unknown',winner:status?.winner||null,participants,woundedIds,kingDied}};}
export {BATTLE_PIECE_COUNT,BATTLE_ARMY_POINTS,STANDARD_FEN,SLOT_CAPACITY,STANDARD_SLOTS,BATTLE_TIERS,combatEligible,createBattleEncounter,selectedTypeCounts,validateBattleSelection,defaultBattleSelection,formationFor,createBattlePlan,applyBattleOutcome};
