// Generated from human-approved Events v1 + approved Events v4 expansion: 500 events / 2114 choices.
import { normalizeRaceTag } from './race-assets.mjs';
import { EVENTS_01 } from './events/event-data-01.mjs';
import { EVENTS_02 } from './events/event-data-02.mjs';
import { EVENTS_03 } from './events/event-data-03.mjs';
import { EVENTS_04 } from './events/event-data-04.mjs';
import { EVENTS_05 } from './events/event-data-05.mjs';
import { EVENTS_06 } from './events/event-data-06.mjs';
import { EVENTS_07 } from './events/event-data-07.mjs';
import { EVENTS_08 } from './events/event-data-08.mjs';
import { EVENTS_09 } from './events/event-data-09.mjs';
import { EVENTS_10 } from './events/event-data-10.mjs';
import { EVENTS_V4_01 } from './events/event-data-v4-01.mjs';
import { EVENTS_V4_02 } from './events/event-data-v4-02.mjs';
import { EVENTS_V4_03 } from './events/event-data-v4-03.mjs';
import { EVENTS_V4_04 } from './events/event-data-v4-04.mjs';
import { EVENTS_V4_05 } from './events/event-data-v4-05.mjs';
import { EVENTS_V4C_01 } from './events/event-data-v4c-01.mjs';
import { EVENTS_V4C_02 } from './events/event-data-v4c-02.mjs';
import { EVENTS_V4C_03 } from './events/event-data-v4c-03.mjs';
import { EVENTS_V4C_04 } from './events/event-data-v4c-04.mjs';
import { EVENTS_V4C_05 } from './events/event-data-v4c-05.mjs';
import { EVENTS_V4C_06 } from './events/event-data-v4c-06.mjs';
import { EVENTS_V4C_07 } from './events/event-data-v4c-07.mjs';
import { EVENTS_V4C_08 } from './events/event-data-v4c-08.mjs';
import { EVENTS_V4C_09 } from './events/event-data-v4c-09.mjs';
import { EVENTS_V4C_10 } from './events/event-data-v4c-10.mjs';
import { EVENTS_V4C_11 } from './events/event-data-v4c-11.mjs';
import { EVENTS_V4C_12 } from './events/event-data-v4c-12.mjs';
import { EVENTS_V4C_13 } from './events/event-data-v4c-13.mjs';
import { EVENTS_V4C_14 } from './events/event-data-v4c-14.mjs';
import { EVENTS_V4C_15 } from './events/event-data-v4c-15.mjs';
import { EVENTS_V4C_16 } from './events/event-data-v4c-16.mjs';
import { EVENTS_V4C_17 } from './events/event-data-v4c-17.mjs';
import { EVENTS_V4C_18 } from './events/event-data-v4c-18.mjs';
import { EVENTS_V4C_19 } from './events/event-data-v4c-19.mjs';
import { EVENTS_V4C_20 } from './events/event-data-v4c-20.mjs';
import { EVENTS_V4C_21 } from './events/event-data-v4c-21.mjs';
import { EVENTS_V4C_22 } from './events/event-data-v4c-22.mjs';
import { EVENTS_V4C_23 } from './events/event-data-v4c-23.mjs';
import { EVENTS_V4C_24 } from './events/event-data-v4c-24.mjs';
import { EVENTS_V4C_25 } from './events/event-data-v4c-25.mjs';
const RAW_EVENTS=[...EVENTS_01,...EVENTS_02,...EVENTS_03,...EVENTS_04,...EVENTS_05,...EVENTS_06,...EVENTS_07,...EVENTS_08,...EVENTS_09,...EVENTS_10,...EVENTS_V4_01,...EVENTS_V4_02,...EVENTS_V4_03,...EVENTS_V4_04,...EVENTS_V4_05,...EVENTS_V4C_01,...EVENTS_V4C_02,...EVENTS_V4C_03,...EVENTS_V4C_04,...EVENTS_V4C_05,...EVENTS_V4C_06,...EVENTS_V4C_07,...EVENTS_V4C_08,...EVENTS_V4C_09,...EVENTS_V4C_10,...EVENTS_V4C_11,...EVENTS_V4C_12,...EVENTS_V4C_13,...EVENTS_V4C_14,...EVENTS_V4C_15,...EVENTS_V4C_16,...EVENTS_V4C_17,...EVENTS_V4C_18,...EVENTS_V4C_19,...EVENTS_V4C_20,...EVENTS_V4C_21,...EVENTS_V4C_22,...EVENTS_V4C_23,...EVENTS_V4C_24,...EVENTS_V4C_25];
const EVENT_CATALOG=Object.freeze(RAW_EVENTS.map((event)=>Object.freeze({...event,raceTag:normalizeRaceTag(event.raceTag||event.race)})));
const EVENT_BY_ID=Object.freeze(Object.fromEntries(EVENT_CATALOG.map((event)=>[event.id,event])));
const EVENT_IDS=Object.freeze(EVENT_CATALOG.map((event)=>event.id));
function eventById(id){return EVENT_BY_ID[id]||null;}
export {EVENT_CATALOG,EVENT_BY_ID,EVENT_IDS,eventById};
