import { PIECE_VALUES } from './roster-data.mjs';
const MAX_SKIRMISH_PIECES=16,MAX_SKIRMISH_POINTS=39,TYPE_CODE=Object.freeze({pawn:'p',knight:'n',bishop:'b',rook:'r',queen:'q',king:'k'}),CODE_TYPE=Object.freeze({p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'}),FILES='abcdefgh';
const ENCOUNTER_TIERS=Object.freeze({1:Object.freeze({label:'Дорожный дозор',stars:1,threat:'6–12',elo:600,tactic:'Неопытный'}),2:Object.freeze({label:'Засадный отряд',stars:2,threat:'10–18',elo:900,tactic:'Осторожный'}),3:Object.freeze({label:'Закалённая стража',stars:3,threat:'16–26',elo:1200,tactic:'Уверенный'}),4:Object.freeze({label:'Чёрная когорта',stars:4,threat:'23–33',elo:1600,tactic:'Опасный'}),5:Object.freeze({label:'Королевская охота',stars:5,threat:'31–39',elo:2000,tactic:'Безжалостный'})});
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function hashSeed(input){let h=2166136261;for(const c of String(input)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}function seededRandom(seed){let v=hashSeed(seed)||1;return()=>{v+=0x6D2B79F5;let t=v;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function takeTravelEncounterOverride(expectedType){if(typeof globalThis==='undefined')return null;const o=globalThis.RPChessTravelEncounterOverride;if(!o||o.type!==expectedType||!o.seed)return null;try{delete globalThis.RPChessTravelEncounterOverride;}catch{globalThis.RPChessTravelEncounterOverride=null;}return o;}
function createEncounter({seed='rpchess-skirmish',stars=2}={}){const o=takeTravelEncounterOverride('skirmish'),resolvedSeed=o?.seed||seed,resolvedStars=o?.stars??stars,s=clamp(Math.round(Number(resolvedStars)||2),1,5),tier=ENCOUNTER_TIERS[s];return Object.freeze({id:`skirmish-${hashSeed(resolvedSeed).toString(36)}-${s}`,seed:String(resolvedSeed),stars:s,label:tier.label,threat:tier.threat,aiElo:tier.elo,tactic:tier.tactic,description:s<=2?'Небольшая вражеская группа перекрывает путь.':s===3?'Опытный противник занял выгодную позицию впереди.':'Сильная армия ждёт открытого столкновения.'});}
function combatEligible(character){return Boolean(character&&(character.status==='healthy'||(character.isRunKing&&character.status==='wounded')));}
function selectionSummary(roster,selectedIds){const selected=new Set(selectedIds||[]),members=(roster||[]).filter((c)=>selected.has(c.id));return{members,count:members.length,points:members.reduce((s,c)=>s+(PIECE_VALUES[c.pieceType]??c.commandCost??0),0)};}
function validateSelection(roster,selectedIds){const ids=[...new Set(selectedIds||[])],byId=new Map((roster||[]).map((c)=>[c.id,c])),king=(roster||[]).find((c)=>c.isRunKing);if(!king)return{ok:false,reason:'missing_king'};if(!combatEligible(king))return{ok:false,reason:'king_unavailable'};if(!ids.includes(king.id))return{ok:false,reason:'king_required'};for(const id of ids){const c=byId.get(id);if(!c)return{ok:false,reason:'unknown_character',id};if(!combatEligible(c))return{ok:false,reason:'character_unavailable',id};}const summary=selectionSummary(roster,ids);if(summary.count>MAX_SKIRMISH_PIECES)return{ok:false,reason:'piece_limit',...summary};if(summary.points>MAX_SKIRMISH_POINTS)return{ok:false,reason:'point_limit',...summary};return{ok:true,...summary};}
function defaultCombatSelection(roster){const eligible=(roster||[]).filter(combatEligible),king=eligible.find((c)=>c.isRunKing);if(!king)return[];const selected=[king.id];let points=0;for(const c of eligible){if(c.id===king.id)continue;const cost=PIECE_VALUES[c.pieceType]??c.commandCost??0;if(selected.length>=MAX_SKIRMISH_PIECES||points+cost>MAX_SKIRMISH_POINTS)continue;selected.push(c.id);points+=cost;}return selected;}
function slotsFor(color){const home=color==='w'?'1':'8',front=color==='w'?'2':'7',mirror=(files)=>color==='w'?files:[...files].reverse();return{king:[`e${home}`,`e${front}`],queen:[`d${home}`,`d${front}`,`c${home}`,`f${home}`],rook:mirror(['a','h','a','h']).map((f,i)=>`${f}${i<2?home:front}`),bishop:mirror(['c','f','c','f']).map((f,i)=>`${f}${i<2?home:front}`),knight:mirror(['b','g','b','g']).map((f,i)=>`${f}${i<2?home:front}`),pawn:mirror([...FILES]).map((f)=>`${f}${front}`),fallback:[...mirror([...FILES]).map((f)=>`${f}${home}`),...mirror([...FILES]).map((f)=>`${f}${front}`)]};}
function placeArmy(army,color){const slots=slotsFor(color),occupied=new Set(),placements=[];const sorted=[...army].sort((a,b)=>a.pieceType==='king'?-1:b.pieceType==='king'?1:0);for(const member of sorted){const type=member.pieceType||CODE_TYPE[member.type]||member.type,candidates=[...(slots[type]||[]),...slots.fallback],square=candidates.find((x)=>!occupied.has(x));if(!square)throw new Error('Skirmish army does not fit into two starting ranks');occupied.add(square);placements.push({id:member.id||null,name:member.name||null,pieceType:type,type:TYPE_CODE[type]||member.type,color,square});}return placements;}
function fenFromPlacements(placements,turn='w'){const board=new Map(placements.map((p)=>[p.square,p])),ranks=[];for(let rank=8;rank>=1;rank--){let row='',empty=0;for(const file of FILES){const p=board.get(`${file}${rank}`);if(!p){empty++;continue;}if(empty){row+=String(empty);empty=0;}const code=TYPE_CODE[p.pieceType]||p.type;row+=p.color==='w'?code.toUpperCase():code.toLowerCase();}if(empty)row+=String(empty);ranks.push(row);}return`${ranks.join('/')} ${turn} - - 0 1`;}
function generateEnemyArmy({playerPoints=0,playerCount=1,encounter}={}){const resolved=encounter||createEncounter(),random=seededRandom(`${resolved.seed}:${resolved.stars}:${playerPoints}:${playerCount}`),target=clamp(Math.round(Number(playerPoints||0)*(0.72+resolved.stars*.13)+resolved.stars*2),4,MAX_SKIRMISH_POINTS),army=[{id:'enemy.king',name:'Вражеский король',pieceType:'king',commandCost:0}];let points=0;const candidates=resolved.stars>=4?['queen','rook','bishop','knight','pawn']:resolved.stars>=2?['rook','bishop','knight','pawn','pawn']:['bishop','knight','pawn','pawn','pawn'];let guard=0;while(army.length<MAX_SKIRMISH_PIECES&&points<target&&guard<200){guard++;const affordable=candidates.filter((t)=>points+PIECE_VALUES[t]<=target);if(!affordable.length)break;const type=affordable[Math.floor(random()*affordable.length)],cost=PIECE_VALUES[type];army.push({id:`enemy.${type}.${army.length}`,name:`Вражеский ${type}`,pieceType:type,commandCost:cost});points+=cost;}return{army,points,target};}
function createBattlePlan({roster,selectedIds,encounter}={}){const validation=validateSelection(roster,selectedIds);if(!validation.ok)throw new Error(`Invalid Skirmish selection: ${validation.reason}`);const resolved=encounter||createEncounter(),enemy=generateEnemyArmy({playerPoints:validation.points,playerCount:validation.count,encounter:resolved}),white=placeArmy(validation.members,'w'),black=placeArmy(enemy.army,'b');return{encounter:resolved,selectedIds:validation.members.map((m)=>m.id),playerPoints:validation.points,enemyPoints:enemy.points,playerFormation:white,enemyFormation:black,fen:fenFromPlacements([...white,...black],'w')};}
function applyBattleOutcome(run,{capturedIds=[],status=null,playerColor='w'}={}){const captured=new Set(capturedIds||[]);let kingDied=false;const lost=status?.type==='checkmate'&&status.winner&&status.winner!==playerColor;const roster=(run?.roster||[]).map((c)=>{if(c.isRunKing&&lost){kingDied=true;return{...c,status:'dead'};}if(!c.isRunKing&&captured.has(c.id)&&c.status==='healthy')return{...c,status:'wounded'};return{...c};});const woundedIds=roster.filter((c)=>captured.has(c.id)&&!c.isRunKing&&c.status==='wounded').map((c)=>c.id);return{...run,roster,ended:Boolean(run?.ended||kingDied),endReason:kingDied?'king_dead':(run?.endReason||null),lastSkirmish:{result:status?.type||'unknown',winner:status?.winner||null,woundedIds,kingDied}};}
export {MAX_SKIRMISH_PIECES,MAX_SKIRMISH_POINTS,ENCOUNTER_TIERS,combatEligible,createEncounter,selectionSummary,validateSelection,defaultCombatSelection,placeArmy,fenFromPlacements,generateEnemyArmy,createBattlePlan,applyBattleOutcome};
